### ISSUE TITLE
pytest: autocompletion of options with a . fail

### ISSUE THREAD

**Issue by calestyo** [scop/bash-completion#1031]
## Describe the bug

It seems bash-completion is able to automatically complete custom options that are added by pytest modules with `pytest_addoption()` and in those `parser.addoption()` special functions.

I've noted, that when such option contains a `.` (like in `--module.function.param=foo`), the completion ignores everything starting with the `.`

I know, `.` in option names is quite unusual, but here it seems to just fit, when one has large number of tests, structured within test classes and these within test modules... and since the actual values that one wants to set may also use `-` (respectively `_`), `.` seems a "good" separator.

## To reproduce

One needs a `conftest.py` like:
```
def pytest_addoption(parser):
    parser.addoption("--using.dots-in-option-names-is-plain-dumb", type=int)
```
and pytest installed.

Then, in the directory with the `conftest.py` try `pytest --using<TAB>`… and it will not complete the `.dots-in-option-names-is-plain-dumb` but put a space right after `--using`.

## Expected behavior

Include the `.` and other "legit" characters (I guess at least also `.` and `_`) in completion.

## Versions (please complete the following information)

- [ ] Operating system name/distribution and version: Debian sid
- [ ] bash version, `echo "$BASH_VERSION"`: 5.2.15(1)-release
- [ ] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: 2.11

Thanks,
Chris.

**Comment by akinomyoga** [comment]
Is it widely used common practice to add option names with dots using `parser.addoption` in `conftest.py`? Or is it just a technical possibility?

**Comment by akinomyoga** [comment]
Because it is processed by a function common for long options of arbitrary commands, where `.` is explicitly processed as the terminator of the long option name. Some commands output the long option name suffixing a period.

**Comment by akinomyoga** [comment]
> OTOH, at least in principle other option parsers may allow `.`, too.

Please read the last sentence of https://github.com/scop/bash-completion/issues/1031#issuecomment-1674785262 again.

https://github.com/scop/bash-completion/blob/master/test/t/unit/test_unit_parse_help.py#L156

**Comment by calestyo** [comment]
I've had read the sentence :-)

Well I cannot say much more other than it would in principle be nice to have even such unusual option names be supported, but if you guys say it's not possible or not worth the effort, than there's nothing left but closing the issue.

**Comment by scop** [comment]
Quite a corner case, yeah. I haven't had a look at the code, but my gut feeling is that it could be in principle ok to terminate the option parsing only on `.` that is _not followed by `[A-Za-z0-9]`_. Also, I don't remember offhand if bash regular expressions support lookahead, which might be needed to easily accomplish this.

**Comment by akinomyoga** [comment]
> terminate the option parsing only on `.` that is _not followed by `[A-Za-z0-9]`_.

Ah, OK. That is one way of defining the behavior of the help parser.

Then, I think we can think of it in the other way, i.e., matching regex to the prefix to keep, instead of matching it to the suffix to remove.

```diff
index 655709d4..bf823c93 100644
--- a/bash_completion
+++ b/bash_completion
@@ -1445,11 +1445,9 @@ _comp_compgen_help__parse()
         option=${option/"${BASH_REMATCH[1]}"/"${BASH_REMATCH[2]}"}
     fi

-    option=${option%%[<{().[]*}
-    option=${option/=*/=}
-    [[ $option ]] || return 1
-
-    _options+=("$option")
+    [[ $option =~ ^([^=<{().[]|\.[A-Za-z0-9])*=? ]]
+    [[ $BASH_REMATCH ]] || return 1
+    _options+=("$BASH_REMATCH")
 }

 # Parse GNU style help output of the given command and generate and store
```

**Comment by scop** [comment]
Yeah, seems to me that would work nicely. PR along with a test case welcome :)

**Comment by akinomyoga** [comment]
https://github.com/scop/bash-completion/pull/1038
