### ISSUE TITLE
use of `$FUNCNAME` when `set -u` is in place and `FUNCNAME` was unset

### ISSUE THREAD

**Issue by calestyo** [scop/bash-completion#1062]
## Describe the bug

Throughout the code `$FUNCNAME` is used, which causes an unbound error, if `set -u` is in place and `FUNCNAME` was unset.

Interestingly, which I don't quite understand why, one can `unset FUNCNAME` even outside a function (where I thought it wasn't supposed to exist) and it will have the effect of it being no longer special.

## Expected behavior

I guess `${FUNCNAME-}` or so should be used.

## Additional context

If it helps, I could provide a PR, but I have no idea which value we should use (especially also in the `FUNCNAME[i]` cases)... simply `unknown`?<br>
The empty string? Though that would look ugly in many error messages (because of the `"bash_completion: : message`)... so maybe use something `${FUNCNAME:+"$FUNCNAME": }` and print the `: ` via that (and only if there is a funcname?

Thanks,
Chris.

**Comment by calestyo** [comment]
Oh, I haven't really checked whether any of `bash`’s other "special" variables that can be unset are used in a fashion that would cause errors when `set -u` is in use.

Maybe that should be done.

**Comment by akinomyoga** [comment]
You shouldn't unset the Bash special variables in an interactive *Bash* session even though it is possible. At least, bash-completion cannot be responsible for every kind of broken environment. There are many different ways to break the environment by removing or disabling the Bash built-in features.
- For example, one can overwrite builtin commands by functions, aliases, etc. To protect ourselves, one might use the `builtin` builtin, but a function or an alias can also overwrite the `builtin` builtin. One might then think about using the POSIX mode to access the builtins directly, but it again fails when the builtins are disabled by `enable -n`. If the `enable` builtin itself is disabled, then there is no way to recover the builtins.
- For another example, one can mark random variables `readonly` at the top level of the shell context (e.g. `readonly i`), and then any local variables of the same name cannot be defined.
- Unsetting `FUNCNAME` is a breakage of the fundamental environment at the same level. There are many similar variables including `BASH`, `COMP_WORDBREAKS`, `LINENO`, `OSTYPE`, `PATH`, `PWD`, etc. It might be worked around by checking the existence of all the variables, but it complicates the codebase unnecessarily.

I have a doubt about complicating the codebase just to protect us from such unrealistic cases.

A part of the reason that Bash allows unsetting these variables is for compatibility with the POSIX standard. For example, the standard does not define the variable `FUNCNAME`, so the variable should be able to be used by an application program written in a portable shell script. However, it is practically impossible to mix up the POSIX scripts (that use the variable names conflicting with the Bash special variables) and the Bash scripts. If you would like to unset `FUNCNAME`, you should do it in a standalone portable POSIX script. On the other hand, `bash-completion` is written in a Bash script (but not in a POSIX script), and it doesn't assume the POSIX environment where Bash features (including `FUNCNAME`) are not available or turned off.

**Comment by calestyo** [comment]
> I have a doubt about complicating the codebase just to protect us from such unrealistic cases.

Okay. Thus closing.
