### ISSUE TITLE
Wrong network interface name if the name is long

### ISSUE THREAD

**Issue by hellodword** [scop/bash-completion#1089]
## Describe the bug

network interface name get truncated with ifconfig

## To reproduce

```
$ ip link show up
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
3: nameislong: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN mode DEFAULT group default qlen 1000

$ ifconfig 
lo        Link encap:Local Loopback
eth0      Link encap:Ethernet
nameislongLink encap:(hwtype unknown)
```

https://github.com/scop/bash-completion/blob/2b7fc195aeb404b41bc3e5fa8c1e98f10f1ee26a/bash_completion#L1723-L1738

Then the `_comp_compgen_available_interfaces -a` will return `nameislongLink` instead of `nameislong`

Reproduce:

```sh
sudo tunctl -t nameislong
sudo ip addr add 10.23.45.0/24 dev nameislong
sudo ip link set dev  nameislong up

# TAB
curl --interface nameis
```

## Versions (please complete the following information)

- [x] Operating system name/distribution and version: `NixOS 24.05.20240102.bd645e8`
- [x] bash version, `echo "$BASH_VERSION"`: `5.2.21(1)-release`
- [x] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: `2.11`

## Additional context

It's bug of upstream inetutils, but maybe we can simply use iproute2 as default choose

`ip -c=never link show up || ip link show up || ifconfig`

https://github.com/scop/bash-completion/blob/2b7fc195aeb404b41bc3e5fa8c1e98f10f1ee26a/bash_completion#L1731-L1733

**Comment by yedayak** [comment]
BTW, which packages provide `ip` and `ifconfig` on your system? I get different outputs on my system, the outputs span multiple lines
