### ISSUE TITLE
README contains incomplete instructions for installation when starting from the git repo

### ISSUE THREAD

**Issue by mgedmin** [scop/bash-completion#11]
The README says
> If you don't have the package readily available for your distribution, or you simply don't want to use one, you can install bash completion using the standard commands for GNU autotools packages:
```./configure
make
make check # optional, requires dejagnu and tcllib
make install # as root
```

but if you clone this repository, you won't find a `./configure` in there.

There are two ways to improve this situation:

1. Point the user to release tarballs that presumably have `configure`
2. Tell the users to run `autoconf` after git clone, so a `./configure` will be generated from `configure.ac`

I would prefer method 1, since I'm currently dealing with an RHEL machine without bash completion and with a really ancient autoconf that fails the version check.

**Comment by mgedmin** [comment]
(I was personally unable to find a website hosting upstream release tarballs, so in the end I downloaded the .orig.tar.bz2 from http://packages.debian.org/bash-completion)

**Comment by scop** [comment]
It's not clear if we'll be publishing tarballs with `configure` in them in the future, so I added the note there at least for now.

Bash-completion for RHEL < 7 is available from https://fedoraproject.org/wiki/EPEL (version 1.x only though), and I assumee bash-completion 2.1 is included in RHEL 7; it is in CentOS 7.

**Comment by mgedmin** [comment]
Thank you!
