### ISSUE TITLE
env: Complete command as well

### ISSUE THREAD

**Issue by hseg** [scop/bash-completion#1111]
## Describe the feature/solution

`env`'s completion currently completes long flags and filenames.
Could we instead have `env` complete like `sudo`, where it first completes
`env`'s flags with their parameters, then some sequence of words containing `=`
(perhaps using `_comp_variable_assignments`?), then a command (using
`_comp_command_offset`)?

## Maintenance (please complete the following information)

- [ ] This is a request for new completion
- [ ] Link to upstream project query about shipping the completion:
Given the presence of completions for `coreutils` binaries in repo, I suppose
this has already been addressed?

**Comment by scop** [comment]
Makes sense, https://github.com/scop/bash-completion/pull/1118

**Comment by hseg** [comment]
Given #1118 has been merged (and a quick check confirms it works pretty much as expected), this can be closed, no?

**Comment by scop** [comment]
Ah yes, I should have used "Closes" instead of "Refs" in the commit message to make that happen automatically. Thanks!
