### ISSUE TITLE
Add weba to audio-file type

### ISSUE THREAD

**Issue by physkets** [scop/bash-completion#112]
A lot of VP9 and VP8 audio files come with the extension '.weba'. Could you add it to the extention list?

**Comment by scop** [comment]
I did a quick search and didn't come across any such files, nor did I find definitive information that .`weba` would be an extension to use for those file types. Can you point me to some samples with which I can verify that the player(s) indeed support opening files with that extension?

**Comment by physkets** [comment]
When ever I use FlashGot to download pure audio (by separating it from the stream) VP8/9 from youtube, it saves it as a '.weba'

Also: https://www.drupal.org/node/1347624
