### ISSUE TITLE
Missing doc/api-and-naming.md in 2.12.0 release tar.xz

### ISSUE THREAD

**Issue by yedayak** [scop/bash-completion#1124]
## Describe the bug
It seems the [tar.xz](https://github.com/scop/bash-completion/releases/download/2.12.0/bash-completion-2.12.0.tar.xz) release is missing the doc/api-and-naming.md file. Is this intentional?

## To reproduce
extract both tars in the assets in the [release](https://github.com/scop/bash-completion/releases/tag/2.12.0) compare, and see the file is missing in the official (?) tar.xz

## Versions (please complete the following information)
- [ ] bash-completion version: 2.12.0
## Additional context
Trying to package the new version

**Comment by akinomyoga** [comment]
> Is this intentional?

I don't think it's intentional. I made #1125.
