### ISSUE TITLE
Readline colors command completions as files (red blinking text)

### ISSUE THREAD

**Issue by MayeulC** [scop/bash-completion#1161]
## Describe the bug
When completing commands, suggestions are displayed. However, readline considers them to be files. Since my configuration colors completed files by type (folder, executable, etc), readline runs a stat operation on the completions, and usually does not find matching files. It then colors them as missing files.

The result is that all command completions are listed as blinking bold white text on red background in my terminal, which is very annoying.

## To reproduce

With bash-completion loaded:

1. `echo "set colored-stats On" >> ~/.inputrc`
2. Open a new terminal
3. Start a completion such as `ls --<TAB><TAB>`

## Expected behavior

Text should be displayed in a neutral manner, or just respecting the `menu-color-display-prefix`

## Versions (please complete the following information)

- [X] Operating system name/distribution and version: Redhat 8
- [X] bash version, `echo "$BASH_VERSION"`: 4.4.20
- [X] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: 2.7

## Additional context

Tab completing bash variables does not highlight them as if they were files.

Interesting thread on RedHat/Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1648170

Small related thread on gentoo forums: https://forums.gentoo.org/viewtopic-p-8628015.html

Text is not necessarily going to blink, depending on your LS_COLORS, terminal, etc. But it is probably still highlighted as a missing file, like as a missing symlink target.

**Comment by akinomyoga** [comment]
The problem arises even with the plain Bash (without loading `bash-completion` or any other shell settings). This is an issue of the upstream Bash.

![image](https://github.com/scop/bash-completion/assets/8982192/3c6be7b9-235f-4322-bd9a-a36421fb1522)

**Comment by MayeulC** [comment]
Ah, I see, thank you. This can probably be closed then ?

**Comment by akinomyoga** [comment]
Yeah. You can post an email to bug-bash@gnu.org.
