### ISSUE TITLE
Gentoo update to 2.14 fails due to QA notice

### ISSUE THREAD

**Issue by glparton** [scop/bash-completion#1189]
## Describe the bug
Update fails on gentoo:
app-shells/bash-completion-2.14.0::gentoo failed 

## To reproduce

Trying to update to 2.14 with emerge on gentoo.

## Expected behavior

updates no issue

## Versions (please complete the following information)

- [ ] Operating system name/distribution and version: Gentoo (6.8.9-gentoo-dist)
- [ ] bash version, `echo "$BASH_VERSION"`: 5.2.26(1)-release
- [ ] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: 2.13.0

## Additional context

Using ~amd accepted keyword

## Debug trace
QA Notice: files installed in ${D}/${D}:
*   /
*   //usr
*   //usr/share
*   //usr/share/bash-completion
*   //usr/share/bash-completion/completions
*   //usr/share/bash-completion/completions/python3.13
* ERROR: app-shells/bash-completion-2.14.0::gentoo failed:
*   Aborting due to QA concerns: 6 files installed in /var/tmp/portage/app-shells/bash-completion-2.14.0/image/var/tmp/portage/app-shells/bash-completion-2.14.0/image
*
* Call stack:
*   misc-functions.sh, line 682:  Called install_qa_check
*   misc-functions.sh, line 134:  Called source 'install_symlink_html_docs'
*          05double-D, line  15:  Called DD_check
*          05double-D, line  11:  Called die
* The specific snippet of code:
*              die "Aborting due to QA concerns: ${#files[@]} files installed in ${D%/}${D}"

**Comment by scop** [comment]
Sounds like this is something to report to Gentoo. If not, please include specific instructions what we could do about it in this project.

**Comment by thesamesam** [comment]
Indeed, fixed in https://bugs.gentoo.org/931665. Sorry for the issue.
