### ISSUE TITLE
mkdir should optionally allow completion of files (as well as directories)

### ISSUE THREAD

**Issue by devkev** [scop/bash-completion#119]
A common use case is to want to make a directory with a name that is similar to an existing file.  eg. someone sent you `LongAndComplicated.zip`, which doesn't contain sub-directories, so you want to create a directory before unzipping this file.  It would be useful (and, without bash-completion, it is possible and the default behaviour) to type `mkdir Long<tab>`, then backspace the `.zip`, and press Enter to create the directory.

This makes sense for mkdir to have different behaviour to rmdir, because in the case of mkdir, the directory doesn't yet exist at the time of tab-completion (except possibly in the case of `mkdir -p`) - whereas for rmdir, the argument must exist and be a directory.

This came up in the past in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=376433 , and was fixed at the time in d9988bc84694185f1cc1869afa3370fe6d9bd477.  The fix was then (inadvertently?) reverted in 1b248b55021318e653a0ca81145829c9dc77c97b.

**Comment by scop** [comment]
While that use case does exist, it also means that mkdir will end up offering completions that are _certain to not work_ unless modified by the user. And in my opinion that is not something we want to do. 1b248b5 is not at at all inadvertent, as witnessed by the commit message and the added test case for it.

Note that filename completion can be always triggered with Esc+/ if you want that instead of what bash-completion offers. See the first FAQ entry in README.md.

**Comment by devkev** [comment]
I understand this, but there are plenty of completions that are destined to fail without further adjustment.  For example, file permissions aren't checked when determining possible completions, and rmdir doesn't check if directories are empty.

It's also not like the command gets submitted as soon as the completion happens.  The user always has the opportunity to adjust things (and no-one would want a completion system which didn't have this ability).  Do users really expect that it should always be able to press Enter after a tab completion, and have the command succeed?

In any case, I do understand the problem -  that providing the names of existing files, for an argument which needs to not exist, could be confusing for less experienced users.  Would you instead consider an approach which kept the current behaviour by default, but allowed knowledgeable users to choose this alternate behaviour via some configuration, eg. setting a particular environment variable?

PS. I apologise about "inadvertent" - I didn't mean that the change wasn't deliberate, or that you didn't know what you were doing, only that you perhaps may not have been aware of the earlier change.

**Comment by devkev** [comment]
I've updated the PR with an example for opt-in customisation.  Please consider it for merge.  If you'd prefer an alternate to using this environment variable, feel free to let me know.

Here's another use case where this behaviour would be very useful (annotated to show keystrokes):

```
$ mkdir 56<TAB>fe355e-5cdb-49aa-917b-5578cd7fbd13
$ mkdir 56<TAB>fe355e-5cdb-49aa-917b-5578cd7fbd13<TAB><TAB>
56fe355e-5cdb-49aa-917b-5578cd7fbd13_2.json  56fe355e-5cdb-49aa-917b-5578cd7fbd13_7.json
56fe355e-5cdb-49aa-917b-5578cd7fbd13_3.json  56fe355e-5cdb-49aa-917b-5578cd7fbd13_8.json
56fe355e-5cdb-49aa-917b-5578cd7fbd13_4.json  56fe355e-5cdb-49aa-917b-5578cd7fbd13_9.json
56fe355e-5cdb-49aa-917b-5578cd7fbd13_5.json  56fe355e-5cdb-49aa-917b-5578cd7fbd13.json
56fe355e-5cdb-49aa-917b-5578cd7fbd13_6.json
$ mkdir 56fe355e-5cdb-49aa-917b-5578cd7fbd13<ENTER>
$ mv 56<TAB>fe355e-5cdb-49aa-917b-5578cd7fbd13
$ mv 56<TAB>fe355e-5cdb-49aa-917b-5578cd7fbd13?* 56<TAB>fe355e-5cdb-49aa-917b-5578cd7fbd13<ENTER>
$ 
```

That is, completing mkdir on files doesn't necessarily mean that the user must make adjustments, for the command to succeed.

**Comment by devkev** [comment]
Can anything be done to advance this closer to something that you would consider merging?
