### ISSUE TITLE
CDPATH autocomplete is not working

### ISSUE THREAD

**Issue by arturoherrero** [scop/bash-completion#1202]
## Describe the bug

I have been using `CDPATH`  successfully for years, but a few months ago, the autocomplete function stopped working.

```sh
export CDPATH=".:~/projects"
```

I can still use it directly, eg. `cd dotfiles` to go into `cd ~/projects/dotfiles`, but typing `cd dot<TAB>` doesn't show any directory to autocomplete the name.

## Workaround

As a workaround, I can do the following and it works as expected:
```
complete -o nospace -F _cd cd
```

## Versions (please complete the following information)

- [x] Operating system name/distribution and version: macOS
- [x] bash version, `echo "$BASH_VERSION"`: 5.2.26(1)-release
- [x] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: 2.14.0

## Additional context

Some extra information that could be relevant. This is the output when is not working:
```sh
$ complete | grep " cd$"
complete -d cd
```

**Comment by akinomyoga** [comment]
> Some extra information that could be relevant. This is the output when is not working:
> 
> ```shell
> $ complete | grep " cd$"
> complete -d cd
> ```

I suspect that is caused by a different framework because `bash-completion` doesn't include such a setting:

- [Code search results](https://github.com/search?q=repo%3Ascop%2Fbash-completion+%2Fcomplete+.*+cd%5Cb%2F&amp;type=code)

**Comment by akinomyoga** [comment]
[This line](https://github.com/arturoherrero/dotfiles/blame/8edea42a87400ab4d437df1dcd0f3c309456ae67/.bash_settings#L25) in your config is causing the issue.

**Comment by arturoherrero** [comment]
@akinomyoga Thank you very much for the feedback. This is the magic of open source.

You are right, I can remove the following lines, and `CDPATH` works as expected.
```sh
complete -d cd
complete -o nospace -F _cd cd
```

I still have a configuration issue because I want to restrict the `cd` autocompletion to only directories, but now it also shows environment variables and Bash functions. Anyway, that's not a bash-completion bug.

**Comment by akinomyoga** [comment]
> I want to restrict the `cd` autocompletion to only directories, but now it also shows environment variables

That is related to [this setting](https://github.com/arturoherrero/dotfiles/blame/8edea42a87400ab4d437df1dcd0f3c309456ae67/.bash_settings#L7). The Bash feature `cdable_vars` allows you to specify a variable name to `cd` so that `cd` reads the content of the variable to pick the path to a directory. If you do not specify variable names to `cd`, you can remove that setting.

> and Bash functions.

Hmm, I'm not sure about this one. It doesn't complete the names of shell functions in my environment. Or maybe do you mean "the special variables of Bash" by "Bash functions"?

**Comment by arturoherrero** [comment]
@akinomyoga This is the output I was getting:

<img width="1449" alt="Screenshot 2024-06-10 at 13 53 30" src="https://github.com/scop/bash-completion/assets/392222/4b3e699c-f967-4a7e-9e88-0eb976102d31">

But you are right again, `shopt -s cdable_vars` was interfering here.

Thank you very much for your help! I've removed a few lines of code https://github.com/arturoherrero/dotfiles/commit/6e436f6d260135f511e461c50e3d9f50d5f34aa8
 achieving the same results 🙌
