### ISSUE TITLE
bash: _comp_initialize: command not found

### ISSUE THREAD

**Issue by BrandonGibbs** [scop/bash-completion#1209]
When I type out a command, a space, and then push tab, I get the following message (using 'man' as an example):
`man bash: _comp_initialize: command not found`

This happens with some commands, not all. These are some of the ones it happens with: 
- man
- python 
- sh
-  gcc
-  make
-  aur
-  ssh 

It doesn't happen with pip or mpv though. I ran
`grep _comp_initialize /usr/share/bash-completion/completions/<a command>`
and noticed only the commands which gave the error message referenced the '_comp_initialize' function. 

- [ ] Operating system name/distribution and version: running Arch Linux, 'uname -a' gives: Linux brandons-pc 6.9.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 26 May 2024 01:30:29 +0000 x86_64 GNU/Linux
- [ ] bash version is 5.2.26(1)-release
- [ ] bash-completion version is 2.14.0-1

**Comment by up4k** [comment]
Have you reloaded your shell for bash-completion to reinitialize after install/update?
I just stumbled upon the same issue after upgrading bash-completion, but after reloading the shell everything works as expected.

**Comment by BrandonGibbs** [comment]
I reloaded and now it works. Thank you!
