### ISSUE TITLE
_configured_interfaces() nor reading interfaces.d on stretch

### ISSUE THREAD

**Issue by Aydan** [scop/bash-completion#121]
_configured_interfaces() does not read /etc/network/interfaces.d so tab completion (for ifup/ifdown) only works for interfaces defined in /etc(/network/interfaces but not for interfaces defined in /etc/network/interfaces.d

this is on Debian Stretch with bash-completion 1:2.1-4.3

**Comment by scop** [comment]
I don't think I have access to a system with files present in that dir or
other info what they contain, so will need more info (e.g. a couple of
sample files)
or someone else to look into it.

**Comment by Aydan** [comment]
The files contain sections from /etc/network/interfaces:
e.g. interfaces.d/lo would contain
```
auto lo
iface lo inet loopback
```
interfaces.d/eth0 would contain
```
auto eth0
allow-hotplug eth0
iface eth0 inet dhcp
```
and /etc/network/interfaces contains
```
# interfaces(5) file used by ifup(8) and ifdown(8)
# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d
```
so each interface has it's own file.

Regards
Aydan

**Comment by Aydan** [comment]
Sorry, I hit the wrong button

**Comment by scop** [comment]
Commit 5f39e73c73a9fde4195ae0edd3718f0d051fbeb2 in the fix_121 branch should fix this. Could you test and report back?

**Comment by Aydan** [comment]
looks good so far, i'm seeing all my configured interfaces now, but the cleaner way would probably be to look for the "source-directory" stanza in /etc/network/interfaces and use the directory given there. This solution should cover even user specific configurations, not only the default one.

**Comment by scop** [comment]
Sure. Clean and robust pull requests implementing that are welcome. In the meantime, this implementation should work for the vast majority of cases.
