### ISSUE TITLE
man: completion punts on e.g. MSYS2

### ISSUE THREAD

**Issue by SamB** [scop/bash-completion#122]
So, I was wondering why `man` commands weren't completing in my MSYS2 shells, and it turns out that it's [because of these lines at the beginning of bash_completion/man](https://github.com/scop/bash-completion/blob/master/completions/man#L3):

```sh
[[ $OSTYPE == *@(darwin|freebsd|solaris|cygwin|openbsd)* ]] || _userland GNU \
    || return 1
```

On my system, MSYS2 shells have have an `$OSTYPE` of `msys`, and `uname -s` can be `MSYS_NT-6.1`, `MINGW64_NT-6.1`, or `MINGW32_NT-6.1` depending on the value of `$MSYSTEM` (which is also used by `/etc/profile` to decide what, besides `/usr/local/bin:/usr/bin:/bin`, needs to be added to the path).  Presumably, the numbers change depending on the version of NT.

However, I can't help but wonder if there isn't a better way to detect whether or not the **[man-db](http://man-db.nongnu.org/)** package is installed, if that's even important in the first place: is this support specific to man-db, or does it also work with other implementations of man? If the latter, what purpose do these conditionals serve? (There's another one further down relating to `manpath` that is similarly questionable.)

**Comment by scop** [comment]
The completion is not at all specific/limited to man-db. I'm not sure why the OSTYPE etc checks were there for, but they're gone now. The other questionable one you're probably referring to was removed over a year ago in c9f54e7a411613cbfba2b200d35059f5bcb87113.
