### ISSUE TITLE
Completions are not loaded in Linux+Homebrew

### ISSUE THREAD

**Issue by cippaciong** [scop/bash-completion#1233]
## Describe the bug

Completions are not loaded in Linux when using Homebrew and the [bash_completion.sh](https://github.com/scop/bash-completion/blob/main/bash_completion.sh.in) script shipped with `bash-completion@2`

## To reproduce

I'm not sure I'm able to tell exactly how to reproduce it on a clean environment, but the following should work

1. Install Homebrew on Linux
2. Install bash and bash-completion with `brew install bash bash-completion@2`
3. Load bash-completion in `.bash_profile` or `.profile` with:
```sh
[[ -r "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh" ]] && . "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh"
```

## Expected behavior

Bash completions for Homebrew and packages installed via Homebrew should work but they don't

## Versions (please complete the following information)

- [ ] Operating system name/distribution and version: Ubuntu 22.04.4 LTS
- [ ] bash version, `echo "$BASH_VERSION"`: 5.1.16(1)-release
- [ ] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: 2.14.0

## Additional context

I did some investigation and it seems that the problem is the check performed here: https://github.com/scop/bash-completion/blob/e209afb2d0c96ee6bfe83da8b2742a8f8e88d372/bash_completion.sh.in#L3

The first two checks pass, but the last one (`"x${BASH_COMPLETION_VERSINFO-}" = x`) doesn't because `${BASH_COMPLETION_VERSINFO}` is equal to `2` hence the check becomes `x2 = x` and fails.

As a result, the whole logic to load bash_completion is skipped. If I manually remove the last check (`if [ "x${BASH_VERSION-}" != x -a "x${PS1-}" != x ]; then`) then it works and I have bash-completion for all my Homebrew packages

## Debug trace

```
if [ "x${BASH_VERSION-}" != x -a "x${PS1-}" != x -a "x${BASH_COMPLETION_VERSINFO-}" = x ]; then
# if [ "x${BASH_VERSION-}" != x -a "x${PS1-}" != x ]; then

    # Check for recent enough version of bash.
    if [ "${BASH_VERSINFO[0]}" -gt 4 ] ||
        [ "${BASH_VERSINFO[0]}" -eq 4 -a "${BASH_VERSINFO[1]}" -ge 2 ]; then
        [ -r "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion" ] &&
            . "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion"
        if shopt -q progcomp && [ -r /home/linuxbrew/.linuxbrew/Cellar/bash-completion@2/2.14.0/share/bash-completion/bash_completion ]; then
            # Source completion code.
            . /home/linuxbrew/.linuxbrew/Cellar/bash-completion@2/2.14.0/share/bash-completion/bash_completion
        fi
    fi
fi
+++ '[' 'x5.1.16(1)-release' '!=' x -a 'x${debian_chroot:+($debian_chroot)}\u@\h:\w\$ ' '!=' x -a x2 = x ']'
set +xv
+++ set +xv
```

**Comment by cippaciong** [comment]
I forgot to mention one thing that I guess it's relevant and might be the reason why `BASH_COMPLETION_VERSINFO` already has a value: I also have `bash` and `bash-completion` installed from the main Ubuntu repositories.

```sh
$ dpkg -l | grep -i bash
ii  bash                                       5.1-6ubuntu1.1                                    amd64        GNU Bourne Again SHell
ii  bash-completion                            1:2.11-5ubuntu1                                   all          programmable completion for the bash shell
```

I need them to be installed to have completion also for system packages not installed through Homebrew (I think?)

**Comment by yedayak** [comment]
> I forgot to mention one thing that I guess it's relevant and might be the reason why `BASH_COMPLETION_VERSINFO` already has a value: I also have `bash` and `bash-completion` installed from the main Ubuntu repositories.
> 
> ```shell
> $ dpkg -l | grep -i bash
> ii  bash                                       5.1-6ubuntu1.1                                    amd64        GNU Bourne Again SHell
> ii  bash-completion                            1:2.11-5ubuntu1                                   all          programmable completion for the bash shell
> ```
> 
> I need them to be installed to have completion also for system packages not installed through Homebrew (I think?)

I don't think you need both - it seems both the ubuntu package and the homebrew one basically ship the same code - this repo. What completions specifically don't work for you?

**Comment by cippaciong** [comment]
You're absolutely right. For some reasons, I thought that the ubuntu package was providing additional completions, but this is not the case.
I removed the ubuntu package and everything works as expected now. Thanks for the help 🙂
