### ISSUE TITLE
wine: Match on .bat/.cmd files

### ISSUE THREAD

**Issue by ToadKing** [scop/bash-completion#1257]
## Describe the feature/solution

Batch scripts (.bat and .cmd) are common for some scripts or automating Windows programs, so it would be useful to pick them up in auto-completion. (The extensions are case-insensitive, like all Windows file extensions.)

## Maintenance (please complete the following information)

- [ ] This is a request for new completion
- [ ] Link to upstream project query about shipping the completion:

**Comment by scop** [comment]
Does plain `wine foo.bat` (and .cmd) work, or does one need to do something like `wine cmd foo.bat`? Some searching around gave pointers (albeit old) to the latter.

**Comment by scop** [comment]
Confirmed working in the wine that ships with Ubuntu 24.04, PR in #1266
