### ISSUE TITLE
__git_ps1: command not found.

### ISSUE THREAD

**Issue by monouser7dig** [scop/bash-completion#127]
2.6 does seem to brake git-completition in some configs

I'm on macOS Sierra, bash4 and bash-completion@2 installed by homebrew and now get

__git_ps1: command not found.
(using bash 4)

[https://github.com/Homebrew/homebrew-core/commit/455a807a8c41fd735ef42cb202f87d3873b7667c](https://github.com/Homebrew/homebrew-core/commit/455a807a8c41fd735ef42cb202f87d3873b7667c)

I'll provide any other information if necessary, thanks in advance for any help

**Comment by scop** [comment]
bash-completion does not define or use `__git_ps1`, it comes from git itself (and probably your `~/.bashrc`, at least that's where mine is on my Fedora 25 system) so I don't know how/why bash-completion would break it.

**Comment by monouser7dig** [comment]
ok this seems logical at first, the issue came up just after upgrading bash-completion though and worked just fine before so that was my best guess, the rest remained unchanged.

Do you have any other objections as to why that could brake?

**Comment by scop** [comment]
Nope.

**Comment by monouser7dig** [comment]
some completions like tmux also stopped working so I do think something is wrong with the new bash-completion

**Comment by scop** [comment]
By the way, if #131 is the reason why your `__git_ps1` was not defined, I'd say you have installed it incorrectly, possibly by placing `git-prompt.sh` in your `bash_completion.d` dir. Prompt stuff is unrelated to completions, so their enablement should not be dependent on bash-completion and it would be better to place `git-prompt.sh` in e.g. `/etc/profile.d` or some other dir which gets loaded by bash itself, or source it in your personal `~/.bashrc`.

**Comment by monouser7dig** [comment]
ok thanks for the tip, however I just used it as it came installed by installing the packages using homebrew I guess

**Comment by scop** [comment]
In that case, I suggest filing an issue against whatever in homebrew sets it up that way.

**Comment by monouser7dig** [comment]
homebrew actually creates an alias into /usr/etc/bash_completion.d

`source /usr/local/etc/bash_completion.d/git-prompt.sh`
thanks, was just my fault!
