### ISSUE TITLE
make: 'bash: set +o posix: command not found' when IFS=$'\n'

### ISSUE THREAD

**Issue by mgorny** [scop/bash-completion#143]
To reproduce:

```
$ IFS=$'\n'
$ make <tab>
```

It causes the output to look like:
```
$ make bash: set +o posix: command not found
bash: set +o posix: command not found

Display all 124 possibilities? (y or n)
```

etc., i.e. it works but prints two `set +o posix` errors every time it completes.

Original report: https://bugs.gentoo.org/530246

**Comment by scop** [comment]
This in completions/make appears to be one candidate fix, not sure if it's the best one:

```diff
-        $reset
+        local IFS+=' '; $reset
```

And we probably have a bunch of other cases (at least all similar `shopt` constructs) lurking here and there, possibly others as well. Not sure if we should even try to support arbitrary `IFS` environments...

**Comment by mgorny** [comment]
Well, to be honest I don't know whether it's worth supporting either. This has been reported by an user who actually did hit this, so might be worth fixing it on per-case basis. However, if you feel like it's too much of an hassle, feel free to reject it and I'll forward the answer appropriately.

As for the technical details, I'm afraid IFS is too much of a brainf* for me. I always get lost on where it exactly gets used and where not. I'm not sure if the best solution wouldn't be to simply override IFS for the whole function scope, unless we actually need to respect it somewhere.

**Comment by scop** [comment]
There's no central place we could use for setting an expected IFS, so I opted to tweak the cases I could find. I kept the IFS setting close to where it's needed in order to give a hint/reminder why it is there.
