### ISSUE TITLE
Bashcomp + Gentoo + ctrl-Z signal brokes the shell

### ISSUE THREAD

**Issue by mirefek** [scop/bash-completion#148]
The following procedure leads to a broken shell:
Say there is a file something.pdf and a pdf-viewer evince installed.
$ evince somethi<tab>
->
$ evince something.pdf<enter>
... evince is running, return back to the terminal, press ctrl-Z (SIGSTP signal)
-> The shell is broken -- no pressed key is visible (even though they are registered and can work when I am able to type blindfold).

It is not an issue of a particular completion, evince was just an example. The same happens if a private script running sleep command is used instead.

I can reproduce it on Gentoo Linux, bash 4.3.48(1), bash-completion 2.4-r1 or 2.7. However this bug does not occur with bash-completion 2.1 or without it completely. I am not sure whether it is rather a bug of bash or a bug of bash-completion but it is a bug for sure :-)

**Comment by scop** [comment]
Doesn't happen to me on Fedora 25, bash 4.3.43(1)-release, current bash-completion master branch. But then again I'm not sure exactly where in your reproducer bash-completion is involved, i.e. where do you hit the TABs? Anyway I suspect something quite specific to your setup, as the described use case as I understand it is a fairly common one and I think lots of people would yell if it was broken for everyone.

**Comment by mirefek** [comment]
Thank you for your reply.
I press the tab in the middle of "something" -- that is
$ evince somethi[tab] ---auto-completed---> something.pdf [enter]
One more thing, the reproduction is reliable if it is the first command or just after loading bash_completion ("$ . /usr/share/bash-completion/bash_completion"). For some reason the following procedure does not break the shell:
$ evince somethi[tab] ---auto-completed---> something.pdf [enter]
Quit evince.
(again)$ evince somethi[tab] ---auto-completed---> something.pdf [enter]
Ctrl-Z
--> everything is allright.

I managed to reproduce it on another (school) Gentoo via ssh. Unfortunately all other distributions I can reach are Ubuntu's with bash-completion 2.1. So, if it does occur on Fedora, could it be something Gentoo-specific (gentoo-specific completions)?
Is there anything you would like to see like the environment variables, bashrc or things like that?

It took me a while until I discovered how to reproduce the occasionally broken shell and that it is related to the installed version of bash-completion, so perhaps people would like to yell but they are unsure what.

**Comment by scop** [comment]
Other than the instructions in bash-completion's README.md (the Troubleshooting section), I don't have any suggestions offhand. Perhaps you can post the output in your shell in `set -x` mode when you invoke the problematic completion and I can see if there's something in it that I can spot. I don't have that high hopes though. Can you reproduce it with basically any command, let's say a console application? Asking because if it's reproducible that way, perhaps a reproducer and debug environment for it can be built as a docker container (if Gentoo has docker images, I don't know).

**Comment by mirefek** [comment]
Yes, I can invoke that by basically any command. I could temporarily send you my login to school by e-mail, so you can see it.

After some research I have to admit that it is a specific issue partially caused by a patch for Gentoo which enables blacklisting of some completions.
https://bitbucket.org/mgorny/bashcomp2/downloads/
The issue does not occur when this patch is not included
```
diff --git a/bash_completion b/bash_completion
index 8c9fc81..5064733 100644
--- a/bash_completion
+++ b/bash_completion
@@ -1959,6 +1959,17 @@ complete -F _minimal ''
 # set up dynamic completion loading
 _completion_loader()
 {
+    if grep -F -x -q -s "${1##*/}" /etc/bash/completion.blacklist; then
+        if ! grep -F -x -q -s "${1##*/}" ~/.config/bash_completion.whitelist; then
+            complete -F _minimal "$1" && return 124
+            return 1
+        fi
+    fi
+    if grep -F -x -q -s "${1##*/}" ~/.config/bash_completion.blacklist; then
+        complete -F _minimal "$1" && return 124
+        return 1
+    fi
+
     # $1=_EmptycmD_ already for empty cmds in bash 4.3, set to it for earlier
     local cmd="${1:-_EmptycmD_}" compdir=./completions compfile
     [[ $BASH_SOURCE == */* ]] && compdir="${BASH_SOURCE%/*}/completions"
```
But, on the other hand, the issue does not occur on Ubuntu even with the patch. I could perhaps address the Gentoo bugzilla...

**Comment by mirefek** [comment]
debugging set -x results:
With Gentoo patch (so shell got broken): http://atrey.karlin.mff.cuni.cz/~mirecek/bashcomp-broken
sourced bash_completion file: http://atrey.karlin.mff.cuni.cz/~mirecek/bash_completion
Wthout Gentoo patch: http://atrey.karlin.mff.cuni.cz/~mirecek/bashcomp-working
(test.sh is just a simple script running sleep 10, something is an empty file)
```
$ diff bashcomp-working bashcomp-broken 
3,59d2
< + local cmd=./test.sh
< + __load_completion ./test.sh
< + dirs=(${BASH_COMPLETION_USER_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion}/completions)
< + local -a dirs
< + local 'OIFS= 	
< ' IFS=: dir cmd=./test.sh compfile
< + for dir in '${XDG_DATA_DIRS:-/usr/local/share:/usr/share}'
< + dirs+=($dir/bash-completion/completions)
< + for dir in '${XDG_DATA_DIRS:-/usr/local/share:/usr/share}'
< + dirs+=($dir/bash-completion/completions)
< + IFS=' 	
< '
< + [[ /usr/share/bash-completion/bash_completion == */* ]]
< + dirs+=("${BASH_SOURCE%/*}/completions")
< + for dir in '"${dirs[@]}"'
< + for compfile in '"${cmd##*/}"' '"${cmd##*/}".bash' '_"${cmd##*/}"'
< + compfile=/home/mirek/.local/share/bash-completion/completions/test.sh
< + [[ -f /home/mirek/.local/share/bash-completion/completions/test.sh ]]
< + for compfile in '"${cmd##*/}"' '"${cmd##*/}".bash' '_"${cmd##*/}"'
< + compfile=/home/mirek/.local/share/bash-completion/completions/test.sh.bash
< + [[ -f /home/mirek/.local/share/bash-completion/completions/test.sh.bash ]]
< + for compfile in '"${cmd##*/}"' '"${cmd##*/}".bash' '_"${cmd##*/}"'
< + compfile=/home/mirek/.local/share/bash-completion/completions/_test.sh
< + [[ -f /home/mirek/.local/share/bash-completion/completions/_test.sh ]]
< + for dir in '"${dirs[@]}"'
< + for compfile in '"${cmd##*/}"' '"${cmd##*/}".bash' '_"${cmd##*/}"'
< + compfile=/usr/local/share/bash-completion/completions/test.sh
< + [[ -f /usr/local/share/bash-completion/completions/test.sh ]]
< + for compfile in '"${cmd##*/}"' '"${cmd##*/}".bash' '_"${cmd##*/}"'
< + compfile=/usr/local/share/bash-completion/completions/test.sh.bash
< + [[ -f /usr/local/share/bash-completion/completions/test.sh.bash ]]
< + for compfile in '"${cmd##*/}"' '"${cmd##*/}".bash' '_"${cmd##*/}"'
< + compfile=/usr/local/share/bash-completion/completions/_test.sh
< + [[ -f /usr/local/share/bash-completion/completions/_test.sh ]]
< + for dir in '"${dirs[@]}"'
< + for compfile in '"${cmd##*/}"' '"${cmd##*/}".bash' '_"${cmd##*/}"'
< + compfile=/usr/share/bash-completion/completions/test.sh
< + [[ -f /usr/share/bash-completion/completions/test.sh ]]
< + for compfile in '"${cmd##*/}"' '"${cmd##*/}".bash' '_"${cmd##*/}"'
< + compfile=/usr/share/bash-completion/completions/test.sh.bash
< + [[ -f /usr/share/bash-completion/completions/test.sh.bash ]]
< + for compfile in '"${cmd##*/}"' '"${cmd##*/}".bash' '_"${cmd##*/}"'
< + compfile=/usr/share/bash-completion/completions/_test.sh
< + [[ -f /usr/share/bash-completion/completions/_test.sh ]]
< + for dir in '"${dirs[@]}"'
< + for compfile in '"${cmd##*/}"' '"${cmd##*/}".bash' '_"${cmd##*/}"'
< + compfile=/usr/share/bash-completion/completions/test.sh
< + [[ -f /usr/share/bash-completion/completions/test.sh ]]
< + for compfile in '"${cmd##*/}"' '"${cmd##*/}".bash' '_"${cmd##*/}"'
< + compfile=/usr/share/bash-completion/completions/test.sh.bash
< + [[ -f /usr/share/bash-completion/completions/test.sh.bash ]]
< + for compfile in '"${cmd##*/}"' '"${cmd##*/}".bash' '_"${cmd##*/}"'
< + compfile=/usr/share/bash-completion/completions/_test.sh
< + [[ -f /usr/share/bash-completion/completions/_test.sh ]]
< + return 1
< + complete -F _minimal -- ./test.sh
< + return 124
```
And I can reproduce it even on Ubuntu now.

**Comment by scop** [comment]
Reporting in Gentoo bugzilla sounds appropriate, perhaps close here if it's not "our" bug?

The first thing I'd have a look at are the `return 1`s -- I don't know what return value 1 means as far as the default completion loader function for bash goes, and the man page doesn't document it. It only documents behavior with return value 124. Maybe I'd try out replacing them with plain `return`s and see if that has any effect.

**Comment by mirefek** [comment]
OK, I will send it there. But it is not entirely clear to me "whose" bug that is, so I will keep it also here for a while. It looks like that just a very simple alternation of "_completion_loader" causes troubles. After some experiments I have discovered that just the grep itself induces the issue (but not other commands like echo or true). That is, if I insert a line
```
grep -F -x -q -s expression nonexisting-file
```
at the begin of the function `_completion_loader`, the procedure with
```
./test.sh some[tab]thing [enter]
[ctrl-Z]
```
causes braking the shell (reproduced on Gentoo and Ubuntu).

**Comment by scop** [comment]
I'm pretty sure such a bug wouldn't be bash-completion's; defining a simpler completion loader function and just provoking the issue with it would prove that, something like:

```
my_loader() {
  # insert offending code here
}
complete -D -F my_loader

```

**Comment by mirefek** [comment]
I do not claim that this is a bash-completion bug. I was just curious how a simple grep query can represent offending code.
In case it should not, it could be a hint for a more secret improper behaviour, that was the reason I wanted to keep it open for a while.
However, you seem confident that this bug has nothing to do with the original bash-completion code, so I am closing it.
