### ISSUE TITLE
Alias to ls (longer than 1 character) add space instead of '/' to the end of directory

### ISSUE THREAD

**Issue by pevik** [scop/bash-completion#153]
commit c41a76237bc9dcbfa326eeddd026b66d7646d91d introduced bug for alias longer than 1 character add space instead of '/' to the end of directory.

Using `ls` command itself works:
```
ls /tm<tab>
ls /tmp/| # '|' is cursor
```

But completion with `ls` aliased is broken:
```
alias xx=ls
xx /tmp<tab>
xx /tmp | # '|' is cursor
```
Aliases one character long are working.

Exporting `BASH_COMPLETION_COMPAT_DIR` variable also helps, so there is a workaround.
`export BASH_COMPLETION_COMPAT_DIR=/etc/bash_completion.d`

**Comment by scop** [comment]
I don't see how c41a762 would be causing an issue like this, and I cannot reproduce it with current master myself, so more information is needed; see e.g. the Troubleshooting section in README.md.

**Comment by pevik** [comment]
@scop you're right, it must be a problem with my current setup. I'll double check it and reopen it if it's really not caused by my configuration. Sorry for invalid bug report.
