### ISSUE TITLE
Completion for umount fails if target contains spaces

### ISSUE THREAD

**Issue by SammysHP** [scop/bash-completion#159]
In case you have a mount point like `/mnt/foo bar` the completion for _umount_ returns only `/mnt/foo` because it parses the output of `mount` with space as the delimiter.

I don't know if `findmnt` is cross platform compatible. If yes, an easy fix would be to use

```diff
-    COMPREPLY=( $( compgen -W '$( mount | cut -d" " -f 3 )' -- "$cur" ) )
+    COMPREPLY=( $( compgen -W '$( findmnt -lno TARGET )' -- "$cur" ) )
```

in [completions/umount](https://github.com/scop/bash-completion/blob/master/completions/umount). Otherwise the change could be done in [completions/umount.linux](https://github.com/scop/bash-completion/blob/master/completions/umount.linux).

**edit:** I just see that the default path is `_linux_fstab < /proc/mounts`. This means that there must be a bug somewhere that escaped characters (like `/mnt/foo\040bar`) are unescaped.

**Comment by scop** [comment]
There's a bunch of test cases in `test/lib/completions/umount.exp`; if you have a reproducer, could you submit a patch that adds the failing case to that file?

**Comment by SammysHP** [comment]
AFAICS the test cases cover my issue. I have bash-completion 2.7 and with

```
$ cat /proc/mounts 
/dev/sdd /media/FOO\040BAR ext4 …
```

`$ umount /media/F` is completed as `$ umount /media/FOO `.

**Comment by ttencate** [comment]
Same here. I ran the tests, and they all pass, yet the actual completion still doesn't work right.

@SammysHP Note that `completions/umount` is only used on non-Linux systems. On Linux, `completions/umount.linux` is sourced and then the script returns. So the problem isn't with `mount` output but with `fstab` output, because my OS is detected correctly:

    $ [[ $OSTYPE == *linux* ]] && echo We are on linux
    We are on linux

**Comment by ttencate** [comment]
@SammysHP Are you, like me, on Arch Linux by any chance? Because...

    $ pacman -Qo /usr/share/bash-completion/completions/umount
    /usr/share/bash-completion/completions/umount is owned by util-linux 2.30.2-1

The `mount`, `umount` and `rfkill` scripts on Arch are coming from `util-linux`, not `bash-completion`. See the [PKGBUILD](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/bash-completion).

**Comment by SammysHP** [comment]
> Are you, like me, on Arch Linux by any chance? Because...

Yes, I am. Thanks for debugging it, I totally forgot this issue.

**Comment by ttencate** [comment]
@scop I think we were both barking up the wrong tree, so this can be closed then. Sorry for the noise!
