### ISSUE TITLE
man completion hindered if MANPATH is set

### ISSUE THREAD

**Issue by veselov** [scop/bash-completion#160]
Hi.

I actually came to this through https://github.com/TACC/Lmod/issues/191
The are packages that modify manpath, but leave an empty colon, which indicates to `man` that default manpath should be injected at that location.

The man autocompleter uses `$MANPATH`, and only invokes `man -w` if `$MANPATH` was empty. IMHO, it should call `man -w`. I don't see a situation where the value of `$MANPATH` individually should supercede.

To reproduce this problem, set your `$MANPATH` to `:xxx`, you would see that man pages still open up, but autocompleter can not suggest a single man page.

**Comment by scop** [comment]
Related test cases in 3b2fd04caa12b720d941d27b751e76a32af8290e
