### ISSUE TITLE
SSH completion doesn't account for "Include"

### ISSUE THREAD

**Issue by dlamblin** [scop/bash-completion#162]
If you look at `ssh_config(5)` you'll see that an `Include` keyword is available.
But if I use it to move a subsection of the ~/.ssh/config file out to another file, Changing EG:

    #~/.ssh/config
    Host dev
    Hostname garrulous-development-host-name.in.a.company.that.likes.its.own.tld

To:

    #~/.ssh/config
    Include team.config

    #~/.ssh/team.config
    Host dev garrulous-development-host-name
    Hostname garrulous-development-host-name.in.a.company.that.likes.its.own.tld

The completion for `ssh de<tab>` is no longer `ssh dev`; nor is `ssh garr<tab>` going to complete.

I looked through completions/ssh but haven't found what parses the Host line.

To make things FUNplicated, the Include line has to be one of the first keywords or it doesn't seem to work at all. It can probably be used multiple times. It can have multiple whitespace separated files identified. They can be relative to ~/.ssh/ OR use ~/ or / for specific absolute paths. And they can include globs like: `Include */*.config`. Of course a command can also use `-o Include file` or `-F file` to change the intended behavior, and it would be amazing if these also were parsed during autocomplete.

**Comment by dlamblin** [comment]
I appear to be using an outdated version of the file.
Let me update to one that includes:
https://github.com/scop/bash-completion/commit/1016e4336c2eaa95888275df6ea248b4e913fb76
You might blame a brew.sh recipe for purposefully getting an out of date version for the reason "it requires Bash 4, and macOS ships with 3.2.57."

I do indeed have: 3.2.57(1)-release

**Comment by RickTorresJr** [comment]
@dlamblin Had the same issue on Kali Linux Rolling. Backing up and downloading the raw file in the version you provided worked `/usr/share/bash-completion/bash_completion` . Thanks.
