### ISSUE TITLE
__get_cword_at_cursor_by_ref fails with syntax error. 

### ISSUE THREAD

**Issue by Dark-Feather** [scop/bash-completion#168]
Description:
bash_completion throws an error around __get_cword_at_cursor_by_ref() complaining that the line "local cword words=()" has an unexpected token '('. This causes issues with tab-complete unless users issue a 'complete -r' command.

Additional info:
|> pacman -Qo /usr/share/bash-completion/bash_completion
/usr/share/bash-completion/bash_completion is owned by bash-completion 2.7-1

My bash.bashrc: 
https://aninix.net/cgit/cgit.cgi/MiscScripts/tree/ShadowArch/bashrc 

My profile:
https://aninix.net/cgit/cgit.cgi/MiscScripts/tree/ShadowArch/profile

Steps to reproduce:
source /usr/share/bash-completion/bash_completion

Previously investigated in https://bugs.archlinux.org/task/55841.

**Comment by scop** [comment]
What's your bash version? What happens if you just execute `words=()` in a shell?

**Comment by Dark-Feather** [comment]
Bash version is 4.4.12(1). words=() works just fine.

```

[ AniNIX::Core(ShadowArch) cxford Tue Oct 10 17:30:19 ~ ] 
|> bash --version
GNU bash, version 4.4.12(1)-release (x86_64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
[ AniNIX::Core(ShadowArch) cxford Tue Oct 10 17:30:20 ~ ] 
|> words=()
[ AniNIX::Core(ShadowArch) cxford Tue Oct 10 17:30:25 ~ ] 
|> echo $?
0
[ AniNIX::Core(ShadowArch) cxford Tue Oct 10 17:30:33 ~ ] 
|> words=(); echo $?
0

```

**Comment by scop** [comment]
Hm. I suggest starting to comment out things in your bashrc and profile to see if an offender can be found that way. See also Troubleshooting in README.md.
