### ISSUE TITLE
test: ls.exp; ERROR: can't read "full": no such variable

### ISSUE THREAD

**Issue by mgorny** [scop/bash-completion#169]
```
$ ./runCompletion ls.exp
WARNING: Couldn't find the global config file.
Test run by mgorny on Sun Oct 15 10:59:16 2017
Native configuration is x86_64-pc-linux-gnu

		=== completion tests ===

Schedule of variations:
    unix

Running target unix
Using /usr/share/dejagnu/baseboards/unix.exp as board description file for target.
Using /usr/share/dejagnu/config/unix.exp as generic interface file for target.
Using ./config/default.exp as tool-and-target-specific interface file.
Running ./completion/ls.exp ...
ERROR: tcl error sourcing ./completion/ls.exp.
ERROR: can't read "full": no such variable
    while executing
"assert_complete "~$full/" "ls ~$part" $test -nospace"
    (file "./lib/completions/ls.exp" line 25)
    invoked from within
"source $file"
    (procedure "assert_source_completions" line 7)
    invoked from within
"assert_source_completions ls"
    (file "./completion/ls.exp" line 1)
    invoked from within
"source ./completion/ls.exp"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 source ./completion/ls.exp"
    invoked from within
"catch "uplevel #0 source $test_file_name""

		=== completion Summary ===

# of expected passes		1
/home/mgorny/git/bash-completion/test, bash-4.4.12(1)-release
```

**Comment by mgorny** [comment]
`unit/_tilde.exp` fails with a similar error:

```
Running ./unit/_tilde.exp ...
ERROR: tcl error sourcing ./unit/_tilde.exp.
ERROR: can't read "full": no such variable
    while executing
"format {_tilde "~%s"; printf "%%s\n" "${COMPREPLY[@]}"} $full"
    (file "./unit/_tilde.exp" line 39)
    invoked from within
"source ./unit/_tilde.exp"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 source ./unit/_tilde.exp"
    invoked from within
"catch "uplevel #0 source $test_file_name""
```

**Comment by scop** [comment]
I suppose `find_unique_completion_pair` fails somehow, so I suggest starting debugging from there. What about `unit/find_unique_completion_pair.exp` and `unit/chown.exp`? If the former works, it might be more related to users/groups available on your system rather than `find_unique_completion_pair` itself.

**Comment by mgorny** [comment]
Only the two tests I've mentioned here fail on my system (`ls` and `_tilde`). All other tests pass.

**Comment by scop** [comment]
What does the chown.exp test output? It does some testing whether find_unique_completion_pair worked out for its required test data, and skips gracefully if it didn't. I suppose it should produce some output when it didn't.

**Comment by mgorny** [comment]
```
$ ./runCompletion chown.exp
WARNING: Couldn't find the global config file.
Test run by mgorny on Sun Oct 15 17:38:41 2017
Native configuration is x86_64-pc-linux-gnu

		=== completion tests ===

Schedule of variations:
    unix

Running target unix
Using /usr/share/dejagnu/baseboards/unix.exp as board description file for target.
Using /usr/share/dejagnu/config/unix.exp as generic interface file for target.
Using ./config/default.exp as tool-and-target-specific interface file.
Running ./completion/chown.exp ...

		=== completion Summary ===

# of expected passes		4
# of untested testcases		2
/home/mgorny/git/bash-completion/test, bash-4.4.12(1)-release
```

**Comment by mgorny** [comment]
dbg.log contains:
```
UNTESTED: Not running complex chown tests; no suitable test user found.
UNTESTED: Not running complex chown tests; no suitable test group found.
```

**Comment by scop** [comment]
Ok, so two issues to look into:
- Find out why that happens, make it not happen if possible
- If that happens, fix ls and _tilde tests to fail gracefully (status untested) instead of blowing up like that

**Comment by mgorny** [comment]
Yes, indeed. Do you need some more data? I can submit you list of users/groups on my system privately; I'd rather not put that data in public, though.

**Comment by scop** [comment]
Feel free to send it to me in private mail or some other way. But please be aware that I'm not sure when I'll have time to look into it. Chances are that you'd get to it quicker than I would...

**Comment by mgorny** [comment]
Sent. Don't worry, I'm not in a hurry. And my TODO is also huge ;-).

**Comment by mgorny** [comment]
So it seems that the issue is that `compgen -u` (`-p`) lists duplicate user entries. This is because `nsswitch.conf` lists both `compat` and `files` modules which both read the passwd file.

It's debatable whether doing this makes any sense but it's the default configuration on Gentoo right now and fixing that who would take a long time. Furthermore, there may be other valid cases for duplicate entries given the plethora of backends (NIS with backup?).

I don't think glibc should be taught to remove dupes, not sure about bash. Fixing either would take long, and the fix may be rejected, especially given that completion works with duplicate entries.

All that considered, I think the best solution would be to account for possible duplicates in the unique entry finding function.

**Comment by mgorny** [comment]
Thanks. I can confirm the issue with ls & co. has been fixed. There is a new issue with _tilde, but i'll file a separate bug for it.
