### ISSUE TITLE
Some bash completion are not sourced from /usr/share/bash-completion/completions/

### ISSUE THREAD

**Issue by siteshwar** [scop/bash-completion#174]
bash completions are not sourced from ```/usr/share/bash-completion/completions/``` directory when file  extension is not  ```.bash```. However they are sourced when put under ```/etc/bash_completion.d```.

[This](https://github.com/scop/bash-completion/blob/master/bash_completion#L2032) is the related code from bash_completion file.  Is there any specific reason that it requires file extension to be ```.bash``` ?

[clap-rs](https://github.com/kbknapp/clap-rs/search?utf8=%E2%9C%93&q=bash-completion&type=) project [generates completions](https://github.com/kbknapp/clap-rs/search?utf8=%E2%9C%93&q=bash-completion&type=) with ```bash-completion``` extension, so there are issues while packaging it's completions under ```/usr/share/bash-completion/completions/``` directory.

**Comment by siteshwar** [comment]
fwiw there a pull request to change it https://github.com/kbknapp/clap-rs/pull/1114 however I would still like to know why there is a restriction for filenames under ```/usr/share/bash-completion/completions/```.

**Comment by scop** [comment]
In addition to _command_.bash, the line you pointed to loads also _command_ and __command_ files from that dir, so it doesn't specifically require *.bash. And this is not about restricting loading files, but rather enablement -- when loading completions dynamically, we need to decide exactly what files we try to load, and that means in practice _something_ based on the command name being completed.

`/etc/bash_completion.d` is different, files in it are eagerly loaded at `bash_completion` load time, and we can load whatever we like from that dir; there's no context of what's being completed at that point (nothing is), so we just load everything there except usual backup files. That behavior is deprecated as it bloats the shell with potentially unused functions, and causes startup delays.
