### ISSUE TITLE
'*' should be expanded in tab completions

### ISSUE THREAD

**Issue by siteshwar** [scop/bash-completion#181]
With `bash-completion` scripts sourced `ls *<TAB>` yields no result, however it works when `bash-completion` is not used.

**Comment by Abominas** [comment]
If you haven't changed your readline keybinds, you can expand that by pressing `Ctrl-X *` after typing the '*'. For example in my ~/, 
`ls *`_Ctrl-X *_ -> `ls src doc res builds git ...`

**Comment by scop** [comment]
#42
