### ISSUE TITLE
Python Completion Syntax Error

### ISSUE THREAD

**Issue by JakeRunsDnD** [scop/bash-completion#188]
Just downloaded the script for python, saved it in my home directory, and sourced it in my 16.04 bash shell (terminator), and like 46 - the regex near the end - is throwing the following error:
```
bash: /home/jakerunsdnd/.pycomplete.bash: line 46: syntax error near unexpected token `('
bash: /home/jakerunsdnd/.pycomplete.bash: line 46: `        !(?(*/)python*([0-9.])|?(*/)pypy*([0-9.])|-?))'
```
I'll try to make a PR to fix it when I get the chance, but I don't know if/when I'll get that time

**Comment by bewuethr** [comment]
Have you sourced `bash_completion`? It provides functions required by `python` (such as `_init_completion`) and turns on the extended glob pattern shell option (`shopt -s extglob`), which I guess is missing in your case.

Also, the proper way to install completion is to drop the files into `/usr/share/bash-completion/completions` (enables dynamic loading) or `/etc/bash_completion.d` (for backwards compatibility). Both of these ways make sure `bash_completion` is sourced previously.

**Comment by JakeRunsDnD** [comment]
Ah, gotcha. The bittersweet pain of a pebkac error :) Thanks for running and maintaining this repo!

**Comment by bewuethr** [comment]
Just a fellow user :wink:
