### ISSUE TITLE
broken dynamic app-specific completions loading

### ISSUE THREAD

**Issue by sergeev917** [scop/bash-completion#192]
I describe the problem on bash for vim, but I believe the problem is not limited to vim.

First, I hit questionable autocompletion behaviour:
```
# mkdir /tmp/bashcomp-test; cd /tmp/bashcomp-test; touch foo bar ld.so.test.conf
# ls
bar              foo              ld.so.test.conf
# vim <Tab><Tab>
bar  foo
```

So, no ld.so.test.conf file in the vim autocompletion output. I checked the vim-specific autocompletion file: `/usr/share/bash-completion/completions/vim`. It uses `_filedir` function when not completing an option. But it works differently:

```
# unset COMPREPLY; cur="" _filedir ; echo "${COMPREPLY[@]}"
bar ld.so.test.conf foo
```

But then it seems that the vim-specific autocompletion is not actually used:
```
# complete | grep vim
complete -F _filedir_xspec rvim
complete -F _filedir_xspec gvim
complete -o filenames -F _vim vix
complete -o filenames -F _vim vim
complete -F _filedir_xspec rgvim
complete -o filenames -F _vim vi
```

The source for these generic rules is at `/usr/share/bash-completion/bash_completion`:
```
_install_xspec '*.@([ao]|so|so.!(conf|*/*)|[rs]pm|gif|jp?(e)g|mp3|mp?(e)g|avi|asf|ogg|class)' vi vim gvim 
rvim view rview rgvim rgview gview emacs xemacs sxemacs kate kwrite
```

But then after doing the following:
```
# complete -r vim
# complete | grep vim
complete -F _filedir_xspec rvim
complete -F _filedir_xspec gvim
complete -F _filedir_xspec rgvim
# vim <Tab> <Tab>
bar             foo              ld.so.test.conf
# complete | grep vim
complete -o filenames -F _vim rview
complete -o filenames -F _vim rvim
complete -F _filedir_xspec gvim
complete -o filenames -F _vim view
complete -o filenames -F _vim vim
complete -o filenames -F _vim ex
complete -F _filedir_xspec rgvim
complete -o filenames -F _vim vi
complete -o filenames -F _vim vimdiff
```

So what happens is that we have a generic completion via `_filedir_xspec`, which blocks `_vim()` from loading. But with `_filedir_xspec` manually removed, `_vim()` is loaded on the first use.
Thus, it looks like app-specific completion is not working as expected and might be blocked by default completion rules.

The original bug report is at: https://bugs.gentoo.org/649986 (bash-completion-2.7-r2).

**Comment by sergeev917** [comment]
Since the completion script for vim is not a part of this repository, I attach it below. It's normally installed at `/usr/share/bash-completion/completions/vim`.

```
# Author: Ciaran McCreesh <ciaranm@gentoo.org>
#
# completion for vim

_vim()
{
    local cur prev cmd args

    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}
    cmd=${COMP_WORDS[0]}

    if [[ "${prev}" == "--servername" ]] ; then
        local servers
        servers=$(gvim --serverlist )
        COMPREPLY=( $( compgen -W "${servers}" -- $cur ) )

    elif [[ "${prev}" == -[uUi] ]] ; then
        COMPREPLY=( $( compgen -W "NONE" ) \
                $( compgen -f -X "!*vim*" -- "$cur" ) )

    elif [[ "${cur}" == -* ]] ; then
        args='-t -q -c -S --cmd -A -b -C -d -D -e -E -f --nofork \
            -F -g -h -H -i -L -l -m -M -N -n -nb -o -R -r -s \
            -T -u -U -V -v -w -W -x -X -y -Y -Z --echo-wid \
            --help --literal --noplugin --version'
        COMPREPLY=( $( compgen -W "${args}" -- $cur ) )
    else
        _filedir
    fi
}

complete -o filenames -F _vim vim ex vi view rvim rview vimdiff

# vim: set ft=sh sw=4 et sts=4 :
```

**Comment by scop** [comment]
We don't have a very good way to override those `_filedir_xspec` completions at the moment. But it's not clear to me what you mean by "manually removing _filedir_xspec" -- the function should not be removed, but if you want to load the one installed in completions/, remove the _filedir_xspec association with vim, i.e. `complete -r vim`. After doing that the completions/vim one should load on demand.

Until we do have a better way for overriding those completions, gentoo should patch their `bash_completion` and remove the `_filedir_xspec` association with vim if they want users to get their `completions/vim` instead.

**Comment by mgorny** [comment]
Ok, I will do that. Thanks for looking into it.

**Comment by sergeev917** [comment]
> But it's not clear to me what you mean by "manually removing _filedir_xspec" -- the function should not be removed

Yes, the wording was imprecise. I meant removing the association and not the function itself, as in the last listing. Should this bug be kept open until there is a solution to override these default completions?

**Comment by scop** [comment]
There is now :)

**Comment by sergeev917** [comment]
> There is now :)

Amazing, thank you!
