### ISSUE TITLE
ssh completion: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by rodrigoaguilera** [scop/bash-completion#196]
When I try to source the ssh completion script I am getting an error

I tried with bash 4.4 and 4.3

What I tried:

`docker run --rm -it debian bash`
This gives me a clean bash environment
`curl -o ssh-completion https://raw.githubusercontent.com/scop/bash-completion/master/completions/ssh`
`source ssh-completion`

I get
```
bash: ssh-completion: line 440: syntax error near unexpected token `('
bash: ssh-completion: line 440: `        !(*:*)/*|[.~]*) ;; # looks like a path'
```

**Comment by scop** [comment]
1) Don't do that. The separate scripts are not intended to be used that way. Just use the complete bash-completion package.
2) If you insist, do it, but you'll need to set the `extglob` shell option. This will get you past that error, but you'll run into others. See 1).
