### ISSUE TITLE
cryptsetup: Add luksChangeKey

### ISSUE THREAD

**Issue by paulmenzel** [scop/bash-completion#197]
With bash-completion 2.7 (and from the changes in 2.8, that one too), the command *luksChangeKey* is not autocompleted.

**Comment by scop** [comment]
PR's welcome :)

**Comment by hugoziviani** [comment]
Hello Guys, I've got this one. I already have correct the line that allows complete for $cryptsetup luksChangeKey. How can I make the pull-request? And which branch?
