### ISSUE TITLE
Is there a way to selectively switch to default completions ?

### ISSUE THREAD

**Issue by siteshwar** [scop/bash-completion#201]
It is possible to workaround buggy completions by overriding them with your own completions, or disabling them altogether with `complete -r`. But is there a way to selectively disable such completions ? I want to selectively disable buggy completions provided by bash-completions and switch back to default completions provided by bash.

**Comment by scop** [comment]
Not entirely sure what you mean, but to use bash's default for let's say command `foo` instead of our dynamically loaded one, one can do something like this:
```shell
echo "complete -o default -o bashdefault foo" > ~/.local/share/bash-completion/completions/foo
```
Does this answer your question? (See also commit 22e9a020adf1ab73896411ca2f3712a445062727)

**Comment by scop** [comment]
I don't think we have a too good mechanism for that apart from obviously deleting the offending completion files, and this is not a FAQ, so I'll leave it for the time when/if such a mechanism exists.

**Comment by scop** [comment]
Ended up documenting use of compatdir for this purpose after all.
