### ISSUE TITLE
Completing "/ " gives _xspecs: bad array subscript

### ISSUE THREAD

**Issue by dm606** [scop/bash-completion#209]
Typing "/ " in bash without the quotes (slash, space) and pressing tab results in `bash: _xspecs: bad array subscript`.
The issue appears to be that on this line:
https://github.com/scop/bash-completion/blob/103db12fd29746ec88f69849842fa3d2f9d251d0/bash_completion#L2021
The command is expanded to the empty string. The check for the empty string occurs before the expansion.

**Comment by ira-bv** [comment]
I still get this in latest master on some completions (e.g. not for vim, cat or less, but yes for vi), could this be something that's mixing in from the system bash completions? (Debian 10/Buster)

**Comment by ira-bv** [comment]
ok, silly me. dug through the settings, somewhere in my bashrc I had an old setting `alias vi="vim -N"` for no good reason. removing it solved the issue.

**Comment by scop** [comment]
If an alias like that triggers the issue, it's a bug I'd like to see fixed. Please open a new issue with complete reproducer details, as I wasn't able to provoke this with the info here myself.

**Comment by ira-bv** [comment]
I think it's a combo of the alias and the bash-it function that auto-generates completions for aliases. I'll take the bug report there ;)
