### ISSUE TITLE
Getting "sed: 22: "    1,/^# * Make data b ...": RE error: empty (sub)expression" for gmake completion

### ISSUE THREAD

**Issue by 0mp** [scop/bash-completion#213]
I'm on FreeBSD and when I try to autocomplete:

```console
$ gmake
```

I get:

>  sed: 22: "    1,/^# * Make data b ...": RE error: empty (sub)expression

**Comment by scop** [comment]
it's quite possible that some things that work only with gnu sed have crept in. If you have gsed installed and do "alias sed=gsed" before invoking the completion, does that make a difference?

**Comment by scop** [comment]
In that case, please attach the makefiles in the dir where you attempted completion, and I can have a look and see if I can reproduce.

**Comment by bewuethr** [comment]
Don't aliases not work by default in non-interactive shells?

**Comment by scop** [comment]
Aliases do work within completion functions. However, in this case we're invoking sed as "command sed", which explicitly prevents this from happening. So I suppose the way to test with GNU sed would be to arrange it to be the "sed" found in $PATH.

**Comment by scop** [comment]
I now have a container with FreeBSD sed in it available for testing, and it caught a couple of BSD sed incompatibilities already. Unfortunately the make one was not one of them, so no immediate help there.

**Comment by 0mp** [comment]
I might try to debug it further soon as I'm working on a better Bash completion support for many FreeBSD programs.

Here's the repository: https://github.com/0mp/bash-completion-freebsd

**Comment by ScoobiFreeBSD** [comment]
The problem is line 43 of `/usr/local/share/bash-completion/completions/gmake`, where the repetition operator has a 0 in it (the value of `${dirname_len}`):

`      s|^\(.\{${dirname_len}\}\)\(.\{${#basename}\}[^:/]*/\{0,1\}\)[^:]*:.*$|${output}|p;
`

which evaluates to

`      s|^\(.\{0\}\)\(.\{0\}[^:/]*/\{0,1\}\)[^:]*:.*$|\1\2|p;
`

when pressing `<Tab>` on 'gmake ' with no arguments.  With a completion argument('`gmake foo<Tab>`'), the 2nd `\{\}' repetition operator is the length of `foo`, but the 1st is still 0.

No idea how to fix (yet)...

**Comment by scop** [comment]
Still pending more details, for example the Makefile(s) used to provoke the problem.

Meanwhile, I tested things like `echo foo | sed -e 's/^f\{0\}//'` with various sed implementations, including FreeBSD 10.0.0 and 11.1.0 seds rebuilt on Linux as well as FreeBSD 13-current sed on FreeBSD, Solaris, ssed, busybox sed but none of them showed any error messages or failed behavior.

**Comment by scop** [comment]
So in other words, I either misunderstand @ScoobiFreeBSD 's pinpointed recipe for the problem, or I'm unable to reproduce it.

**Comment by ScoobiFreeBSD** [comment]
Makefile:
`target1:
        echo "This is target 1."

target2: target1
        echo "This is target 2."`
uname -a:
`FreeBSD ajenkins-delllaptop 13.0-CURRENT FreeBSD 13.0-CURRENT #17 fa3e936dba5-c268465(master): Sat May  9 15:02:07 EDT 2020     root@ajenkins-delllaptop:/usr/obj/usr/src/amd64.amd64/sys/MYKERNEL  amd64`

Failing sed command:
`$ sed -ne 's|^\(.\{0\}\)\(.\{0\}[^:/]*/\{0,1\}\)[^:]*:.*$|foobar|p;'
sed: 1: "s|^\(.\{0\}\)\(.\{0\}[^ ...": RE error: empty (sub)expression`

This is about as small as I can get the regex and still have it fail:
`$ sed -ne 's|\(.\{0\}\)||p;'
sed: 1: "s|\(.\{0\}\)||p;
": RE error: empty (sub)expression`

**Comment by scop** [comment]
Ah, thanks. I believe https://github.com/scop/bash-completion/pull/419 could fix this, could someone give it a try and report back?

**Comment by scop** [comment]
By the way, the FreeBSD sed we compile and test with in a variant of the Ubuntu 14 container does not exhibit this behavior. Maybe it's a libc thing.

**Comment by ScoobiFreeBSD** [comment]
> By the way, the FreeBSD sed we compile and test with in a variant of the Ubuntu 14 container does not exhibit this behavior. Maybe it's a libc thing.

It's quite possible...I always run FreeBSD CURRENT, which is the bleeding-edge development version of FreeBSD.  grep(1) doesn't exhibit the problem on my machines using that regular expression, which is weird.

```
$ echo foo | grep '.\{0\}'
foo

$ echo foo | sed -ne 's|.\{0\}||'
sed: 1: "s|.\{0\}||
": RE error: empty (sub)expression

$ echo foo | gsed -ne 's|.\{0\}||'

$ ldd /usr/bin/grep
/usr/bin/grep:
        libgnuregex.so.5 => /usr/lib/libgnuregex.so.5 (0x80025b000)
        libbz2.so.4 => /usr/lib/libbz2.so.4 (0x800274000)
        libz.so.6 => /lib/libz.so.6 (0x80028a000)
        libc.so.7 => /lib/libc.so.7 (0x8002a6000)
$ ldd /usr/bin/sed
/usr/bin/sed:
        libc.so.7 => /lib/libc.so.7 (0x80024c000)
```
Oh, well looks like my `grep` is linked against the GNU regex library, which would explain it - that library doesn't mind that regex construct.

**Comment by scop** [comment]
Thanks for confirming. #419 is still there for someone to take a peek at :)
