### ISSUE TITLE
Bash Completion not working

### ISSUE THREAD

**Issue by Schwartz10** [scop/bash-completion#216]
Bash Completion is not working on my Mac running High Sierra version 10.13.3.

I've configured my `~/.bash_profile` to contain other logic that also parses the git branch to display it in the terminal:

```
if [ -f /etc/bash_completion ]; then
   . /etc/bash_completion
fi

# Git branch in prompt.

parse_git_branch() {
 git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1=" \W\[\033[94m\]\$(parse_git_branch)\[\033[00m\] $ "
```

I also have not pointed at `/sw/etc/bash_completion` because my `bashrc` lives in `/etc/`, there is no `/sw/etc`

When I run `set -v` I get:
`parse_git_branch`

When I run `set-x` I get:
```
parse_git_branch
++ parse_git_branch
++ git branch
++ sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
```

Thoughts?

**Comment by scop** [comment]
Not really, just some guesswork.

* Does removing the git branch stuff from $PS1 make it work?
* /etc/bash_completion smells like you're using an old version of bash-completion. Recent ones install to /usr/(local/)share/bash-completion by default (at least on Linux). Does /etc/bash_completion actually exist?
* Are you using the bash-completion package from homebrew? (If not, why not/have you tried with it?)

**Comment by Schwartz10** [comment]
> Does removing the git branch stuff from $PS1 make it work?

No, tried that and still didn't work.

> /etc/bash_completion smells like you're using an old version of bash-completion. Recent ones install to /usr/(local/)share/bash-completion by default (at least on Linux). Does /etc/bash_completion actually exist?

When I run, `brew info bash-completion`, I get:

```
bash-completion: stable 1.3 (bottled)
Programmable completion for Bash 3.2
https://bash-completion.alioth.debian.org/
Conflicts with:
  bash-completion@2 (because Differing version of same formula)
/usr/local/Cellar/bash-completion/1.3_3 (189 files, 608.2KB) *
  Poured from bottle on 2018-06-01 at 10:29:31
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/bash-completion.rb
==> Caveats
Add the following line to your ~/.bash_profile:
  [ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
```

so I changed my `.bash_profile` to reflect this information:

```
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

if [ -f /usr/local/etc/bash-completion ]; then
   . /usr/local/etc/bash-completion
fi
```

> Are you using the bash-completion package from homebrew? (If not, why not/have you tried with it?)

Yes, I'm using the bash-completion package from homebrew.

**Comment by scop** [comment]
Your bash-completion version is ancient, and no longer supported here. I can't help you with exact details with how to get a recent one from homebrew, but perhaps this will help: https://formulae.brew.sh/formula/bash-completion%402
