### ISSUE TITLE
bash completion for nvm?

### ISSUE THREAD

**Issue by JBallin** [scop/bash-completion#220]
I brew installed nvm and bash-completion@2 but nvm completions are not working without manually sourcing the completions installed by brew in `/usr/local/etc/bash_completion.d/nvm`.

I am sourcing bash-completions properly using `. /usr/local/share/bash-completion/bash_completion` which works for git.

**Comment by scop** [comment]
nvm completion is not shipped by us. I suggest finding out who ships it and asking to make sure that it is installed appropriately for your setup, and that completion autoloading is correctly otherwise set up.

**Comment by JBallin** [comment]
Sure. As stated, I have it set up. But other things seem to work out of the box with bash-completion such as git and docker, is there some way I can help get nvm supported too?

Also, where can I see all the available completions? The completions folder doesn't have anything called git or docker. Thanks!

**Comment by scop** [comment]
For set up details regarding the package you have installed, in case the bash-completion documentation is not enough (see e.g. README.md, and things in doc/), I would ask the package provider which in your case is brew maintainer or somesuch, perhaps a forum, dunno (I'm not familiar with brew).

/etc/bash_completion.d, /usr/local/etc/bash_completion.d /usr/share/bash-completion/completions, /usr/local/share/bash-completion/completions, ~/.local/share/bash-completion/completions are examples of dirs where completions may reside in, depending on setup. Note the difference in eager vs on demand loading behavior wrt the */completions and */bash_completion.d dirs, see docs on details.
