### ISSUE TITLE
sh: for i do...

### ISSUE THREAD

**Issue by jidanni** [scop/bash-completion#229]
This should expand into procmail

`$ for i do procm<TAB>`

Currently one needs a ";" to make it work:

`$ for i; do procm<TAB>`

**Comment by scop** [comment]
Without the semicolon, bash gives us `for` as the command to be completed, and with it, we are given `do`. I don't think we're going to try to complete things that can be done with `for`. Whereas with `do` it's quite straightforward, which is why it already works.

**Comment by jidanni** [comment]
All I know is I am not violating any specs, but you are not completing according to specs.

```
$ for i do<TAB>
Display all 185 possibilities? (y or n)
$ for i; do<TAB>
Display all 2294 possibilities? (y or n)
$ for i do;<TAB>
Display all 2169 possibilities? (y or n)
```
The first should get all the possibilities as the second,
and the third should beep as a syntax error.

$ apt-cache policy bash-completion
bash-completion:
  Installed: 1:2.8-6
