### ISSUE TITLE
bash-completion increasingly starts to get in my way

### ISSUE THREAD

**Issue by rico666** [scop/bash-completion#232]
The worsening(tm)

I download some movie and while it is downloading, I'd like to watch it.

    mplayer some_movie.mkv.cdrdownload

perfectly works, but impossible to get `mplayer some<TAB>` because this "intelligent" tool considers .cdrdownload to not be a file that could be of relevance to mplayer. causing me to run in circles before I can actually watch it (`touch some<TAB>`, then replace touch with mplayer, or ls dir, then copy and paste - SERIOUSLY - the *.cdrdownload file as argument to mplayer)

----

Let's say there are
    file.xyz
    file.abc
    file.uvw

in a directory. And I would like to create a folder "file" to be able to move all these files into it. Impossible with

    mkdir fi<TAB>

Why - I don't know. The workaround

    touch fi<TAB>

then going back and replacing touch with mkdir became unbearable.

----

As bash-completion seems to have it's fangs deep in system dependencies - trying to remove it from my openmediavault box would have resulted in:

    The following packages will be REMOVED:
    bash-completion omvextras-common openmediavault openmediavault-backup openmediavault-cups openmediavault-diskstats openmediavault-docker-gui openmediavault-downloader
    openmediavault-locate openmediavault-luksencryption openmediavault-lvm2 openmediavault-netatalk openmediavault-omvextrasorg openmediavault-route
    openmediavault-rsnapshot openmediavault-sabnzbd openmediavault-shellinabox openmediavault-usbbackup openmediavault-virtualbox

my best workaround so far is

    mv /usr/share/bash-completion/bash_completion /usr/share/bash-completion/bash_completion.disabled

Please - a little bit more common sense in future versions. Thank you.

**Comment by dpaleino** [comment]
Hello,

to complete arbitrary filenames, you could just use Alt+/.

As for having more common sense, please blame openmediavault's developers: bash-completion is a dependency of one of those packages, over which we have absolutely control.

To disable bash-completion, make sure to just avoid sourcing it in your .bashrc.

Kthxbye,
David

**Comment by rico666** [comment]
The "common sense" request was actually not related to openmediavault integration (I know that can always be made "fault" of the other party) but to semantics hacked into the behavior of this package.

When I have the choice to use simply `<TAB>` or a 3-key combo, I choose the less painful one.

Ok, thank you too for having thoroughly considered my feedback.

Bye

**Comment by dpaleino** [comment]
Please have a look: https://github.com/scop/bash-completion/blob/master/README.md#faq

It's our policy not to complete on any extension for all binaries -- since this is usually valid on *nix systems and would make extension-based completion completely moot. If one really wants to complete on any filename,  please do follow the shortcut described in the FAQ, in turn taken from the bash man page.

David

**Comment by scop** [comment]
Courtesy and being constructive usually yields better results. But consider yourself lucky this time :) mkdir stuff has been addressed in dbb38708e39bc8cb463ccaab294b5d1ae1e173f6 and b0babf873b21eb2f1d936e6e2288b451c1a58778, and crdownload now in 2837a48c7954116b4e6d4e1c911798b6e54f6c68
