### ISSUE TITLE
job completion not completing

### ISSUE THREAD

**Issue by mtklr** [scop/bash-completion#247]
With multiple jobs, `bg`, `fg`, `jobs`, `disown` won't complete past `"%` (bash 4.419(1), `bash --norc`).

In `bash_completion`, removing the prefix and suffix (`-P'"%'` and `-S'"'`) allows completion of the job names:

``` sh
# bg completes with stopped jobs
complete -A stopped bg

 # other job commands
complete -j jobs fg jobs disown
```

(Duplicate process names result in an `ambiguous job spec` error. I've tried writing a job number completion to avoid this, but it's not quite working right...)

Thanks.

**Comment by scop** [comment]
Looks good in principle, but this would break the case noted in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=347316:
```
$ ( sleep 100; )&
[1] 17411
$ disown <TAB>
# completes to "disown ( " which will give an error
```
...ditto:
```
$ ( sleep 100; )
^Z
[1]+  Stopped                 ( sleep 100 )
$ bg <TAB>
# completes to "bg ( " which will give an error
```
Ideas?

**Comment by mtklr** [comment]
Ah, I see. I'm afraid I can't see a way around it at the moment. Thanks for taking time to look at it.

**Comment by scop** [comment]
Neither did I in a quick look. But if we can't make both work, I think supporting the cases you noted broken would be more important. Anyway, I'll let this rest for a while and will take another stab later unless someone beats me to it.
