### ISSUE TITLE
systemctl php

### ISSUE THREAD

**Issue by Forkest** [scop/bash-completion#251]
`systemctl start php<TAB>` autocompletes `phpsessionclean.service`, but:

```
$ systemctl list-units | grep php
php7.2-fpm.service
phpsessionclean.timer
```

The first one suggestion is missing, and the second is really a timer, not a service.

bash-completion version 1:2.8-1ubuntu1, php-fpm package is installed.

**Comment by scop** [comment]
systemctl completion is not provided by us, but systemd IIRC.
