### ISSUE TITLE
not auto complete username while use command su 

### ISSUE THREAD

**Issue by Mrzyxing** [scop/bash-completion#253]
login as user 'someone' via ssh and switch to root,then use command su to switch other account but not work.
It worked at centos 6.4 with version 1.3,but centos 7.1 and 7.4 with version 2.1 not work.

use case as follow:
```
ssh as user someone
sudo -i
su [tab]
````

more detail info as follow:
```
[airtickets@VMS78519 ~]$ cat /etc/system-release
CentOS Linux release 7.1.1503 (Core)
[airtickets@VMS78519 ~]$ yum list installed  | grep -i completion
bash-completion.noarch           1:2.1-6.el7                           @anaconda
[airtickets@VMS78519 ~]$ cat /etc/passwd | grep airtickets
airtickets:x:1005:1005::/home/airtickets:/bin/bash

```

**Comment by scop** [comment]
The `su` completion included with CentOS 7 is not from us but from util-linux:

```
$ rpm -qf /usr/share/bash-completion/completions/su
util-linux-2.23.2-43.el7.x86_64
```

**Comment by Mrzyxing** [comment]
> The `su` completion included with CentOS 7 is not from us but from util-linux:
> 
> ```
> $ rpm -qf /usr/share/bash-completion/completions/su
> util-linux-2.23.2-43.el7.x86_64
> ```

Many thanks for reply.
I just edit this file,and problem solved!
Current default completion is list current directory files but list users is most useful completion,not sure my change isn't a better completion way for su.
change 42 line from
` COMPREPLY=( $(compgen -f -- $cur) )`
to
` COMPREPLY=( $(compgen -u -- $cur) )`
