### ISSUE TITLE
no email gateway for reporting issues 

### ISSUE THREAD

**Issue by ebblake** [scop/bash-completion#264]
I really detest logging into a web page to file an issue, and would much rather shoot off an email in my favorite editor.  https://fire.fundersclub.com/ claims that it is easy to add a bot collaborator to projects in order to enable such a mail gateway, although I personally have no experience on whether that actually works.

**Comment by Lekensteyn** [comment]
I almost thought that this was spam (for the linked URL), but it is not ;)

For many issue/bug trackers, some kind of login is required. I am not sure if adding an email gateway is worth the effort.

**Comment by scop** [comment]
I'm not at all sure either, but the setup was simple enough, so enabled to try it out. Will remove it if it starts to require more work than this or cause any problems.
