### ISSUE TITLE
Using `alias ip='ip -color'` breaks interfaces completion

### ISSUE THREAD

**Issue by vgaetera** [scop/bash-completion#268]
Using `alias ip='ip -color'` breaks interfaces completion:
```
# alias ip='ip -color'

# firewall-cmd --add-interface=^[[36m
^[[36menp3s0  ^[[36mlo      ^[[36mtun0    ^[[36mwlp2s0 

# rpm -q bash-completion 
bash-completion-2.8-3.fc29.noarch
```

**Comment by scop** [comment]
I'm afraid this is a "don't do that, then" case. We generally don't want to disable aliases because setups may have valid reasons for defining them. One ugly way to get this working with both worlds could be to use something like this instead of an alias:
```bash
ip() { [[ "$COMP_LINE" ]] && /bin/ip "$@" || /bin/ip -color "$@"; }
```

**Comment by vgaetera** [comment]
Optimized solution for iproute-4.20.0+:
```
alias ip='ip -color=auto'
```
