### ISSUE TITLE
could bash-completion for youtube-dl be improved ?

### ISSUE THREAD

**Issue by shirishag75** [scop/bash-completion#271]
currently when I use bash-completion for youtube-dl it gives me 

`$ youtube-dl --`

what it needs to also give or do an option is do 

`$ youtube-dl -`

or better yet - 

`$ youtube-dl -F`

which is the most common switch used.

**Comment by scop** [comment]
youtube-dl completion is not shipped by us, so changes to it need to be made somewhere else. But FWIW in general, offering long options as completions is preferable over short ones, we have a chapter about that in CONTRIBUTING.md.
