### ISSUE TITLE
macOS `-bash: have: command not found`

### ISSUE THREAD

**Issue by gbateman** [scop/bash-completion#273]
Just installed bash completion with `brew install bash-completion` on bash version 3.2 using `brew install bash-completion`. Added the line `[ -d /usr/local/etc/bash_completion.d ] && . /usr/local/etc/bash_completion.d/*` to ~/.bash_profile and restarted iterm.

Every time I load a session or source ~/.bash_profile, I get the error `-bash: have: command not found`, and bash-completion is not working. 

I heard that the bash_completion script itself defines `have`, but looking through the script it seems to also unset have.

Is there something obviously wrong with what I'm doing or is this an issue?

**Comment by scop** [comment]
At least the version you get for bash 3.2 with the name bash-completion from brew is so old that it is no longer supported here. I suggest checking out https://formulae.brew.sh/formula/bash-completion%402 for an up to date one, or contacting the brew maintainers for support for the old version.
