### ISSUE TITLE
Error on sourcing: "declare: -A: invalid option" on bash 5.0.0

### ISSUE THREAD

**Issue by sathishvj** [scop/bash-completion#275]
Error on sourcing from .profile:
`-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]`

Bash version is latest: 5.0.0
`bash --version
GNU bash, version 5.0.0(1)-release (x86_64-apple-darwin17.7.0)
`

**Comment by scop** [comment]
Sounds very weird. Actually, sounds like errors one would receive if trying to use current bash-completion with bash 3.x. I'm having a hard time believing that they would have removed essential features such as complete -D and declare -A -- are you **sure** those errors are from 5.0.0, and not 3.x?

**Comment by sathishvj** [comment]
I'm on a mac and I had updated to bash v5.0.0.  I thought the issue might be resolved if I did a `#!/usr/bin/env bash` at the top.  But that also didn't.  

Here is the result of running both together.  Does it give you any clues that I can try out?

$ `bash --version && source ~/.profile
GNU bash, version 5.0.0(1)-release (x86_64-apple-darwin17.7.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]
`

**Comment by scop** [comment]
Invoking `bash --version` does not give you the version of the running shell. Try for example `echo $BASH_VERSION` for that.

**Comment by sathishvj** [comment]
ugh.  I'm so sorry for wasting your time.  I looked it up and I fixed it.  
meanwhile, thank your for your work.

For others: I also had to update the preferences in my mac terminal and iterm2 profiles to use the new version of bash.
