### ISSUE TITLE
Homebrew completion scripts not sourced anymore

### ISSUE THREAD

**Issue by weibeld** [scop/bash-completion#277]
Installed with `brew install bash-completion@2` on macOS 10.14.2 (Mojave) with Bash 5.0. Now the proposed code to add to `.bash_profile` or `.bashrc` in the "Caveat" is:

~~~bash
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
~~~

When I installed it 10 days ago, it was:

~~~bash
if [ -f /usr/local/share/bash-completion/bash_completion ]; then
  . /usr/local/share/bash-completion/bash_completion
fi
~~~

Both result in the same, namely in the sourcing of `/usr/local/share/bash-completion/bash_completion`, so this shouldn't matter.

But now the problem is that the completion scripts of other Homebrew formulas, which are in `/usr/local/etc/bash_completion.d`, are not sourced anymore by the `bash_completion` script. When I installed it 10 days ago, this was still the case and the completions worked, but now they don't. So, something must have changed.

**Comment by scop** [comment]
This seems related to the homebrew packaging. That's not something we're involved with here, I suggest contacting the homebrew maintainers.

**Comment by weibeld** [comment]
This has been discussed [here](https://github.com/Homebrew/homebrew-core/issues/36377) and the fact that scripts in `/usr/local/etc/bash_completion.d` are not sourced automatically is a design decision of the `bash-completion@2` formula.
