### ISSUE TITLE
any completion macro for clear current entry line?

### ISSUE THREAD

**Issue by abdulbadii** [scop/bash-completion#285]
How is there any completion macro for clear current entry line? ..there's such one in windows by ESC key
and how to make 'overloaded' key for 2 or more completion macros

**Comment by scop** [comment]
Not sure if/how this is related to bash-completion, seems like a generic bash question to me? Anyway, some ideas you may try experimenting with: Ctrl+W (remove previous word) and Ctrl+A Ctrl+K (jump to beginning of line, delete line).
