### ISSUE TITLE
Filename after >& is not completed

### ISSUE THREAD

**Issue by greymd** [scop/bash-completion#296]
```
$ touch test.log
$ echo test >& test.<tab>
```
=> Does not work

However, `&>` works even `>&` is equivalent to it.

```
$ touch test.log
$ echo test &> test.<tab>
```

It's going to be

```
$ echo test &> test.log
```

**Comment by scop** [comment]
It seems our completion code is not invoked at all after `>&` and bash itself without bash-completion exhibits the same behavio, so I don't think there's anything we can do about this for now. I suggest reporting it to bash upstream.
