### ISSUE TITLE
Completion script slowing down tmux startup

### ISSUE THREAD

**Issue by mrzool** [scop/bash-completion#30]
Every time I start tmux or open a new split/window there is a delay of about 7 seconds before the prompt appears. I'm pretty sure this is not about tmux misconfiguration, I've made a test with a blank `.tmux-conf` and the delay persists. On the other hand, commenting out the bit where I load bash-completion in my `bashrc` puts things back to normal.

This is not happening outside tmux.

Running Bash 4.3 and tmux 2.1 on OS X. Any help pointing me in the right direction would be much appreciated.

**Comment by scop** [comment]
This is the first time I've heard of tmux, so I don't have anything at the moment except to point you at the  troubleshooting section of our README.md, see https://github.com/scop/bash-completion#troubleshooting

**Comment by mrzool** [comment]
Sourcing bash-completion after setting `set -x` gave me a 3500+ lines of log.

[This](https://gist.github.com/mrzool/f9ad70fdf4122a6986e2f2ff7e3c08fc) is the log I got while inside tmux, and [this](https://gist.github.com/mrzool/72f0e17ad5f098b65dbafc5e7c51e016) while outside.

**Comment by scop** [comment]
So the only differences are with `PATH`? The latter has some duplicates so maybe there's some kind of recursive initialization going on. How do you load bash-completion from bashrc? If the delay is because of an initialization loop and you cannot get rid of it, loading it like this should prevent it being sourced multiple times in a single shell:
```shell
[[ $BASH_COMPLETION ]] || . /path/to/bash_completion
```

**Comment by mrzool** [comment]
Looks that way... I load bash-completion as recommended by the caveats in the homebrew formula:

```bash
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi
```

Sadly the change you suggested has no effect whatsoever.

**Comment by scop** [comment]
Hm, `/etc/bash_completion` is not the location we install the main script these days. What version of bash-completion are you using?

**Comment by mrzool** [comment]
Ok, you definitely got something there.

Homebrew installs bash-completion 1.3 by default [for compatibility reasons](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bash-completion.rb#L1)—bash-completion 2.x requires Bash 4.x while OS X still ships with Bash 3.

I was able to install an up-to-date bash-completion with homebrew with these commands:

```bash
brew tap homebrew/versions
brew install bash-completion2
```

And by updating the path in my `bashrc`.

All this effectively fixed my delay issue with tmux.

Thanks a lot for the help!
