### ISSUE TITLE
completions/gdb: pattern for corefiles

### ISSUE THREAD

**Issue by dilyanpalauzov** [scop/bash-completion#300]
Systemd creates forefiles of the form `core.weston.1000.bc46148827504908898ad152f43bffb2.5308.1555362132000000.lz4`, which unpacked look as `core.weston.1000.bc46148827504908898ad152f43bffb2.5308.1555362132000000`.  `gdb prog <TAB>` does not recognize the pattern of the corefile name and therefore does not complete.  Proposal:
```diff
diff --git a/completions/gdb b/completions/gdb
--- a/completions/gdb
+++ b/completions/gdb
@@ -37,7 +37,7 @@ _gdb()
         COMPREPLY=( $( compgen -W "$( command ps axo comm,pid | \
             awk '{if ($1 ~ /^'"${prev##*/}"'/) print $2}' )" -- "$cur" ) )
         compopt -o filenames
-        COMPREPLY+=( $( compgen -f -X '!?(*/)core?(.+([0-9]))' -o plusdirs \
+        COMPREPLY+=( $( compgen -f -X '!?(*/)core?(.*+([0-9]))' -o plusdirs \
             -- "$cur" ) )
     fi
 } &&
```

**Comment by scop** [comment]
Thanks, made it a even bit more liberal than that.
