### ISSUE TITLE
MIssing "# ex: filetype=sh"

### ISSUE THREAD

**Issue by dilyanpalauzov** [scop/bash-completion#302]
… in the completions `getconf`, `nproc`, `perltidy`, `pv`, `tox`, `xdg-mime` and `xdg-settings`.

**Comment by scop** [comment]
Good catch, added. Out of interest, how did you spot this? Are you using an editor that is affected by the lack of it? I tested vim and nano, and neither seemed to care, perhapse they understand the `-*- shell-script -*-`.

**Comment by dilyanpalauzov** [comment]
I catched this with grep, after looking what is in common between all completion scripts.
