### ISSUE TITLE
Alpine Linux: Tests failing on latest release (v2.9)

### ISSUE THREAD

**Issue by oxr463** [scop/bash-completion#312]
I'm the maintainer of bash-completion for Alpine Linux,
and I have a few tests that are failing on the latest release:

- arping - using version from iputils.
- getconf - using version from musl libc.
- iconv - same as above.
- ifup/ifdown - using only version (as far as I know), from debian.

NOTE: I'm developing in an LXC container, so I'm assuming that's why ifup/ifdown are failing, the log mentions something about failing to run due to being in a Docker container.

See: https://gitlab.com/oxr463/aports/issues/31

[log.txt](https://github.com/scop/bash-completion/files/3129713/log.txt)

**Comment by scop** [comment]
I believe container stuff (thus arping and ifup/ifdown) and getconf are now taken care of in master per the above two commits, but I'm not sure what to do about iconv. It doesn't seem to recognize any options whatsoever, just responds with "unrecognized option" with all `-*` I've tried.

**Comment by oxr463** [comment]
I did some further digging, and apparently, there are functional differences between glibc and musl versions of iconv, (See: https://wiki.musl-libc.org/functional-differences-from-glibc.html#iconv).

Is there a way to force-skip a test?

**Comment by scop** [comment]
Sure, there may be that kind of functional differences but that doesn't mean it'd have to affect bash-completion in any way. Adding a skip for option completion because the musl one doesn't output an usage message we could use to parse options from: https://git.alpinelinux.org/aports/tree/main/musl/iconv.c

**Comment by oxr463** [comment]
Oh that's true. Sounds good to me!

**Comment by scop** [comment]
Pretty much all of this should be taken care of in master, apart from killall/pidof failures which are tracked in #318.

**Comment by oxr463** [comment]
Thanks!

**Comment by nh2** [comment]
Could you make a release? NixOS with musl also suffers from this.
