### ISSUE TITLE
Tests clutter user's bash history

### ISSUE THREAD

**Issue by mgorny** [scop/bash-completion#321]
After running `make check`, some of the test commands end up in my `~/.bash_history` which clutters history completion. I think this could be solved via setting `HISTFILE=/dev/null` early on.

**Comment by scop** [comment]
I vaguely remember that others preferred that a long time ago. But I've always found it very annoying, just haven't got around to it especially now that probably most of my tests are run in dedicated containers. But a clean fix would be very welcome nevertheless.
