### ISSUE TITLE
Use badge from Repology

### ISSUE THREAD

**Issue by FranklinYu** [scop/bash-completion#327]
For example:

Alpine Linux
![Alpine Linux](https://repology.org/badge/version-for-repo/alpine_edge/bash-completion.svg)

FreeBSD
![FreeBSD](https://repology.org/badge/version-for-repo/freebsd/bash-completion.svg)

Similar badges are available for Cygwin, Gentoo, Magela, OpenMandriva, openSUSE, Sisyphus, and Slackware.

**Comment by scop** [comment]
Oh, I was unaware of repology, thanks for bringing it to my attention. My initial impression is that I should drop the badges altogether, and simply link to https://repology.org/project/bash-completion/versions or https://repology.org/project/bash-completion/packages instead.
