### ISSUE TITLE
xdg-open alias causes "command not found"

### ISSUE THREAD

**Issue by rcorre** [scop/bash-completion#341]
In my `~/.bashrc`, I have:

```
alias op="xdg-open"
alias vim=nvim
```

If I type `op /tm<TAB>`, I get in `op /tmbash: op: command not found`. However, typing out `xdg-open` works as expected, as do other aliases like `vim` above.

**Comment by scop** [comment]
That's because we have a completion for another `op` command, and try to parse its output. Error message avoided now in master branch, but the completion will not produce meaningful results for xdg-open (or it it does, that's just lucky).

**Comment by rcorre** [comment]
Thanks! I no longer get the output, but I don't get completion either. I ended up just removing `completions/op` so I can get filename completion, which is all I really wanted for `xdg-open`. Is there a better way to do this?

I guess I could, of course, change my alias and my muscle-memory.

**Comment by scop** [comment]
A better way would be to not remove `completions/op`, but preemptively install your completion function for `op` so the dynamic load doesn't kick in. One (untested, off the cuff) way to accomplish that (and while at it, use it for xdg-open, and use the `_longopt` completion which would provide a bit of `--<tab>` completions) would be to add this to your `~/.bash_completion`:

```
complete -F _longopt op xdg-open
```

This should kick in in new shells.

**Comment by rcorre** [comment]
That did exactly what I wanted, thank you!
