### ISSUE TITLE
bash-completion breaks with for loop in a command substitution

### ISSUE THREAD

**Issue by FremdSprach** [scop/bash-completion#348]
Press [**TAB**] after this bash line:

-------------
for line in $(cat dem
-------------

And we get warnings saying error encountered:

-------------
for line in $(cat dembash: unexpected EOF while looking for matching `)'
bash: syntax error: unexpected end of file
-------------

This problem lives with bash-completion from very early versions, dating back to 1.x, which indicates some wrong disposal when dealing with command substitutions.

**Comment by scop** [comment]
I think the error message has been fixed already a while back. If you can reproduce with 2.9, ping back with details (see troubleshooting in README.md) and I'll reopen.

Completion within `$(...)` doesn't still work though, that's a known issue, #151
