### ISSUE TITLE
BUG: vars in pathname are quoted -- not expanded

### ISSUE THREAD

**Issue by Astara** [scop/bash-completion#361]
COMMAND /proc/$$/<complete_ch>
results in:
COMMAND /proc/\$\$/ FILELIST 
which never matches.  Ex:
cat /proc/$$/<complete_ch>
results in
cat /proc/\$\$/stat (type in stat from the FILELIST)
cat: '/proc/$$/stat': No such file or directory

dollar signs in command line should not be quoted or they won't expand.  

Only time you don't want to expand is if dollar sign has BS ('\') before it.

Version 2.5

**Comment by scop** [comment]
Yes, we have some issues with completing paths with variables, see #290.

(Aside, 2.5 is pretty old, you may want to consider upgrading.)
