### ISSUE TITLE
complete -D -F _completion_loader = "-bash: complete: -D: invalid option"

### ISSUE THREAD

**Issue by wildone** [scop/bash-completion#362]
OS: MAC
Version: 10.14.5
Bash: GNU bash, version 5.0.7(1)-release (x86_64-apple-darwin18.5.0)

Line: `complete -D -F _completion_loader`
Error: `-bash: complete: -D: invalid option`

Possible solution: `complete -F _completion_loader ""`

**Comment by scop** [comment]
Same as #363.
