### ISSUE TITLE
declare -A _xspecs = -bash: declare: -A: invalid option

### ISSUE THREAD

**Issue by wildone** [scop/bash-completion#363]
OS: MAC
Version: 10.14.5
Bash: GNU bash, version 5.0.7(1)-release (x86_64-apple-darwin18.5.0)

Line: `declare -A _xspecs`
Error: `-bash: declare: -A: invalid option`

Posible solution: `declare -a _xspecs`

**Comment by scop** [comment]
That's pretty much certainly not bash 5.x, but 3.x which doesn't support `-A`. A quick and dirty way to verify would be to place e.g. `echo $BASH_VERSION` above the mentioned line and do the same you did to trigger the above error message. If you can verify that this happens with 5.x, ping back and I'll reopen.
