### ISSUE TITLE
Timeline for the new release?

### ISSUE THREAD

**Issue by chenrui333** [scop/bash-completion#367]
It has been eight months since last release, and the homebrew user community does need a patch release for the latest upgrade (v2.9 has some build issue due to [this](https://github.com/scop/bash-completion/issues/331) and related [homebrew-core PR](https://github.com/Homebrew/homebrew-core/pull/41552)).

cc @yumitsu @maxim-belkin @scop

**Comment by scop** [comment]
I'll probably roll one soon, but frankly I find it really strange that the homebrew maintainers don't just apply a (supposedly) oneliner fix to deal with the issue in 2.9 locally in their package.

**Comment by maxim-belkin** [comment]
I struggled with this question too... until I realized that Homebrew is a nothing more than a redistributor of packages, not a pit stop where packages should be fixed. Homebrew encourages maintainers and contributors to submit patches upstream if/when possible.

Anyway, thanks for planning a new release!

**Comment by scop** [comment]
Submitting upstream is great, but not applying fixes that are available and just waiting for new releases that contain them may mean that users have to wait quite unnecessarily, perhaps even indefinitely should new issues arise in following releases.

**Comment by chenrui333** [comment]
I think I can take an action on this while we waiting for the new release. I am pretty open to do the patch (with knowing there would be some new release to fix in the future).

**Comment by maxim-belkin** [comment]
> perhaps even indefinitely

I'm pretty sure Homebrew would drop such a package from its main homebrew-core repo.

**Comment by scop** [comment]
@chenrui333 nah, I think I'll roll out 2.10 about right now.

**Comment by chenrui333** [comment]
Cool, I just created a new PR. Thanks for rolling out the new release.
https://github.com/Homebrew/homebrew-core/pull/47527
