### ISSUE TITLE
Adding \ to a command to bypass alias use wrong completion

### ISSUE THREAD

**Issue by rockandska** [scop/bash-completion#368]
Hello,

I just discovered that using \ to bypass an alias cause bash-completion to use the wrong complete function.

For example :
```
$ cd <TAB>
$ complete | grep 'cd$'
complete -o nospace -F _cd cd
$ \cd <TAB>
$ complete | grep 'cd$'
complete -F _minimal \cd
complete -o nospace -F _cd cd
```

Anyway to fix it and considering \command equivalent to command ?

Regards,

**Comment by scop** [comment]
Don't know if there's any other way besides taking it into account in our completion loader, and changing every single completion file to install completions also for the backslash-prefixed command names.

**Comment by rockandska** [comment]
Or it could be handle at the _completion_loader() level by :
- detecting if cmd start with a "\"
- remove the "\" from cmd and let the original completion loading happen
- retrieve the complete function used for the cmd (without the "\")
- duplicate the complete function with "\"

This way, it will only duplicate when needed and do not require to add this to all already known completion files

Could try to propose an implementation for this in a PR someday if you want.

Regards,

**Comment by scop** [comment]
Right, that could work too, and PR's definitely welcome.
