### ISSUE TITLE
Add copletion for launchctl

### ISSUE THREAD

**Issue by Daywalker01** [scop/bash-completion#37]
Please add the completion from
https://github.com/bobthecow/launchctl-completion/blob/master/launchctl-completion.bash
A lot of homebrew users would be very thankfull

**Comment by scop** [comment]
I may consider it if the author of the completion asks for it and signs up for maintaining it in bash-completion, there are no project members to my knowledge who are working on or testing stuff on OS X. But I suppose an at least good alternative to including that in the bash-completion project would be to just include the launchctl completion in homebrew's bash-completion package.
