### ISSUE TITLE
bash-completion@2 2.10 upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [scop/bash-completion#374]
Bug report, https://github.com/Homebrew/homebrew-core/pull/47527#issuecomment-563289732 (the upgrade bump relates to #367)

cc @xeron @scop

**Comment by chenrui333** [comment]
relates to #367

**Comment by xeron** [comment]
Not sure it's `bash-completion` issue.

1st thing we need to fix is to make `BASH_COMPLETION_COMPAT_DIR` note in `bash-completion@2` formula to use `brew --prefix` (or `etc` I guess similar to `"#{etc}/profile.d/bash_completion.sh"`).

The only question which is not brew related is to why `BASH_COMPLETION_COMPAT_DIR` wasn't required with 2.8 and it's required with 2.10.

**Comment by bradleyfrank** [comment]
So in `/usr/local/Cellar/bash-completion@2/2.10/share/bash-completion/bash_completion` I see this line (2143):
`compat_dir=${BASH_COMPLETION_COMPAT_DIR:-/usr/local/Cellar/bash-completion@2/2.10/etc/bash_completion.d}`

But that directory doesn't exit, it's `/usr/local/Cellar/bash-completion@2/2.10/etc/profile.d` instead.

**Comment by chenrui333** [comment]
Where can I see the changelog related to `BASH_COMPLETION_COMPAT_DIR`?

**Comment by yumitsu** [comment]
@chenrui333 This is unrelated to `bash-completion`, as it's just a hardcoded caveat in formulae code.

**Comment by chenrui333** [comment]
Should be by now :)
