### ISSUE TITLE
_xspecs: bad array subscript on alias completion

### ISSUE THREAD

**Issue by okomestudio** [scop/bash-completion#388]
I'm using Bash-it (https://github.com/Bash-it/bash-it) along with bash-complete on Debian Buster, and I get an `_xspecs: bad array subscript` error whenever I use an alias that uses `_filedir_xspec`. The original ticket was filed in Bash-it: https://github.com/Bash-it/bash-it/issues/1497

There is an alias
```
$ alias en
alias en='emacs -nw'
$ complete -p en
complete -F _alias_completion::en en
```

The `_alias_completion::en en` is a dynamically generated function by Bash-it (except the `echo` line, which I added only for debugging purpose and does not affect the bug):

```
$ type -a _alias_completion\:\:en
_alias_completion::en is a function
_alias_completion::en () 
{ 
    (( COMP_CWORD += 1 ));
    COMP_WORDS=(emacs -nw ${COMP_WORDS[@]:1});
    (( COMP_POINT -= ${#COMP_LINE} ));
    COMP_LINE=${COMP_LINE/en/emacs -nw};
    (( COMP_POINT += ${#COMP_LINE} ));
    echo [${COMP_LINE}][${COMP_CWORD}][${COMP_POINT}][${COMP_TYPE}][${COMP_KEY}][${COMP_WORDS[@]}] 1>&2;
    _filedir_xspec
}
```

When I use `TAB` after typing `som` to open the file named `somefile`, I get this:

```
$ en som[emacs -nw som][2][13][9][9][emacs -nw som]
bash: _xspecs: bad array subscript
efile
```

Note that the completion actually seems to be working (see `efile` following the error message), but it outputs `bash: _xspecs: bad array subscript` upon hitting `TAB`. The parameters that I echo in square brackets seem to make sense to me (though I am not actually familiar with `COMP_*` variables). 

I am wondering if this is a bug in bash-completion.

**Comment by scop** [comment]
The bare argumentless call to `_filedir_xspec` looks susceptible, that function is intended to be called as a completion one so at the very least, the first argument passed to it should be the command being invoked. No idea whether the error is because of this, though, but it could be, because that ends up being as the _xspecs subscript/key.

See Troubleshooting in README.md for further debugging tips, `set -x` in particular.

**Comment by okomestudio** [comment]
Thank you for the response. I have looked at the source code and it looks like the issue is indeed the missing (required) argument to `_filedir_xspec`. I've filed a patch at Bash-it to hopefully fix the issue on their side (not entirely sure this is the only issue, since I'm not thoroughly familiar with both the code bases). I'll report back.

**Comment by okomestudio** [comment]
We have patched Bash-it to fix the issue, so this ticket is irrelevant now. Thank you very much for the tip about the argument(s) to `_filedir_xspec`, which helped me identify the problem!

**Comment by scop** [comment]
Glad to hear. Posted a quick note at https://github.com/Bash-it/bash-it/commit/9e92ef342f9673559e78220b14cd535aa631f4c7#r37469859
