### ISSUE TITLE
openssl ca expect -selfsign but -selfsig

### ISSUE THREAD

**Issue by inpool** [scop/bash-completion#402]
System: Debian testing(bullseye)
Bash version: GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
Bash-completion version: 1:2.10-1

When I typed:
```
openssl ca -self<TAB>
```
I expect it auto completion as 
```
openssl ca -selfsign
```
but it do as 
```
openssl -ca -selfsig
```
then openssl report me a error message.

**Comment by scop** [comment]
Thanks for the report, this was already fixed as part of 9e03fc5ca07ecc7cbb863b2affdd06f8bbf8b415 where we switched to parsing args instead of hardcoding them.
