### ISSUE TITLE
make completion does not work any longer on other make variants

### ISSUE THREAD

**Issue by kforner** [scop/bash-completion#405]
I'm assuming that the ubuntu bash completion package is related to this repository. 
I used to inherit make completions for some alias of mine called qbmake:

```
complete -F _make qbmake
```
This worked well on ubuntu 16.04 but does not work on ubuntu 19.10 (bash-completion                        1:2.9-1ubuntu1). Now it hangs after typing TAB and I have to type CTRL+C to recover control.

I also noticed that the other variants listed in the last line of `/usr/share/bash-completion/completions/make`:
```
complete -F _make make gmake gnumake pmake colormake
```

do not work either. I installed colormake and setup a gmake make alias, and they do not complete. 
Any idea of what's going on ? 

Thanks

**Comment by scop** [comment]
The completion included here is for GNU make as the comment at the top says. However, some limited functionality is available for other make variants as well. I just verified that at least option completions (`bmake -`<kbd>Tab</kbd>) work for me on Ubuntu 18.04 and bmake, and while target completion doesn't, it doesn't require Ctrl+C to recover.

I'm nowhere near a make expert so chances are that I won't be able to help out much, but more details are needed, see Troubleshooting in README.md.

(bmake alias support added in 6b42551fa0166508b1ef6c28751ccdf5c7c49f32)

**Comment by kforner** [comment]
Here my other command (`qbmake`) uses the same Makefile that make does. Actually it just runs `make` in a different environment.

Using `set -x`, I logged the 2 commands: `make` and  `qbmake` on the same Makefile:
[qbmake.log](https://github.com/scop/bash-completion/files/4540747/make.log)
[make.log](https://github.com/scop/bash-completion/files/4540748/qbmake.log)

The output is quite a big but there are just a few diffs between the two.
One thing I noticed though is this diff:

```
++ make -npq __BASH_MAKE_COMPLETION__=1 -C . .DEFAULT
versus
++ qbmake -npq __BASH_MAKE_COMPLETION__=1 -C . .DEFAULT
```

I'm not sure to understand exactly what it does but it seems to run the command with different arguments. If TRUE, that could explain the problem since my command can not be run with these arguments. 
In this case how could I use the exact same completion for `make` for my custom `qbmake` ? 
I mean ideally:
- qbmake
- TAB
- get/copy the completions as if `make` were types instead of `qbmake`
-  paste those completions/

**Comment by scop** [comment]
I guess one somewhat ugly/duplicative way would be to
- take a copy of the `_make` function into a separate file named `qbmake` in your bash completion completions dir
- rename the function to `_gbmake`
- change [this line](https://github.com/scop/bash-completion/blob/6b42551/completions/make#L156) to invoke `make -npq ...` instead of `$1 -npq ...`
- change [this line](https://github.com/scop/bash-completion/blob/6b42551/completions/make#L154) to invoke `_xfunc make _make_target_extract_script ...` instead of `_make_target_extract_script ...`
- change [this line](https://github.com/scop/bash-completion/blob/6b42551/completions/make#L168) to read `complete -F _qbmake qbmake`

**Comment by scop** [comment]
...but a cleaner approach would be to make your program do the same thing as make does with those arguments, then you'd just `complete -F _make qbmake`

**Comment by kforner** [comment]
Thanks for your suggestions. 
The cleaner approach is not really applicable since my make actually runs the actual make but in a docker container. So running all this just to get some completions seem rather brutal.
I'll think about it...
Thanks again.
