### ISSUE TITLE
FAQ clarification

### ISSUE THREAD

**Issue by lifeBalance** [scop/bash-completion#408]
According to the FAQ, users should put their local completions in:
``~/.local/share/bash-completion/completions``

> to have them loaded **on demand**. 

What does that mean? That if I want to use them I have to **source** each file in my shell configuration?

**Comment by scop** [comment]
No, on demand loading means... loading on demand :) Just hit <kbd>Tab</kbd> after a command, its completion will be sourced and used automatically if there is one (there are a few rules on the file's naming, but in general the completion name should match the command's basename).

**Comment by lifeBalance** [comment]
> No, on demand loading means... loading on demand :)
Oh, so it's self-evident, right?
Anyways thanks for the explanatory explanation and for the pedant tautology too ;-)

**Comment by nngo** [comment]
> No, on demand loading means... loading on demand :) Just hit Tab after a command, its completion will be sourced and used automatically if there is one (there are a few rules on the file's naming, but in general the completion name should match the command's basename).

@scop What are the file naming rules? I have a `~/.local/share/bash-completion/completions/kubectl` but kubectl Tab doesn't do the completion for me. BTW: I am able to directly source that file to have it work. Maybe my version of bash-completion is old (on centos7.8, yum info says it is 2.1)? When was this feature added? How do I get my bash-completion version?

**Comment by scop** [comment]
Re naming rules: see `type __load_completion`, but basename, basename.bash, and _basename work.
Re completion not loaded: the standard Troubleshooting section of README.md instructions apply.
Re version: yes 2.1 is old, but dynamic loading was added in 2.0.

**Comment by nngo** [comment]
`type __load_completion` doesn't print out anything on my centos 7.8.2003, so I am guessing dynamic loading somehow is broken on on bash-completion on this platform. Looking at `/usr/share/bash-completion/bash_completion`, it says it is RELEASE: 2.1 in the comments.  I tried running `set -v` before attempting the completion, and didn't get anything useful.
With `set -x`, it dump lots of info which I am not sure. Grepping /usr/share/bash-completion/bash_completion for ".local/share" or XDG_DATA_HOME returns no references.

FYI: Under centos 8.2.2004, `type __load_completion` shows the `dirs` that it checks and my custom completions under `~/.local/share/bash-completion/completions/` works.

Also, the on demand completion filenames that it scans would be a good addtion to the FAQ section of the README.md

**Comment by scop** [comment]
It's possible that the function names have changed, and I don't think it was broken in 2.1, just different. But that's such an old version that we don't really "support" it here any more.

FAQ amended, see eda24f85af3b7eebeb49daba34d65259019b729c

**Comment by nngo** [comment]
Thanks for updating the docs. I am able to workaround by directing sourcing my completion files by adding the following to my `~/.bashrc`:

```bash
for f in ~/.local/share/bash-completion/completions/*; do
  source $f
done
```

**Comment by MestreLion** [comment]
> Thanks for updating the docs. I am able to workaround by directing sourcing my completion files by adding the following to my `~/.bashrc`:
> 
> ```shell
> for f in ~/.local/share/bash-completion/completions/*; do
>   source $f
> done
> ```

Suggestion: use a different directory for such files, since `~/.local/share/bash-completion/completions/` is meant for _on-demand, dynamically loaded_ completions, and you're "eagerly" sourcing yours. You could use, for example,  `~/.local/share/bash-completion/bash_completion.d/`, to mimic the name (and behavior) of the legacy, eagerly-loaded `/etc/bash_completion.d`.

This way you can easily migrate/update the completions when/if you make dynamic loading work.

**Comment by nngo** [comment]
> Suggestion: use a different directory for such files, since `~/.local/share/bash-completion/completions/` is meant for _on-demand, dynamically loaded_ completions, and you're "eagerly" sourcing yours. You could use, for example, `~/.local/share/bash-completion/bash_completion.d/`, to mimic the name (and behavior) of the legacy, eagerly-loaded `/etc/bash_completion.d/`.
> 
> This way you can easily migrate/update the completions when/if you make dynamic loading work.

Thanks for the suggestion. I have modified my ~/.bashrc to check `~/bash_completion.d` to mirror `/etc/bash_completion.d` for the eager loading of those completions on my CentOS 7.8 machine:

```shell
for f in ~/bash_completion.d/*; do
  source $f
done
```
