### ISSUE TITLE
lftp: support space-delimited lines in bookmarks file

### ISSUE THREAD

**Issue by wolfgangkarall** [scop/bash-completion#412]
lftp happily reads space delimited key-value lines from the booksmarks file, see

https://github.com/lavv17/lftp/blob/e888e824a274ea3dedaca888c82fa86f7003a952/src/keyvalue.cc#L56

But the completion only looks for cut's default delimiter, i.e. TAB:

https://github.com/scop/bash-completion/blob/c0f6a6d09c88a23441a46c351eff25f23e64b528/completions/lftp#L24

Using awk it will work the same way as lftp:

`awk '{ print $1 }' ~/.lftp/bookmarks`

**Comment by scop** [comment]
Thanks for pointing this out. That plain simple `awk` isn't exactly the same, because we are using `-s` to `cut`. I'm not sure exactly why though. Will fix.
