### ISSUE TITLE
.RECIPEPREFIX confuses autocompletion for Makefille targets

### ISSUE THREAD

**Issue by zyxue** [scop/bash-completion#413]
I asked about this on 

https://stackoverflow.com/questions/61735439/recipeprefix-confuses-autocompletion-for-makefille-targets,

and learned it could be a `bash-completion` problem, wondering if anyone could provide some guidance, please.

**Comment by scop** [comment]
Works for me with current bash-completion. Your question mentions version 1.3 which is ages old, I suggest upgrading, see bash-completion@2 on homebrew and be sure to have bash 4 or later available as well.

**Comment by zyxue** [comment]
Thank you! I updated to bash-completion@2 and changed my login bash to 5 (following instruction on https://unix.stackexchange.com/a/196059/145789), and it works now.
