### ISSUE TITLE
completion function does not exist in interactive shell until the completion is attempted.

### ISSUE THREAD

**Issue by nikita-skobov** [scop/bash-completion#415]
Forgive my ignorance if this is completely as intended, but I have an issue where I cannot use the completion function for curl: `_curl`. When I open a new shell, and try to run:

```sh
_curl
```
I get:
```sh
bash: _curl: command not found
```

If I then try to do:
```sh
curl --<TAB><TAB>
```

Then suddenly `_curl` exists, and I can call it.

My guess is that this is an intentional feature of bash-completion to avoid having too many functions sourced in the user's environment? Can you point me to how this is implemented, as the `bash-completion` file is fairly long and complicated.

If it is necessary, my system is arch linux, and bash-completion was installed via pacman, and located in
```
/usr/share/bash-completion
/usr/share/bash-completion/bash_completion
# the curl file exists here:
/usr/share/bash-completion/completions/
/usr/share/bash-completion/helpers
```

And my `.bashrc` file includes this line:

```
[ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion
```

**Comment by scop** [comment]
Yes, it's very much intentional. It starts from `_completion_loader` defined as the default completion (`complete -D -F _completion_loader`). See also the last few paragraphs of https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion.html#Programmable-Completion

**Comment by nikita-skobov** [comment]
Thank you very much, that was exactly what I was looking for.
