### ISSUE TITLE
ssh completion for "host*" doesn't work

### ISSUE THREAD

**Issue by Hazzard17h** [scop/bash-completion#425]
In my `.ssh/config` I have some hosts with * suffix:
```
Host host*
    User user
    HostName ip/hostname

Host *-proxy
    Port         443
    ProxyCommand nc -X connect -x 127.0.0.1:3128 %h %p
```
So that I can do `ssh host` or `ssh host-proxy` in some scenarios.  
With that "host*" completion doesn't work, while I expect that typing `ssh h<TAB>` gives `ssh host `.

It seems that could be a simple fix:
```diff
diff --git a/bash_completion b/bash_completion
index 9a97fa7c..1d7c9b91 100644
--- a/bash_completion
+++ b/bash_completion
@@ -1739,7 +1739,7 @@ _known_hosts_real()

     # append any available aliases from ssh config files
     if [[ ${#config[@]} -gt 0 && -v aliases ]]; then
-        local hosts=$(command sed -ne 's/^[[:blank:]]*[Hh][Oo][Ss][Tt][[:blank:]]\{1,\}\([^#*?%]*\)\(#.*\)\{0,1\}$/\1/p' "${config[@]}")
+        local hosts=$(command sed -ne 's/^[[:blank:]]*[Hh][Oo][Ss][Tt][[:blank:]]\{1,\}\([^#*?%]*\)\(.*\)\{0,1\}$/\1/p' "${config[@]}")
         COMPREPLY+=($(compgen -P "$prefix" \
             -S "$suffix" -W "$hosts" -- "$cur"))
     fi
```

**Comment by scop** [comment]
Interesting find, thanks. Although your change appears to make things better, there's more we want to fix here I think.

First, the treatment of `#` here appears to be based on the incorrect assumption that it would make the remainder of the line after it a comment. It takes such effect only when it appears as a first character on a line, or when preceded only by whitespace.

Second, we fail to process the remainder of a line after a token that contains one of the special characters.

So let's say for
```
Host a b* c?d e%%lo *f
```
...we should be offering `a`, `b`, `c`, and `e`.

I believe this could be a correct fix, but it makes a bunch of test cases fail- Will have to look into them separately, but I guess they may be making some broken expectations too.

```diff
diff --git a/bash_completion b/bash_completion
index 9a97fa7c..fede47e4 100644
--- a/bash_completion
+++ b/bash_completion
@@ -1741,5 +1741,5 @@ _known_hosts_real()
     if [[ ${#config[@]} -gt 0 && -v aliases ]]; then
-        local hosts=$(command sed -ne 's/^[[:blank:]]*[Hh][Oo][Ss][Tt][[:blank:]]\{1,\}\([^#*?%]*\)\(#.*\)\{0,1\}$/\1/p' "${config[@]}")
+        local -a hosts=($(command sed -ne 's/^[[:blank:]]*[Hh][Oo][Ss][Tt][[:blank:]]\(.*\)$/\1/p' "${config[@]}"))
         COMPREPLY+=($(compgen -P "$prefix" \
-            -S "$suffix" -W "$hosts" -- "$cur"))
+            -S "$suffix" -W '${hosts[@]%%[*?%]*}' -- "$cur"))
     fi
```
