### ISSUE TITLE
Color-Bug if ip is an alias

### ISSUE THREAD

**Issue by johannes-schmatz** [scop/bash-completion#436]
If ip is an alias to 'ip -c' (colored output), then the completion for ip addr show dev outputs some worse escape sequences.
The completed device names are not correct.

FIX:
put in command for absolute path to command, do not use alias.
```
$ PAGER=cat git diff
diff --git a/bash_completion b/bash_completion
index 1a7f5634..16cd47d8 100644
--- a/bash_completion
+++ b/bash_completion
@@ -1006,11 +1006,11 @@ _available_interfaces()

    COMPREPLY=($({
        if [[ ${1:-} == -w ]]; then
-            iwconfig
+            command iwconfig
        elif [[ ${1:-} == -a ]]; then
-            ifconfig || ip link show up
+            command ifconfig || command ip link show up
        else
-            ifconfig -a || ip link show
+            command ifconfig -a || command ip link show
        fi
    } 2>/dev/null | awk \
        '/^[^ \t]/ { if ($1 ~ /^[0-9]+:/) { print $2 } else { print $1 } }'))
```

**Comment by scop** [comment]
A generic problem with bypassing aliases is that doing so will break setups that have the commands aliased for a real reason which makes them actually work (BTW the proposed fix touches not only ip, but iwconfig and ifconfig as well without a mention). If we accept this, by the same reasoning we should do this for every single command we invoke, which is not pretty. We do it for a select few currently only.

Offhand, I suppose the best thing would be if `ip` had an auto-color mode or something that would not try to colorize if stdout is not a pty.

**Comment by johannes-schmatz** [comment]
ip has a no-color mode with `-c=never`.
use `ip -c=never` to don't get colored output.

**Comment by scop** [comment]
Can't use it, it's a too new addition. For example on Ubuntu 18 (and we support much older distros too):
```
$ ip -V
ip utility, iproute2-ss180813
$ ip -c=never a
Option "-c=never" is unknown, try "ip -help".
```

**Comment by scop** [comment]
I guess we could look into ugliness like `ip -c=never foo || ip foo` but we need to address at least in 5 places in bash_completion, and completions/ip. Would be better if the tools that colorize would just automatically DTRT. But meh, could you submit a real PR for those mentioned places along with some test cases that set the `ip -c` alias to verify that the fixes work and don't break older versions?

**Comment by johannes-schmatz** [comment]
pull request is out. done.
