### ISSUE TITLE
Completions fail with 'unbound variable' error if 'nounset' option is set

### ISSUE THREAD

**Issue by siteshwar** [scop/bash-completion#44]
Tab completions fail with 'unbound variable' error if 'nounset' option is set :

```
# set -u
# ls /roo<TAB>bash: !ref: unbound variable
bash: !ref: unbound variable
bash: words[i]: unbound variable
```

```
bash-completion version 2.1.
```

**Comment by scop** [comment]
Known problem, documented in README.md

**Comment by scop** [comment]
On 2nd thought, let's leave this open, maybe people notice better that way that it's a known issue.

**Comment by siteshwar** [comment]
Yes it's a known problem, but is there a planned fix or workaround for it ?

**Comment by scop** [comment]
I'm not aware of anyone working on it. The workaround is not to use `nounset`.

**Comment by deekej** [comment]
In case we dedicate somebody to work on this and fix it, will you accept the patch?

**Comment by scop** [comment]
See discussion in #45

**Comment by scop** [comment]
To facilitate looking into things by folks that are interested in this stuff, I pushed a new `nounset` branch which runs the test suite in `nounset` mode (failing spectacularly for now as expected), has #45 applied, and contains some initial bits to get the first unit test to succeed in that mode. Feel free to hack away and submit pull requests (as minimal/clean as possible) against that branch.

**Comment by jwalt** [comment]
Just for the record, this is a different workaround with little clutter:

At the start of `__reassemble_comp_words_by_ref` and `_filedir`:

    trap "set -$-" RETURN; set +o nounset

It doesn't solve the problem that 3rd-party completion scripts exhibit the same incompatibility, but for me it works fine and could be expanded to cover other shell options as well.

**Comment by mgoldshteyn** [comment]
Now I am running into this problem with the above fix:

    set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
    -bash: set: -i: invalid option

Turning on xtrace with file and line enabled by changing $PS4 and pressing TAB in an attempt to expand the name of a dir in the current directory, I get the source of the errors as follows:
...
    +(/usr/share/bash-completion/bash_completion:17): _upvars(): eval 'words=("${@:3:2}")'
    ++(/usr/share/bash-completion/bash_completion:1): _upvars(): words=("${@:3:2}")
    +(/usr/share/bash-completion/bash_completion:18): _upvars(): shift 4
    +(/usr/share/bash-completion/bash_completion:7): _upvars(): ((  0  ))
    ++(/usr/share/bash-completion/bash_completion:1): _get_comp_words_by_ref(): set -himxBHs
    -bash: set: -i: invalid option
    set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
    +(/usr/share/bash-completion/bash_completion:25): _init_completion(): _variables
    +(/usr/share/bash-completion/bash_completion:2): _variables(): [[ d =~ ^(\$(\{[!#]?)?)([A-Za-z0-9_]*)$ ]]
...
    +(/usr/share/bash-completion/bash_completion:64): _init_completion(): [[ -n '' ]]
    +(/usr/share/bash-completion/bash_completion:66): _init_completion(): return 0
    ++(/usr/share/bash-completion/bash_completion:1): _init_completion(): set -himxBHs
    -bash: set: -i: invalid option
    set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
    +(/usr/share/bash-completion/bash_completion:5): _cd(): local 'IFS=
    ' i j k
    +(/usr/share/bash-completion/bash_completion:7): _cd(): compopt -o filenames
    +(/usr/share/bash-completion/bash_completion:11): _cd(): [[ -z '' ]]
    +(/usr/share/bash-completion/bash_completion:12): _cd(): _filedir -d
...
    +(/usr/share/bash-completion/bash_completion:15): _filedir(): [[ -d != -d ]]
    +(/usr/share/bash-completion/bash_completion:35): _filedir(): [[ 0 -ne 0 ]]
    ++(/usr/share/bash-completion/bash_completion:1): _filedir(): set -himxBHs
    -bash: set: -i: invalid option
    set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
    +(/usr/share/bash-completion/bash_completion:13): _cd(): return
    ++(/usr/share/bash-completion/bash_completion:1): _cd(): set -himxBHs
    -bash: set: -i: invalid option
    set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]

Can anyone please tell me what is using this `-i` option and how I can remove it?

**Comment by scop** [comment]
This is done now in the sense that I went through the test suite and have been using `nounset` mode myself for a bit. It is likely that I didn't catch everything, but any remaining ones are considered bugs that need a fix from now on.

3rd party completions are affected too, I'm preparing to send a patch at least for git's completion soon once I gather some more confidence that I caught most of the issues.
