### ISSUE TITLE
xfreerdp not completing rdp file names

### ISSUE THREAD

**Issue by af7567** [scop/bash-completion#440]
When connecting to work through a remote desktop gateway I can download a .rdp file from the office and then connect to the office desktop by running "xfreerdp COMPUTERNAME.rdp". After a "recent" update to bash-completion on slackware-current I can't press tab to complete the file name anymore. Sorry I have no idea what version the change happened.
I used to be able to type "xfreerdp ./COMP\<TAB\>" and it would auto complete.

**Comment by scop** [comment]
I don't think we've ever actually supported  `*.rdp` completions intentionally -- if it has worked, it has been coincidental. But we do now, fix in 1e4d185eacc988997bb977c7bffe77f584fbdbba. Thanks for the report!
