### ISSUE TITLE
Handle bsdtar (libarchive) formats (like .zip)

### ISSUE THREAD

**Issue by asdil12** [scop/bash-completion#443]
When using bsdtar, completion should also work for the bsdtar supported formats like .zip, .rar, .iso, .cpio, etc.

**Comment by scop** [comment]
Basically I believe this would be a matter of adding those filename suffixes to the `tars` variable in the beginning of `__tar_detect_ext` if we're invoking bsdtar. But what's the exact list of suffixes we should add?

**Comment by asdil12** [comment]
According to https://www.libarchive.org/#:~:text=Reads%20a%20variety%20of%20formats,xz%2C%20lzma%2C%20or%20compress.

> * Reads a variety of formats, including tar, pax, cpio, zip, xar, lha, ar, cab, mtree, rar, and ISO images.
> * Writes tar, pax, cpio, zip, xar, ar, ISO, mtree, and shar archives.

**Comment by scop** [comment]
Hm read/write difference adds some complexity.
