### ISSUE TITLE
line 226: syntax error near unexpected token `done'

### ISSUE THREAD

**Issue by tobip** [scop/bash-completion#445]
I just installed bash-completion and get following error message:

```
bash: /usr/share/bash-completion/bash_completion: line 226: syntax error near unexpected token `done'
bash: /usr/share/bash-completion/bash_completion: line 226: `    done'
```
Version 2.11
Do you have any hint?

**Comment by scop** [comment]
README.md, Troubleshooting section. Perhaps incompatible bash version, very hard to tell.

**Comment by tobip** [comment]
Do you know how I could investigate this?
My bash version is `5.0.18(1)-release`.

I read the whole Troubleshooting section but couldn't find anything that suits the error message.

**Comment by scop** [comment]
The start of the Troubleshoting section describes how to turn on tracing. You need to do it before loading bash_completion, so something like
```
bash --norc
set -x
source /path/to/bash_completion
```
How did you install bash-completion? What's your environment (OS, distribution, ...)?

**Comment by scop** [comment]
Closing due to lack of info.

**Comment by akinomyoga** [comment]
FWIW, this type of error happens when the user defines a custom alias that conflicts with commands or keywords used in `bash_completion`. In this case, I guess the user defines an alias named `do`. However, `do` is a fundamental keyword used in Bash so should not be overridden by an alias.
