### ISSUE TITLE
Latest homebrew package points to the wrong version directory

### ISSUE THREAD

**Issue by phillipb** [scop/bash-completion#448]
When installing the from homebrew, my `bash_completion.sh` file is trying to source the wrong path. It's expecting the version to be 2.7, but the current version is 2.11. After changing to 2.11, things work.

Current bash_completion.sh
```
        if shopt -q progcomp && [ -r /usr/local/Cellar/bash-completion@2/2.7/share/bash-completion/bash_completion ]; then
            # Source completion code.
            . /usr/local/Cellar/bash-completion@2/2.7/share/bash-completion/bash_completion
        fi
    fi
```

**Comment by scop** [comment]
The homebrew package is maintained independently of this project, issues with it need to be reported there.
