### ISSUE TITLE
What is the policy towards completion documentation and configuration?

### ISSUE THREAD

**Issue by gavenkoa** [scop/bash-completion#455]
I seek an improvement that requires special documentation globally and per command `env`: https://github.com/scop/bash-completion/issues/452

As I understand project aim is to provide sane completions out of the box.

For heavy users it is not enough. Some completions might provide extra if you tune it.

**What way project intend to inform users about particular command completion features and available options?**

**What way completion can be custmizable (specially prefixed env var, specially named file)?**

**Comment by gavenkoa** [comment]
I used 3rd party completions (for Gradle) that mention in README.md about caching.

https://github.com/Bash-it/bash-it uses some special env vars for customizations, like `BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE`.

This project itself  has `doc/bash_completion.txt` & mentions `COMP_` prefixed env vars.

**Comment by scop** [comment]
> **What way project intend to inform users about particular command completion features and available options?**

There is no general intent to provide customizability; on the contrary actually. But in case there is some, it's likely it's going to be through env vars, and they will be documented in doc/bash_completion.txt like they currently are.

> **What way completion can be custmizable (specially prefixed env var, specially named file)?**

Likely through env vars in case we implement some customizability. But see above.
