### ISSUE TITLE
Inappropriate tab completions for TZ, TERM, LANG in nonassignment context

### ISSUE THREAD

**Issue by FeepingCreature** [scop/bash-completion#457]
As per https://github.com/scop/bash-completion/blob/master/bash_completion#L682 , TZ is completed with timezones. However, this completion also applies in cases where a timezone is inappropriate, such as `grep TZ <tab><tab>`, where we want to complete with local files, not timezones. Since it specifically _doesn't_ trigger for `TZ=<tab><tab>`, I'm having a hard time seeing where this completion is useful.

**Comment by scop** [comment]
Ouch, reproduced.

This completion is useful for example in `export TZ=`<kbd>Tab</kbd>, and `echo $TER`<kbd>Tab</kbd>.

The function in question (`_variables`) should likely be split in two:
a) one that completes variable names (latter case in above), and
b) the one that completes values for "known" variable names.

a) could be applied quite liberally as it now is, but b) should be applied more sparingly; only in the `export` and the like cases (`env`, `declare` etc) as well as if we can do it at the beginning of a command line.
