### ISSUE TITLE
chown group name not completed

### ISSUE THREAD

**Issue by jidanni** [scop/bash-completion#468]
Completion of the user name worked fine in
`# chown jidanni /some/dir`
But stumbles when one adds the dot and tries to also complete the group name, e.g.,
`# chown jidanni.jidanni /some/dir`

**Comment by scop** [comment]
That's intentional, dot as a separator used that way is deprecated since a long time ago, no longer even documented e.g. in my Ubuntu 18 chown manpage, and I think it doesn't even work everywhere any more. Use a colon instead.

**Comment by jidanni** [comment]
Ah, they [should](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=44770) have warned me!
