### ISSUE TITLE
Is it possible to use the deprecated files like _yum?

### ISSUE THREAD

**Issue by samfux84** [scop/bash-completion#469]
Hi,

We would like to install bash-completion in user space and provide it to our cluster users as module that they can load (instead of installing it through the operating systems package manager).

I noticed, that there is no file "yum", but a file "_yum" that contains the comment:

```
# yum(8) completion                                        -*- shell-script -*-

# Use of this file is deprecated.  Upstream completion is available in
# yum > 3.2.25, use that instead.
```

But since we don't want to use the package manager of the OS, is it still possible to use the deprecated "_yum" file?

There are some more deprecated files:

```
[spackapps@leoopen-ops-01 completions]$ ls _*
_cal  _chfn  _chsh  _dmesg  _eject  _hexdump  _hwclock  _ionice  _look  _mock  _modules  _newgrp  _nmcli  _renice  _repomanage  _reptyr  _rtcwake  _runuser  _su  _svn  _svnadmin  _svnlook  _udevadm  _write  _yum
[spackapps@leoopen-ops-01 completions]$ 
```

Will removing the underscores break anything? Because as mentioned above, I would like to have everything in one central place, such that users just have to load 1 module.

Best regards

Sam

**Comment by scop** [comment]
Files prefixed with underscore will be automatically loaded by `bash_completion` on demand for commands for which no other completion source is found, no matter if it's from a distro package, as long as the files are in appropriate dirs. The underscore just causes them to be tried as the last resort. See `__load_completion` in `bash_completion` for implementation details.

**Comment by samfux84** [comment]
Thank you for your reply.
