### ISSUE TITLE
$ kill %<TAB>

### ISSUE THREAD

**Issue by jidanni** [scop/bash-completion#471]
I can do
```
$ kill <TAB>
```
and it shows me nicely all the pids I can kill.

However
```
$ kill %<TAB>
```
can't even find %1!

> Yes, that is what the 'jobs' command is for.

I know that.

**Comment by scop** [comment]
Not sure where the "Yes, ..." quote comes from, can you elaborate?

Also, do you know of a command we could use to robustly get the jobspecs for `%`<kbd>Tab</kbd> completion? `jobs` does list that, but I don't know if there's any documentation or specification of the output format, and not sure if grabbing first number enclosed in square brackets on each row is the best thing we have avaialble.

**Comment by jidanni** [comment]
I was just talking to myself,
> like this.

Mmmm, as to where to get that info... Perhaps the bash author knows.

**Comment by scop** [comment]
That was too easy.
