### ISSUE TITLE
at now + 33 d…

### ISSUE THREAD

**Issue by jidanni** [scop/bash-completion#472]
```
$ at now + 33 d<TAB>
dan.c        default.xml  dongshi/     dwants  
```
That should complete to "days".

**Comment by scop** [comment]
We do not ship a completion for `at` currently at all.

**Comment by jidanni** [comment]
Yes. I'm saying that there should be. I'm not saying that what you ship is wrong. Though the result is the same to the user.

**Comment by scop** [comment]
Would be good if there was. However it could also be shipped along with "at", not us; in general we'd like that. New completions are generally added in case someone submits it and volunteers to maintain it, and also then we usually might request contacting upstream first, see CONTRIBUTING.md.

If requesting a new completion from us, would be helpful if the request was clearly marked as such, so people won't spend time debugging and verifying if something is wrong with software we actually do ship.

**Comment by jidanni** [comment]
OK but... many packages' upstream hasn't been active for years...

**Comment by scop** [comment]
> OK but... many packages' upstream hasn't been active for years...

Elaborated a bit on that in 5b7ac58888967626a7d4cdcb33a1225e4790fe1f
