### ISSUE TITLE
Lazy loading completions for subcommands / multi-word commands

### ISSUE THREAD

**Issue by n8henrie** [scop/bash-completion#475]
Hello,

Is there a way to lazy-load completions for (possibly third-party) subcommands of commands?

For example, the password manager [pass](https://git.zx2c4.com/password-store) has its own completion that works great. It also allows for third-party plugins -- an excellent example is [pass otp](https://github.com/tadfisher/pass-otp), which provides for MFA through the `pass otp` subcommand and has its own completion file.

This works fine when placed into `BASH_COMPLETION_COMPAT_DIR`, since both are eagerly loaded, but I'm trying to move as many of these as possible into `~/.local/share/bash-completion/completions/` to take advantage of lazy loading (and speed up my slow terminal launch time).

I've tried adding a symlink to the completion for `pass-otp` there as well as renaming the file `pass otp`, but whenever I try `pass otp i[TAB][TAB]`, nothing happens (hoping to see `pass otp insert`).

Similarly, the `brew services` subcommand for homebrew.

As much as possible I'm trying to keep these as symlinks to the files in `/usr/local/etc....` so that they are automatically upgraded with the packages, but so far the only solution I've found is e.g. `cat pass-otp >> pass`, which obviously won't survive an update.

Any other suggestions? Many thanks in advance.

**Comment by n8henrie** [comment]
As another workaround that won't survive an update, insert a line that sources the subcommand's completion just before the command's `complete -F` line. For example:

```bash
source /usr/local/etc/bash_completion.d/pass-otp
complete -o filenames -F _pass pass`
```

This is similar to just `cat`ing it like I noted above, but at least in this case if the *subcommand* (`pass-otp` in this example) updates, its updates should be reflected.

**Comment by scop** [comment]
There is no generic mechanism for that, and I don't think bash's default completion loader functionality that we use would apply to this use case.

`bash_completion` comes with the `_xfunc` function that can be used to call completion functions from other files, lazy loading them as necessary, but that would require the main `pass` completion to explicitly use it. See examples of use in bash-completion sources.

One thing that would survive an upgrade
- place a completion of your own to `~/.local/share/bash-completion/completions/pass`
- call the completion function something that won't clash with the real `pass` completion, e.g. `_my_pass_hack`
- source the otp completion file in it as well as the real `pass` completion one
- replace the pass completion with the real one in your function body
- generate completions using the real pass function once
- finally unset your function
For an example of this pattern, see `_vncviewer_bootstrap` in our `completions/vncviewer`.

Aside, if homebrew installs dozens of completions to the old compat dir, something seems off. I suspect at least some of these are packaging issues in homebrew or package upstreams. If you can paste the file listing of your compat completion dirm along with the information which homebrew package which file is from if possible, I'd be interested in having a look and seeing if I can get some of those fixed.

**Comment by n8henrie** [comment]
Thanks for your thorough response and input!

I think I've found a much simpler workaround that seems to fit the bill (not sure why I didn't think of this before).

Contents of `~/.local/share/bash-completion/completions/pass`

```bash
source /usr/local/etc/bash_completion.d/pass
source /usr/local/etc/bash_completion.d/pass-otp
```

Contents of `~/.local/share/bash-completion/completions/brew`

```bash
source /usr/local/etc/bash_completion.d/brew
source /usr/local/etc/bash_completion.d/brew-services
```

In conjunction with `BASH_COMPLETION_COMPAT_DIR=/dev/null`, I can confirm that they are not eagerly loaded\*, however everything works as expected with e.g. `pass [TAB][TAB]` and `pass otp [TAB][TAB]`.

This strategy should also solve my problem of package upgrades, as long as homebrew continues to symlink the same completion file (which I suspect it will for the most part). So I think this issue can be closed from my perspective.

> If you can paste the file listing of your compat completion dir along with the information which homebrew package which file is from if possible, I'd be interested in having a look and seeing if I can get some of those fixed.

Very gracious of you. This should give you the packages and version numbers; there is a chance that 1 or 2 I have manually symlinked at some point, but the vast majority were not placed there by me.

```console
$ realpath /usr/local/etc/bash_completion.d/*
/usr/local/Cellar/aria2/1.35.0/etc/bash_completion.d/aria2c
/usr/local/Cellar/awscli/2.1.10/etc/bash_completion.d/aws_bash_completer
/usr/local/Cellar/heroku/7.47.5/etc/bash_completion.d/bash
/usr/local/Homebrew/completions/bash/brew
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/completions/bash/brew-services
/usr/local/Cellar/sk/0.9.3/etc/bash_completion.d/completion.bash
/usr/local/Cellar/docker/19.03.14/etc/bash_completion.d/docker
/usr/local/Cellar/docker-compose/1.27.4_1/etc/bash_completion.d/docker-compose
/usr/local/Cellar/docker-machine/0.16.2/etc/bash_completion.d/docker-machine-prompt.bash
/usr/local/Cellar/docker-machine/0.16.2/etc/bash_completion.d/docker-machine-wrapper.bash
/usr/local/Cellar/docker-machine/0.16.2/etc/bash_completion.d/docker-machine.bash
/usr/local/Cellar/exercism/3.0.13/etc/bash_completion.d/exercism_completion.bash
/usr/local/Cellar/fd/8.2.1/etc/bash_completion.d/fd.bash
/usr/local/Cellar/glib/2.66.2_1/etc/bash_completion.d/gapplication
/usr/local/Cellar/glib/2.66.2_1/etc/bash_completion.d/gdbus
/usr/local/Cellar/gh/1.3.1/etc/bash_completion.d/gh
/usr/local/Cellar/glib/2.66.2_1/etc/bash_completion.d/gio
/usr/local/Cellar/git/2.29.2/etc/bash_completion.d/git-completion.bash
/usr/local/Cellar/git/2.29.2/etc/bash_completion.d/git-prompt.sh
/usr/local/Cellar/gopass/1.10.1/etc/bash_completion.d/gopass
/usr/local/Cellar/glib/2.66.2_1/etc/bash_completion.d/gresource
/usr/local/Cellar/glib/2.66.2_1/etc/bash_completion.d/gsettings
/usr/local/Cellar/hub/2.14.2/etc/bash_completion.d/hub.bash_completion.sh
/usr/local/Cellar/hyperfine/1.11.0/etc/bash_completion.d/hyperfine.bash
/usr/local/Cellar/john-jumbo/1.9.0/etc/bash_completion.d/john.bash
/usr/local/Cellar/jupyterlab/2.2.9_1/etc/bash_completion.d/jupyter
/usr/local/Cellar/sk/0.9.3/etc/bash_completion.d/key-bindings.bash
/usr/local/Cellar/launchctl-completion/1.0/etc/bash_completion.d/launchctl
/usr/local/Cellar/unar/1.10.1/etc/bash_completion.d/lsar.bash_completion
/usr/local/Cellar/node/15.4.0/etc/bash_completion.d/npm
/usr/local/Cellar/open-completion/1.0.4/etc/bash_completion.d/open
/usr/local/Cellar/pandoc/2.11.2/etc/bash_completion.d/pandoc
/usr/local/Cellar/pass/1.7.3/etc/bash_completion.d/pass
/usr/local/Cellar/pass-otp/1.2.0/etc/bash_completion.d/pass-otp
/usr/local/Cellar/pip-completion/20190723/etc/bash_completion.d/pip
/usr/local/Cellar/pyenv/1.2.21/completions/pyenv.bash
/usr/local/Cellar/restic/0.11.0/etc/bash_completion.d/restic
/usr/local/Cellar/ripgrep-bin/12.1.1/etc/bash_completion.d/rg.bash
/usr/local/Cellar/task/2.5.1/etc/bash_completion.d/task.sh
/usr/local/Cellar/tmux/3.1c_1/etc/bash_completion.d/tmux
/usr/local/Cellar/unar/1.10.1/etc/bash_completion.d/unar.bash_completion
/usr/local/Cellar/wireguard-tools/1.0.20200827/etc/bash_completion.d/wg
/usr/local/Cellar/wireguard-tools/1.0.20200827/etc/bash_completion.d/wg-quick
/usr/local/Cellar/youtube-dl/2020.12.12/etc/bash_completion.d/youtube-dl.bash-completion
```

\* I just inserted a `touch brew-testfile.txt` into the completion file (e.g. `/usr/local/etc/bash_completion.d/brew`) and ran something like `watch ls *.txt` to see when each of them showed up.

**Comment by scop** [comment]
Good to hear my overengineered suggestion contributed to a much better fix for you :)

Thanks for the list, copied over to #477, closing this one.
