### ISSUE TITLE
RubyGems support

### ISSUE THREAD

**Issue by voxik** [scop/bash-completion#48]
It would be nice if bash-completion supported RubyGems. I just opened ticket with the script in RubyGems issue tracker, but since I am not sure where is the better place, I'll link it here as well, so I'll possible have feedback from both sides. Thx

[1] https://github.com/rubygems/rubygems/issues/1627

**Comment by scop** [comment]
Very much preferring it to be shipped with rubygems, if possible.

**Comment by akinomyoga** [comment]
https://github.com/mernen/completion-ruby seems to contain an implementation. I added it to the wiki page of external completions.

**Comment by scop** [comment]
With that, I think we can close this.
