### ISSUE TITLE
[Question] bash-completion-extras package is not exited on redhat8 yum repo

### ISSUE THREAD

**Issue by invent-lwj** [scop/bash-completion#485]
`bash-completion-extras` package is not exited on redhat8 yum repo, i found completions folder increased many of command, this is moved from `bash-completion-extras`? If yes, `bash-completion` has contain `bash-completion-extras` command now? 
Thanks!

**Comment by scop** [comment]
I'm not sure I understand your question, but bash-completion packaging in Red Hat as well as all other distributions is beyond us. I suggest contacting your distributor in matters related to the packaging.
