### ISSUE TITLE
On debian 10.7 of windows docker, the package name after ‘apt install‘ cannot be automatically completed

### ISSUE THREAD

**Issue by even0306** [scop/bash-completion#490]
On debian 10.7 of windows docker, the package name after ‘apt install‘ cannot be automatically completed, the command can be completed, but the package name following cannot be automatically completed

**Comment by scop** [comment]
Please follow the instructions in README.md's Troubleshooting section.

**Comment by even0306** [comment]
> Please follow the instructions in README.md's Troubleshooting section.

Already tried. Currently bash-completion has been installed and added to bash.bashrc, I also manually executed ’source /usr/share/bash-completion/bash-completion’. It is confirmed that other commands Jun has taken effect, but the package name after ‘apt install’can never be completed. In addition, I tried it on the docker version of debian 10.7 on the Linux side, but the package name cannot be completed.

**Comment by scop** [comment]
To be able to assist, we likely need to see the trace output mentioned in troubleshooting.

Also, note that completion for `apt` is not shipped by this project, but apt itself. Does package name completion work with `apt-get`? That we do ship.

**Comment by even0306** [comment]
> 为了提供帮助，我们可能需要查看故障排除中提到的跟踪输出。
> 
> 另外，请注意，`apt`此项目未提供的完成，而是本身提供的。软件包名称补全可以使用`apt-get`吗？我们做船。

I tried ’apt-get’, but I can’t complete it
[bash-completion.log](https://github.com/scop/bash-completion/files/5794569/bash-completion.log)

**Comment by scop** [comment]
It's trying to obtain completions by running `apt-cache --no-generate pkgnames`. `--no-generate` means you need to have a populated package cache (i.e. have run `apt update`), that's at least one scenario where it won't produce completions otherwise. Our apt-get completion does similar things, and is likely affected due to the same reason.

**Comment by even0306** [comment]
> 它正在尝试通过运行获得完成`apt-cache --no-generate pkgnames`。`--no-generate`意味着您需要拥有一个填充的程序包缓存（即run `apt update`），至少在这种情况下，它不会产生补全。我们的apt-get完成会做类似的事情，并且可能由于相同的原因而受到影响。

Apt update has been executed, and all packages have been kept up to date without any errors, but the package name is still not completed

**Comment by scop** [comment]
Have you tried what `apt-cache --no-generate pkgnames` outputs if you run it?

**Comment by even0306** [comment]
> Have you tried what `apt-cache --no-generate pkgnames` outputs if you run it?

Tried it, show ```E: Could not open file  - open (2: No such file or directory)```

**Comment by scop** [comment]
Ok, that's the problem you need to fix to get the completion (and likely some other stuff as well) to work. It is out of scope of this project/here though; if you need help with that I suggest you seek for help from the Debian/apt channels you can find.
