### ISSUE TITLE
Some completions don't work and some do...

### ISSUE THREAD

**Issue by Dvergatal** [scop/bash-completion#493]
Hi i have compiled bash-completion 2.10 in buildroot and i have a strange behaviour. For some of packages autocompletion does work but for some it does not. All completion files are in /usr/share/bash-completion/completions the working ones and the not working. I.e. i have there nmcli auto completion which works and for some reason systemctl is not.

I dunno what can cause this strange behaviour and i would be appreciate if you could help me solving this odd behaviour.

**Comment by scop** [comment]
Please follow the Troubleshooting section of README.md, and paste the trace output (after verifying it doesn't contain anything confidential) here in case you still need assistance after looking into it.

**Comment by Dvergatal** [comment]
Hi @scop thx for your quick reply. I will check it asap.

**Comment by Dvergatal** [comment]
Ok, this is the log which was made by setting set -x
[systemctl.log](https://github.com/scop/bash-completion/files/5869969/systemctl.log)

**Comment by Dvergatal** [comment]
Ok i have solved the issue. The problem was taht in /ets/passwd my user had /bin/sh instead /bin/bash. I thougth that if /bin/sh is a link to bash than it doesn't matter that in /etc/passwd it is /bin/sh... I'm closing the issue.
