### ISSUE TITLE
[RFE] allow easier reload of completions (upon updating/adding completion file)

### ISSUE THREAD

**Issue by jnpkrn** [scop/bash-completion#51]
My assumption was that after a package update that brings along it's own
completion file

```
source /etc/profile
```

would do the trick automatically in the current `ssh` session.

Unfortunately, that's not the case, because of
https://github.com/scop/bash-completion/blob/2.3/bash_completion.sh.in#L1:

```
# Check for interactive bash and that we haven't already been sourced.
if [ -n "${BASH_VERSION-}" -a -n "${PS1-}" -a -z "${BASH_COMPLETION_COMPAT_DIR-}" ]; then
```

where `BASH_COMPLETION_COMPAT_DIR` is marked as `readonly` variable, hence cannot be redefined/unset in the current shell session.

So while one could apparently do:

```
exec "$0" "$@"
```

it does not seem particularly appealing nor practical.

Is there a way to make `bash-completion` more reload-friendly?

**Comment by scop** [comment]
If you want to reload bash-completion, I suggest simply directly sourcing `bash_completion` itself.

But packages should install their completions according to the instructions in README.md (search for "I author/maintain package X"); when installed properly there, the completions will get loaded automatically on demand.

Note that already loaded completions will stay in effect unless removed with `complete -r` (and automatically loaded again later).

**Comment by jnpkrn** [comment]
Thanks a lot for the answer, that addresses all the concerns.
FTR, this is the context: https://bugzilla.redhat.com/show_bug.cgi?id=1349465
