### ISSUE TITLE
bash_completion: line 251: conditional binary operator expected

### ISSUE THREAD

**Issue by wizwuz** [scop/bash-completion#512]
I get the following error when running bash:
laptop-4:bash-completion brainsurf$ source bash_completion 
-bash: bash_completion: line 251: conditional binary operator expected
-bash: bash_completion: line 251: syntax error near `exclude'
-bash: bash_completion: line 251: `    if [[ -v exclude ]]; then'

Environment:
MacOS Big Sur 11.2.3
bash 5.1.4
bash-completion 2.11 installed with homebrew in:
/usr/local/Cellar/bash-completion@2/2.11/share/bash-completion/bash_completion

**Comment by scop** [comment]
Please double check that your current bash version is indeed 5.x, what does `echo "$BASH_VERSION"` output? If it is 4.2 or later, please see Troubleshooting in README.md for information how to generate a debug trace, and attach it here.

**Comment by scop** [comment]
The environment variable tells the actual active version. bash --version tells the version of bash that would be running if you executed `bash` from that shell.

**Comment by wizwuz** [comment]
Sorry you're right, I had the updated bash installed but not set as my shell, so the terminal process was still using the old bash 3. However bash_complete was failing silently during terminal startup, only after I tried it manually it showed the error. It would be nice to catch this kind of environment fault and not crash, although I understand the root cause fix is to set the shell correctly. Thanks! :-)

**Comment by scop** [comment]
Our suggested installation procedure already doesn't load `bash_completion` for non-bash or bash < 4.2 shells:
https://github.com/scop/bash-completion/blob/b404f62bd38640f791ea1b297e2a24f769244b0a/bash_completion.sh.in#L5

I tend to think that's good enough.

**Comment by joffrey92** [comment]
Hello, I had the same issue with Mac and bash 5.3.3 installed by brew:
`bash-completion/bash_completion: line 95: conditional binary operator expected`

The issue was happening when I did run a script with "#!/bin/bash" inside.

```bash
$ type bash
bash is /opt/homebrew/bin/bash
$ bash --version
GNU bash, version 5.3.3(1)-release (aarch64-apple-darwin24.4.0)
Copyright (C) 2025 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ /bin/bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin24)
Copyright (C) 2007 Free Software Foundation, Inc.
```

Replacing the script with "#!/usr/bin/env bash" fixed it
