### ISSUE TITLE
Spurious backslash inserted: $a/x<TAB> becomes \$a/xyz

### ISSUE THREAD

**Issue by jidanni** [scop/bash-completion#516]
I type:
```
$ l=/home/jidanni/images
$ ls $l/P_20<TAB>
```
At this point the second line becomes:
```
$ ls \$l/P_20200617_060304_Gamma_18.jpg
```
I have no idea why a backslash is being inserted here.

It has no good use and just messes the command up.

TAB should just do:
```
$ ls $l/P_20200617_060304_Gamma_18.jpg
```

$ apt-show-versions bash
bash:amd64/unstable 5.1-2+b1 uptodate
$ apt-show-versions bash-completion
bash-completion:all/unstable 1:2.11-2 uptodate

**Comment by scop** [comment]
#290, #438
