### ISSUE TITLE
/usr/share/Package_A/completions/Package_B : Say where to report bugs to in each file

### ISSUE THREAD

**Issue by jidanni** [scop/bash-completion#517]
Let's say a user finds a file on their system,
```
/usr/share/Package_A/completions/Package_B
```
Well, without any comments inside that file as to which package one
should report bugs to, one would assume they should go to `Package_A`.

Sure, with enough hunting around on their system, perhaps they could
find the answer.

But still, it would be best to put a note inside each such file.

**Comment by scop** [comment]
That's OS/distro/distro version specific information, maintaining that is an effort we don't want to embark on here.

On debian based systems `dpkg -S /usr/share/Package_A/completions/Package_B` should give a hint, and similarly `rpm -qf /usr/share/Package_A/completions/Package_B` on rpm based ones, I suppose e.g. `apk` and `brew` and others likely have something similar.
