### ISSUE TITLE
IFS='*' freezes bash

### ISSUE THREAD

**Issue by imgx64** [scop/bash-completion#52]
If you set `IFS='*'` then try tab completion, bash freezes and uses 100% CPU. The only way to stop it is kill -9.

I'm using Fedora 24 and bash-completion 2.3.

**Comment by scop** [comment]
Reproduced, but I'm not sure why you'd do that?

**Comment by imgx64** [comment]
To be honest, no reason at all. I was just thinking of ways to break my own scripts (and making them fool-proof in the process), and ended up with a frozen shell..

But I can think of a hypothetical reason, splitting a *-delimited string:
```
$ foo='a*b*c'
$ set -f
$ IFS='*'
$ bar=($foo)
$ declare -p bar
declare -a bar='([0]="a" [1]="b" [2]="c")'
```

**Comment by imgx64** [comment]
This seems to be a bug in bash ( https://lists.gnu.org/archive/html/bug-bash/2016-07/msg00004.html ), but I think bash-completion could at least print an error instead of looping infinitely. The long-term solution would be implementing [cleanly controllable completion environment](https://github.com/scop/bash-completion/pull/45#issuecomment-221191015).

**Comment by scop** [comment]
If someone wants to submit a clean, minimal patch that works around this, I can have a look, but honestly I'm not too keen on spending much time at all for such a corner case especially if it's caused by a bash bug.

**Comment by imgx64** [comment]
This was fixed in Bash. Closing.
