### ISSUE TITLE
cryptsetup completion out of date

### ISSUE THREAD

**Issue by lkraav** [scop/bash-completion#54]
What's the update process - is there a maintainer for a specific app like `cryptsetup` to be pinged here, or just open a pull request personally?

**Comment by scop** [comment]
Just open a PR. Be sure to look at CONTRIBUTING.md, and include also new cases for the test suite for your changes if at all applicable (meaning if they're testable in the first place, and not entirely trivial).

**Comment by akinomyoga** [comment]
I think this issue can be closed. Pull requests are always welcome for any completions.
