### ISSUE TITLE
Unable to checkout repository on Windows

### ISSUE THREAD

**Issue by imgx64** [scop/bash-completion#55]
Checking out the repository using Git for Windows produces the below error:

```
$ git clone 'https://github.com/scop/bash-completion.git'
Cloning into 'bash-completion'...
remote: Counting objects: 22529, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 22529 (delta 2), reused 0 (delta 0), pack-reused 22519
Receiving objects: 100% (22529/22529), 3.27 MiB | 1.00 MiB/s, done.
Resolving deltas: 100% (16332/16332), done.
Checking connectivity... done.
fatal: cannot create directory at 'test/fixtures/_filedir/a"b': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

I reported it on [git-for-windows#828](https://github.com/git-for-windows/git/issues/828) but they pointed out that the repository contains files that are invalid on Windows.

These files are used in tests. Can these files be generated during the tests instead of being committed to the repository?

**Comment by scop** [comment]
Should be fixed now, please give it a try

**Comment by imgx64** [comment]
There's another invalid file: test/fixtures/man/man3/Bash::Completion.3pm.gz

**Comment by scop** [comment]
That should be taken care of now as well.

**Comment by imgx64** [comment]
Works now. Thank you.
