### ISSUE TITLE
Externally available completion on wiki: add opensc and p11-kit

### ISSUE THREAD

**Issue by Jakuje** [scop/bash-completion#606]
It looks like I do not have permission to edit the following wiki page

https://github.com/scop/bash-completion/wiki/Externally-available-completions

I would like to add at least the two following completions I know about:

(many); [OpenSC](https://github.com/OpenSC/OpenSC/); Generated from manual pages in [doc/tools/Makefile.am](https://github.com/OpenSC/OpenSC/blob/master/doc/tools/Makefile.am); [./]
`p11-kit`, `trust`; [p11-kit](https://github.com/p11-glue/p11-kit/); [bash-completion/*](https://github.com/p11-glue/p11-kit/tree/master/bash-completion); [./]

**Comment by akinomyoga** [comment]
Thank you! I have updated the Wiki. Could you check the added information is correct?

@scop I'm wondering if there is a reason that we don't allow external people to edit the Wiki?

**Comment by Jakuje** [comment]
Thank you! Looks good to me.

**Comment by scop** [comment]
Nah, restricting Wiki edits to collaborators only was an oversight. Fixed now, thanks for letting me know and for these additions.
