### ISSUE TITLE
Doc: "cd & Makefile, believed to be a bug in bash" - Link to source?

### ISSUE THREAD

**Issue by Jonta** [scop/bash-completion#607]
https://github.com/scop/bash-completion/blame/dc0b6fbcf8d70f8a89cac7c035d551b201fcc543/README#L73

I've searched a bit, but no luck

**Comment by scop** [comment]
Looks like it was added in 33582d81ee22a0258eee1a688d2b9c7e4ed5a1d0, almost two decades ago. That's all the info I have about it, and to be honest, if that issue still exists, I'm kind of confused what it has to do with bash-completion or completions in the first place :thinking:

**Comment by Jonta** [comment]
@ianmacd Do you happen to remember?
