### ISSUE TITLE
release doesn't contain configure

### ISSUE THREAD

**Issue by sleep-walker** [scop/bash-completion#64]
2.3 release doesn't seem to be normal release but just tag in GIT. Please, provide dist tarball with configure script etc.

https://lists.gnu.org/archive/html/guix-devel/2016-08/msg00479.html

**Comment by scop** [comment]
It is there. Download the tar.xz one from the releases, not tags view.
https://github.com/scop/bash-completion/releases

**Comment by sleep-walker** [comment]
Thanks for clarification, my bad.
