### ISSUE TITLE
Using -o option with ssh command seems to break known hosts completion

### ISSUE THREAD

**Issue by egamby** [scop/bash-completion#647]
## Describe the bug

When I want to auto-complete a ssh command with -o option, for instance `ssh -o ForwardX11=yes <tab>`, the list of known hosts is not provided anymore.

## To reproduce

1. Type `ssh -o ForwardX11=yes <tab>`
2. Auto-completion proposes all the possibilities: `Display all 2497 possibilities? (y or n)`

## Expected behavior

Completion should propose the list of known hosts.

## Versions

- [ ] Operating system name/distribution and version: Debian 11
- [ ] bash version, `echo "$BASH_VERSION"`: 5.1.4(1)-release
- [ ] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: 2.11

## Debug trace
[debug_trace.txt](https://github.com/scop/bash-completion/files/7492460/debug_trace.txt)

**Comment by scop** [comment]
Oh, good catch! Makes me wonder how we've missed this for this long :thinking:. Anyway #648 contains a candidate fix, but seems there are a few remaining things to iron out, see the PR.

**Comment by egamby** [comment]
Thanks a lot for the quick fix. I confirm this solves the issue :-)

**Comment by scop** [comment]
Let's not close this yet, #648 is not merged yet. It'll autoclose this when it is.
