### ISSUE TITLE
failglob causes the failure of `_variable` in generating `${assoc[index]}` as a completion

### ISSUE THREAD

**Issue by EmilySeville7cfg** [scop/bash-completion#663]
## Describe the bug

`-S` `compgen` option causes `_variables` function fail for `${array[index` (lines 683-684):

```bash
        COMPREPLY+=($(compgen -W '$(printf %s\\n "${!'${BASH_REMATCH[2]}'[@]}")' \
            -P "${BASH_REMATCH[1]}${BASH_REMATCH[2]}[" -S ']}' -- "${BASH_REMATCH[3]}"))
```

Without -S everything works fine.

## To reproduce

We can reproduce this behavior interactively inside Bash without `_variables` function: 

1. `declare -A assoc=([aa]=1 [ab]=2)`
2. `[[ '${assoc[a' =~ ^(\$\{[#\!]?)([A-Za-z0-9_]*)\[([^]]*)$ ]]`
3. `e $(compgen -W '$(printf %s\\n "${!'${BASH_REMATCH[2]}'[@]}")' -P "${BASH_REMATCH[1]}${BASH_REMATCH[2]}[" -S ']}' -- "${BASH_REMATCH[3]}")`
4. See problem

![image](https://user-images.githubusercontent.com/42812113/145806673-1eb5f893-ddc2-4c9c-ae4b-c81cc1f772d3.png)

## Expected behavior

No error expected even with `failglob` enabled.

## Versions (please complete the following information)

- [x] Operating system name/distribution and version: Linux Mint 20.2 Cinnamon
- [x] bash version, `echo "$BASH_VERSION"`: 5.1.0(1)-release
- [x] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: 2 10

**Comment by akinomyoga** [comment]
Thanks for the report. This is actually not related to the option `-S` of `compgen` but caused by the pathname expansions applied to `$(...)`. We may look at the following reduced test case:

```bash
$ bash --norc
$ shopt -s failglob
$ COMPREPLY=($(echo '${assoc[ab]}'))
bash: no match: ${assoc[ab]}
```
