### ISSUE TITLE
~ complete is broken

### ISSUE THREAD

**Issue by EmilySeville7cfg** [scop/bash-completion#668]
## Describe the bug

When I type `code ~<TAB>` I obtain the `bash: no match: COMPREPLY[0]=~root` error:

![image](https://user-images.githubusercontent.com/42812113/147057068-afa5fbaa-9b63-4724-87a6-dd578b9a37c5.png)

## To reproduce

1. `code ~<TAB>`
2. See problem

## Expected behavior

No error expected even with `failglob` enabled.

## Versions (please complete the following information)

- [x] Operating system name/distribution and version: Linux Mint 20.2 Cinnamon
- [x] bash version, `echo "$BASH_VERSION"`: 5.1.0(1)-release
- [x] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: 2.10

**Comment by akinomyoga** [comment]
@EmilySeville7cfg Thank you for the report! This has been fixed in #670.
