### ISSUE TITLE
Source user's .bash_completion.d

### ISSUE THREAD

**Issue by arichiardi** [scop/bash-completion#67]
Hello and thanks for this awesome project!

I was wondering if it is a good idea to source files from `$HOME/bash_completion.d` as well.

I have a couple of examples where I need to keep the files local to a single user with no access to `/etc`.

I know I have a single file in `~` but the script come separate and I'd like the idea to just dump stuff in a folder like in `/etc`.

Thanks a lot for your (and contributor's) work!

**Comment by scop** [comment]
We already load user completions on demand from `$BASH_COMPLETION_USER_DIR`, grep for the variable name in `bash_completion` to see the default. The whole `/etc/bash_completion.d` dir and the associated eager loading mechanism is deprecated, so I don't plan to add a user counterpart to it.

**Comment by arichiardi** [comment]
Oh didn't find this in my ubuntu (`16.04`) that's why it was not working. I need to upgrade the script. Sorry about the noise.
