### ISSUE TITLE
Support xbps files (void linux packages)

### ISSUE THREAD

**Issue by tornaria** [scop/bash-completion#685]
## Describe the feature/solution

Support for void linux packages, namely xbps files (`*.xbps`). These are plain old tar files compressed with zstd, so it's trivial to support. In fact I monkey patched my system version of `bash-completion-2.11` as shown below, and it works fine.

```diff
--- bash-completion-2.11_2/usr/share/bash-completion/completions/tar
+++ /usr/share/bash-completion/completions/tar	2021-12-23 10:25:47.636095345 -0300
@@ -422,7 +422,7 @@
 
 __tar_detect_ext()
 {
-    local tars='@(@(tar|gem|spkg)?(.@(Z|[bgx]z|bz2|lz?(ma|o)|zst))|t@([abglx]z|b?(z)2|zst))'
+    local tars='@(@(tar|gem|spkg|xbps)?(.@(Z|[bgx]z|bz2|lz?(ma|o)|zst))|t@([abglx]z|b?(z)2|zst))'
     ext="$tars"
 
     case "$tar_mode_arg" in
```

## Maintenance (please complete the following information)

- [x ] This is a request for new completion

**Comment by scop** [comment]
Thanks! A bit modified version included in #688
