### ISSUE TITLE
lvm completion of pvremove and vgcreate doesn't work: command not found

### ISSUE THREAD

**Issue by Whissi** [scop/bash-completion#69]
To reproduce, type `vgcreate foo /dev/s[TAB]`

After pressing `TAB` key your terminal will display

> \# vgcreate foo /dev/s-bash:  : command not found

Same issue with `pvremove`.

Tested against lvm2-2.02.145.

Gentoo-Bug: https://bugs.gentoo.org/591724

**Comment by sitsofe** [comment]
According to https://bugzilla.redhat.com/show_bug.cgi?id=1382674 this is fixed by https://github.com/scop/bash-completion/commit/2ed36b808cee5416139a034477a223f4910b53d8 ...

**Comment by scop** [comment]
Oh, I forgot that this was reported here as well, closing.
