### ISSUE TITLE
hostname completion fails terribly when IFS is set to some unusual value

### ISSUE THREAD

**Issue by calestyo** [scop/bash-completion#723]
## Describe the bug

Not sure whether this is kinda expected respectively simply unsupported, but when `IFS` is set to e.g. `x`, then completing hostnames (and possibly other completions, too) fails terribly.

## To reproduce

1. `IFS=x`
2. `ssh <tab tab>`
3. Gives e.g.
```
$ ssh bash: set -o noglob: command not found
bash: set -o noglob: command not found
bash: set +o noglob: command not found
bash: set -o noglob: command not found
bash: set -o noglob: command not found
bash: set -o noglob: command not found

amundsen.example.org^Jamundsen ssh-ed25519 AAAAC3NzaC
...
...
...
```

## Expected behavior

Catch unusual `IFS` at some top level for all bash-completions?

## Versions (please complete the following information)

- [ ] Operating system name/distribution and version: Debian sid
- [ ] bash version, `echo "$BASH_VERSION"`: 5.1.16(1)-release
- [ ] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: 2.11

Cheers,
Chris.

**Comment by calestyo** [comment]
Any I think it also fails when `set -e` is in effect.

**Comment by scop** [comment]
IFS issues are generally ones we've wanted to fix. And we've already done a bunch, for example this particular case no longer fails that way in current master. (Not sure it produces useful/wanted results there either, though.)

`set -e` on the other hand I'm not entirely sure we want or "need" to support. No objections if we find a clean and sustainable way to do it, but having that setting in effect in interactive shells is quite rarely desirable in the first place.

The two mentioned issues are different, so in a sense they would be better off reported and handled separately. But on the other hand, if we can figure out a general way to set the shell in a desired state wrt various settings like these at start of a completion and reset them back to their previous state at end, in that way they are related. For example the return hook mechanism in https://github.com/scop/bash-completion/issues/720#issuecomment-1093764792 could lead towards a way to restore the state, and perhaps there was already some related work in another issue/PR, I forget.

**Comment by calestyo** [comment]
Ah then it's probably just because of Debian's older bash-completion. Guess you can close that ticket then?

With `set -e`,... also not sure whether it's needed to support that or not (which is also why I didn't open a separate ticket)... just wanted to let you know :-D
