### ISSUE TITLE
Implement new `_comp_xfunc` and naming

### ISSUE THREAD

**Issue by scop** [scop/bash-completion#732]
Per https://github.com/scop/bash-completion/discussions/539#discussioncomment-2213575

New `_comp_xfunc` implementation, renaming of target functions, docs in `doc/api-and-naming.md`

**Comment by scop** [comment]
Docs done in https://github.com/scop/bash-completion/pull/731/commits/ed168f068f8b6f53610db408dd3a30859e1b5a3d

**Comment by akinomyoga** [comment]
Thank you for working on these related changes. If there is anything I can do, please let me know as these big changes are something that I have originally triggered. For example, the implementation of `_comp_xfunc` and renaming of the public interfaces defined in `bash_completion` (while keeping the old names), etc.

**Comment by scop** [comment]
No problem, as far as I'm concerned it's first come first serve, whoever wants to implement something and starts work on it, gets it :) For example this one, feel free to grab it. And there are a few PR's pending for review.

Re the backwards compatibility names, I was thinking it could be great if those could be shipped e.g. in a separate file in /etc/bash_completion.d, but that doesn't work that well for files in completions/*. But perhaps we could do that for things where it does work.

**Comment by akinomyoga** [comment]
Thanks. OK, I'll work on `_comp_xfunc`.
