### ISSUE TITLE
can't autocomplete webp image files using feh

### ISSUE THREAD

**Issue by kgabor545** [scop/bash-completion#743]
I have no idea how to solve this, and don't know it is some manjaro customization or the problem is in this package, so I am sorry if I am posting it to the wrong place.

## Describe the bug

The auto completion doesn't work on webp images.

Some default autocompletion is used when I type the feh command (unfortunately I can't figure it out how it is recognized, but I can't find autocompletion files in feh package, so I suppose it is some default). 

## To reproduce

1. install feh
2. Type 'feh '
3. try to autocomplete an image file with webp extension

## Expected behavior
Not sure. If it IS some default, maybe the expected behavior is to autocomplete any file

## Versions (please complete the following information)

- [ ] Manjaro
- [ ] bash version: 5.1.16(1)-release
- [ ] bash-completion version: 2.11

**Comment by akinomyoga** [comment]
I think this has been already fixed in #682. Could you try the latest version of `bash-completion` from the mater branch?

**Comment by scop** [comment]
Assuming fixed indeed, please do make a note here if you find the fix doesn't work.
