### ISSUE TITLE
'crontab -l > foo<tab>' completes ok but 'crontab -l >| foo<tab>' does not

### ISSUE THREAD

**Issue by jeremyhetzler** [scop/bash-completion#769]
If I have an existing file "foobar", then 
`crontab -l > foo<tab>`
will complete "foobar" successfully.

However, 
`crontab -l >| foo<tab>`
will not complete (finds no matches).

The >| redirection completes ok when using e.g. cat:
`cat qux >| foo<tab>`
completes ok.

How can I get crontab to autocomplete when using the >| redirection?

**Comment by akinomyoga** [comment]
Thank you for the report! This is because the redirection pattern in the following line is incomplete:

https://github.com/scop/bash-completion/blob/f5756939a45e5da774274293768da2d7e547d8c4/bash_completion#L1006
