### ISSUE TITLE
Support new subsections (at least, 3type, 2type, and 3const)

### ISSUE THREAD

**Issue by alejandro-colomar** [scop/bash-completion#778]
## Describe the bug

The Linux man-pages project is adding new subsections: at least `3type`, `2type`, and `3const`.  Maybe also `3head` and `2head`.

That would mean adding directories such as `man3type`, and file extensions such as `.3type`.

Autocomplete for those sections is not working currently.  Maybe an approach could be to allow arbitrary subsections.  If not, another approach would be to support those specific subsections.

## To reproduce

Install the Linux man-pages from source (`sudo make install`) from the current [git HEAD](https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/), then

`man -s 3type [TAB]` should show only a bunch of options, since there are only a few dozens of pages in that subsection.  Instead, it shows that there are 9k+ possibilities, since it doesn't understand the subsection 3type.

## Versions (please complete the following information)

- [x] Operating system name/distribution and version: `Debian Sid`
- [x] bash version: `5.1.16(1)-release`
- [x] bash-completion version: `2.11`

**Comment by scop** [comment]
Thanks for the heads up. https://github.com/scop/bash-completion/pull/788 takes the approach of allowing (almost) arbitrary suffixes to numeric sections. See related commit in the PR for more discussion.

**Comment by scop** [comment]
Also filed https://github.com/scop/bash-completion/issues/789 for the `-s` completion.
