### ISSUE TITLE
got err at "/usr/share/bash-completion/bash_completion:2296: parse error near `\n'  "

### ISSUE THREAD

**Issue by 1oda** [scop/bash-completion#784]
Ubuntu 22.04.1 LTS
`apt-get install bash-completion`
then
`type _init_completion` but failed
so  i continued
`source /usr/share/bash-completion/bash_completion` add to `~/.zshrc`
the relogin,return this :
`/usr/share/bash-completion/bash_completion:2296: parse error near `\n'`

don't know why, when i googled this ,found that maybe `'<>' or EOF unindented `
please help me solve it ,every time login ,it always appers

**Comment by 1oda** [comment]
![image](https://user-images.githubusercontent.com/10447318/182855099-be7c7665-e491-44c4-9687-0dafdb5a3c1d.png)

**Comment by akinomyoga** [comment]
`bash-completion` does not support `zsh`, but you seem to be trying to source it in `zsh`.

**Comment by 1oda** [comment]
> `bash-completion` does not support `zsh`, but you seem to be trying to source it in `zsh`.

ok，now just returned this error, but the regular functionality is available in `zsh`.
