### ISSUE TITLE
Strange envrionment entry

### ISSUE THREAD

**Issue by D630** [scop/bash-completion#82]
Hi,

After sourcing `/usr/share/bash-completion/bash_completion` from `bash-completion_2.1-4.3_all.deb` my environment contains the entry `"'><;|&(:`. That prevents me from using `dbus-update-activation-environment --systemd --all` or `systemctl --user import-environment`.

**Comment by D630** [comment]
Ok. It has been caused by  `/etc/bash_completion.d/npm` of `npm_1.4.21+ds-2_all.deb`.

**Comment by scop** [comment]
Ok, it should be reported against the npm package then.
