### ISSUE TITLE
Test suite runs out of tree completions instead of fallbacks

### ISSUE THREAD

**Issue by scop** [scop/bash-completion#836]
## Describe the bug

Current fedoradev CI runs fail, because we end up testing not our `_adb`, but the system installed `/usr/share/bash-completion/completions/adb` (-> `/usr/share/android-tools/completions/adb`), and it has env var leakages.

In our test suite, we should test only our fallbacks, not the possibly installed corresponding non-underscore prefixed completion files.

I suspect this is a regression from 19840401612f23582e819ef277260299151334c6.

## To reproduce

Run test suite on current fedoradev.

## Expected behavior

Test our `_adb` instead of the system installed `adb`.

## Versions (please complete the following information)

- [x] Operating system name/distribution and version: Fedora development
- [ ] bash version, `echo "$BASH_VERSION"`:
- [ ] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`:

**Comment by akinomyoga** [comment]
I think there are roughly three ways to solve this issue. 1) One is to revert the change 19840401612f23582e819ef277260299151334c6, and 2) another is to introduce some mechanism to change the behavior inside the test framework. Or, 3) we can manually `source completions/_adb` before the corresponding test.

I introduced 19840401612f23582e819ef277260299151334c6 thinking that the completion files prefixed by `_` are for older external commands that are not shipped with their completion files so the completion files unprefixed by `_` should be preferred if they are found in any paths. If you agree with this treatment, I think option 3 would be the easiest solution.

**Comment by scop** [comment]
The change in 1984040 is fine, I wouldn't revert it.

I would prefer a mechanism that would take care of this automatically, rather than having to remember to do it separately for all underscore prefixed completions. I'd also like it to be done so that it's something we do in the test suite, without adding complexity or quirks to normal runtime use. But if we don't come up with something we are happy with, let's go with 3.

One thing I can think of would be to create a "shadow" completions dir for the tests suite that would symlink all underscore prefixed completions to the corresponding non-underscore prefixed name, and make sure that dir is injected to the lookup path before the system dirs. Probably `$BASH_COMPLETION_USER_DIR` / `$XDG_DATA_HOME` could be (ab)used for this. Not sure if this will be clean enough for our taste.

**Comment by akinomyoga** [comment]
> One thing I can think of would be to create a "shadow" completions dir

I like this solution as this keeps the desired behavior of the loader that the unprefixed completions are preferred to the underscored completions. Maybe we can also add an explicit test for that in `test/t/unit/test_unit_load_completion.py`.

**Comment by scop** [comment]
#842 experiments with a statically populated dir. This isn't fully automatic in the sense that one needs to remember to update it, but there's a `make` helper target for doing that, and a pre-commit check that should fail if the dir is not properly populated.

I considered creating the dir dynamically, but I didn't find a spot where I'd be happy with its placement (so that it wouldn't unnecessarily create the dir all the time, and it would work with both `make` and direct `pytest`, etc). Writing to in tree during build has quirks, and a varying tempdirs have theirs too.
