### ISSUE TITLE
rsync ssh remote paths are double-escaped (incorrect since rsync 3.2.4)

### ISSUE THREAD

**Issue by stefanor** [scop/bash-completion#848]
## Describe the bug

[In 3.2.4](https://download.samba.org/pub/rsync/NEWS#3.2.4) rsync changed the default way that arguments were passed to a remote ssh host, to no longer require double-escaping.

The bash-completion still double-escapes.

## To reproduce

1. Create `/tmp/foo bar` on a remote machine (named `remote`)
2. Type `rsync remote:/tmp/foo`
3. Press tab.
4. Note that this completes to `rsync remote:/tmp/foo\\\ bar`, which is incorrect.

## Expected behaviour

The remote path should only be escaped once, not twice (unless the `--old-args` argument is passed to rsync (>= 3.2.4)

## Versions (please complete the following information)

- [x] Operating system name/distribution and version: Debian testing
- [x] bash version, `echo "$BASH_VERSION"`: `5.2.2(1)-release`
- [x] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: `2.11` (Debian: `1:2.11-6`)

**Comment by amalgame21** [comment]
One year later the problem still there.

**Comment by jucor** [comment]
Just got bitten by this. I'd be very grateful for this fix to be merged. Thank you :)
