### ISSUE TITLE
Tests use completion files in home directory

### ISSUE THREAD

**Issue by rrthomas** [scop/bash-completion#87]
When preparing a patch, I had unexpected test failures, which I tracked to bash-completion using `BASH_COMPLETION_HOME_DIR`. Presumably the test suite should clear that variable before running tests.

**Comment by scop** [comment]
Right. To be exact, clearing isn't sufficient with current implementation, and/instead we should set both BASH_COMPLETION_USER_DIR and XDG_DATA_DIRS to values that prevent out-of-tree things from affecting test results.

**Comment by scop** [comment]
I was trying to reproduce this by copying a version of the `ip` completion that is known to fail the related unit tests to `~/.local/share/bash-completion/completions/ip`, and then ran `./runCompletion ip.exp` in the `test` dir, but it didn't fail, so the test suite obviously ended up not using the faulty one from my home dir. I don't have more time to dig deeper now. Can you post an explicit recipe for reproducing the failure here?

**Comment by rrthomas** [comment]
I have the following `~/.bash_completion`:

```
# Code copied from /usr/share/bash-completion/bash_completion, with modified
# setting for home directory

BASH_COMPLETION_HOME_DIR=$HOME/.bash_completion.d

# Glob for matching various backup files.
#
_backup_glob='@(#*#|*@(~|.@(bak|orig|rej|swp|dpkg*|rpm@(orig|new|save))))'

for i in $(LC_ALL=C command ls "$BASH_COMPLETION_HOME_DIR"); do
    i=$BASH_COMPLETION_HOME_DIR/$i
    [[ ${i##*/} != @($_backup_glob|Makefile*|$_blacklist_glob) \
           && -f $i && -r $i ]] && . "$i"
done
```

Other than that, I simply ran all the tests with `make check`.

**Comment by scop** [comment]
But in that case, you are sourcing the custom completion files explicitly yourself (bash-completion is not doing that), and using an environment variable that bash-completion itself doesn't use or know about at all (`BASH_COMPLETION_HOME_DIR`). So clearing that particular one -- or any unknown one for that matter -- is not something that we're going to do in bash-completion. We probably should at least look into avoiding loading of `~/.bash_completion` during tests though, if it has potential to cause problems.

**Comment by rrthomas** [comment]
You're right that reading ~/.bash_completion should be disabled in any case.

**Comment by rrthomas** [comment]
Thanks!
