### ISSUE TITLE
Cannot get this to work at all for bash 5

### ISSUE THREAD

**Issue by sarink** [scop/bash-completion#875]
## Describe the bug

I am using bash 5.2 on a Mac. I have installed `bash-completion@2` with homebrew. I have added the necessary lines to `.bash_profile`, and sourced it. It appears to have loaded successfully? But I have no additional tab completion in my shell (specifically `git`, but I've tried others as well, eg `tree`)

```
sarink:~ $ brew list bash-completion@2
/usr/local/Cellar/bash-completion@2/2.11/etc/profile.d/bash_completion.sh
/usr/local/Cellar/bash-completion@2/2.11/share/bash-completion/ (743 files)
/usr/local/Cellar/bash-completion@2/2.11/share/cmake/ (2 files)
/usr/local/Cellar/bash-completion@2/2.11/share/pkgconfig/bash-completion.pc

sarink:~ $ echo ${BASH_VERSINFO[0]}
5

sarink:~ $ echo $BASH_COMPLETION_VERSINFO
2

sarink:~ $ git --version
git version 2.39.1
```

Any ideas?

**Comment by akinomyoga** [comment]
Not all the completions are provided through this repository. For example, `git` completion, which you tried, is not provided by `bash-completion`, but it is provided by the upstream project. You already seem to have installed `git` in your system, so the completion file should be somewhere in your system. Possible place are

- `/usr/share/bash-completion/completions/git`
- `/usr/share/git-core/contrib/completion/git-completion.bash` (Note: you might find `git-completion.{csh,tcsh,zsh}`, but they are not what we want)
- `$prefix/share/bash-completion/completions/git-completion.sh`, where `prefix` is a path to the install prefix such as `/usr/local/Cellar/gitXXXX/YYYY`
- `$prefix/share/git-core/contrib/completion/git-completion.bash`

If you can find it, you can directly source it or copy the file `git` or `git-completion.bash` to `/usr/local/Cellar/bash-completion@2/2.11/share/bash-completion/completions/git`. If you don't find it, you can download it from

- https://github.com/git/git/blob/v2.39.1/contrib/completion/git-completion.bash

To download the file, press the <kbd>Raw</kbd> button on the top-right corner of the source text area.

**Comment by Nesze** [comment]
I might be seeing the same:

I've been cleaning up my `.bashrc`, and found git-completion is sourced twice:

```bash
$ cat ~/.bashrc
...
[[ -r "$BREW_PREFIX/etc/profile.d/bash_completion.sh" ]] && . "$BREW_PREFIX/etc/profile.d/bash_completion.sh"

if [ -f $BREW_PREFIX/etc/bash_completion.d/git-completion.bash ]; then
  . $BREW_PREFIX/etc/bash_completion.d/git-completion.bash
fi
...
```

I wanted to simplify so dropped the second line, but then git completion is not working anymore. I added some log lines so can see the very same file for git is sourced in the first as well, but something else must be going on which makes it ineffective. What's even more strange, is that for other commands (e.g. kubectl, tmux) completion is working just fine.

```bash
$ # for the record, completions is linked
$ brew completions state
Completions are linked.
$ ls -l /opt/homebrew/etc/bash_completion.d | rg git
lrwxr-xr-x  1 zb  admin  65 12 Feb 16:09 git-completion.bash -> ../../Cellar/git/2.39.1/etc/bash_completion.d/git-completion.bash
lrwxr-xr-x  1 zb  admin  59 12 Feb 16:09 git-prompt.sh -> ../../Cellar/git/2.39.1/etc/bash_completion.d/git-prompt.sh
$ 
```

**Comment by scop** [comment]
I don't see git-completion being sourced twice in the given example. There's a `-f` test for its existence, followed by the sourcing, but no other references visible.

I'm not sure we have much to work with here. In the bug report template, we ask for the debug trace for a reason:
> See Troubleshooting section in README.md how to generate a debug trace,
> copy-paste it into a separate file and attach the file here.

Searching for the issue tracker for `git homebrew` (including closed issues) brings up something you may want to review:
https://github.com/scop/bash-completion/issues?q=is%3Aissue+git+homebrew

**Comment by Nesze** [comment]
Thanks for the link @scop.

Turns out `hub` was messing up `git` in brew completions: https://github.com/scop/bash-completion/issues/387#issuecomment-779485030.

I've uninstalled it, dropped the explicit git completion, and it works like a charm. My lean `.bashrc`:

```
$ cat ~/.bashrc
...
[[ -r "$BREW_PREFIX/etc/profile.d/bash_completion.sh" ]] && . "$BREW_PREFIX/etc/profile.d/bash_completion.sh"
...
```

**Comment by sarink** [comment]
@akinomyoga I do see a ton of completion files under the path `/usr/local/Cellar/bash-completion@2/2.11/share/bash-completion/completions` - are you saying I need to source each of these individually? Also, git is not listed. I should note that I installed this package via homebrew (`brew install bash-completion@2`). If this is only a package to "assist in the development of bash completions" - then how do you actually get the completions? I'm sure if I were to download the official git completion, that that would work, but isn't the point of this repo to install one package rather than dozens for all the tools you may use? I'm confused.

**Comment by akinomyoga** [comment]
> @akinomyoga I do see a ton of completion files under the path `/usr/local/Cellar/bash-completion@2/2.11/share/bash-completion/completions` - are you saying I need to source each of these individually?

No. The files placed in that directory are automatically sourced by `bash-completion` when it is necessary, i.e., when the completion for the command is attempted. So, you do not need to source them manually.

> Also, git is not listed 🤔 .

Yes, so this is the reason that I asked you to copy the file of the git completion in that directory.

> I should note that I installed this package via homebrew (`brew install bash-completion@2`). If this is only a package to "assist in the development of bash completions" - then how do you actually get the completions? I'm sure if I were to download the official git completion, that that would work, but isn't the point of this repo to install one package rather than dozens for all the tools you may use? I'm confused.

You can first read the third and fourth Q&A in the FAQ section of README.

The external package is supposed to put the completion file in the `bash-completion` data directory of the same prefix (i.e., `${prefix}/share/bash-completion/completions`). In this way, for example, when one installs the package `git`, the `git` completion comes with the package `git` and becomes automatically available from `bash-completion`. What the users need to do is *supposed to be* just to install both the packages `git` and `bash-completion` and to make sure to source just one file, `bash_completion`.

However, Homebrew breaks the assumption. When the external package is installed in a different prefix than that of `bash-completion`, `bash-completion` doesn't recognize the completion file. Homebrew installs every package in a distinct prefix, so `bash-completion` never recognizes the completion files installed in different prefixes. This is the reason that the homebrew user needs to manually relocate the completion files to the directory in an appropriate prefix.

In the latest `master` version, there is an improvement in the search for the completion files. Now it also searches for the prefix that the current command is found. But it is not applied in 2.11.

**Comment by sarink** [comment]
👍 That makes sense, thank you for your detailed explanation! I downloaded the `git-completion.bash` file, renamed it to `git`, and moved it to `/usr/local/Cellar/bash-completion@2/2.11/share/bash-completion`. Everything works as expected now

**Comment by scop** [comment]
Good to hear the issues were resolved. Would also be great if someone using brew having experienced the issue could report it against the "hub" package, perhaps they're not aware of the breakage it causes?
