### ISSUE TITLE
dpkg -i 

### ISSUE THREAD

**Issue by jidanni** [scop/bash-completion#876]
dpkg -i file.deb doesn't complete file.deb 
Seen on Debian.

**Comment by scop** [comment]
It does for me on Ubuntu. Please fill in the information asked in the bug report template.

**Comment by jidanni** [comment]
$ echo "$BASH_VERSION"
5.2.15(1)-release
$ (IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")
2.11

**Comment by scop** [comment]
Still waiting for at least the debug trace. From the template:
> See Troubleshooting section in README.md how to generate a debug trace, copy-paste it into a separate file and attach the file here.

**Comment by jidanni** [comment]
OK. It's working again. Odd.
