### ISSUE TITLE
-bash: 404:: command not found after installation

### ISSUE THREAD

**Issue by Brototype** [scop/bash-completion#89]
I just installed it on a fresh MacOS 10.12.1 with brew and the only lines in my `~/.bash_profile` are
````
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi
````
the output in a new terminal is `-bash: 404:: command not found`
I'm not sure how to fix this or what went wrong :/

**Comment by scop** [comment]
The only idea off the cuff I have is that I suggest checking what the file `$(brew --prefix)/etc/bash_completion` contains. Maybe it was downloaded over invalid HTTP URL which resulted in a 404 not found, and that found its way to the file's contents?

(No setup to test brew here, sorry.)

**Comment by Brototype** [comment]
The file looks fine - to be sure is reinstalled via brew but still the same issue.

**Comment by scop** [comment]
The only other tip I have is to enable trace output according to the instructions at https://github.com/scop/bash-completion/#troubleshooting and see if that produces something useful. Be sure to turn on the tracing before loading bash_completion in your .bash_profile. Or fire up a fresh bash (bash --norc), turn on the tracing options, then source bash_completion manually.

If this is of no use, I'm afraid the next stop for you to ask help from should be the brew bash-completion maintainers.

**Comment by Brototype** [comment]
Look at this snippet it looks like it has something to do with `kubectl`
````
...
/sbin:/usr/sbin:/usr/local/sbin
+++ type k3b
++ for i in '$(LC_ALL=C command ls "$BASH_COMPLETION_COMPAT_DIR")'
++ i=/usr/local/etc/bash_completion.d/kldload
++ [[ kldload != @(*~|*.bak|*.swp|\#*\#|*.dpkg*|*.rpm@(orig|new|save)|Makefile*) ]]
++ [[ -f /usr/local/etc/bash_completion.d/kldload ]]
++ [[ -r /usr/local/etc/bash_completion.d/kldload ]]
++ . /usr/local/etc/bash_completion.d/kldload
+++ '[' Darwin = FreeBSD ']'
++ for i in '$(LC_ALL=C command ls "$BASH_COMPLETION_COMPAT_DIR")'
++ i=/usr/local/etc/bash_completion.d/kubectl
++ [[ kubectl != @(*~|*.bak|*.swp|\#*\#|*.dpkg*|*.rpm@(orig|new|save)|Makefile*) ]]
++ [[ -f /usr/local/etc/bash_completion.d/kubectl ]]
++ [[ -r /usr/local/etc/bash_completion.d/kubectl ]]
++ . /usr/local/etc/bash_completion.d/kubectl
+++ 404: Not Found
-bash: 404:: command not found
++ for i in '$(LC_ALL=C command ls "$BASH_COMPLETION_COMPAT_DIR")'
...
````
