### ISSUE TITLE
make -nC needs to be written -n -C to make expansions work

### ISSUE THREAD

**Issue by jidanni** [scop/bash-completion#898]
I had to rewrite
- make -nC ~/bla/bla

to
 - make -n -C ~/bla/bla

to get it to work.

**Comment by akinomyoga** [comment]
Both seem to work the same in my environment. It is supposed to be supported in v2.9 (commit [`8f82fd98`](https://github.com/scop/bash-completion/commit/8f82fd98cc56ac6973ff01407784c3c76b0e462a#diff-1776d90047a6c8d16281efc474f61be0173178c5564bbeddf154f7c4ceb3b07aR97)). Which version of bash-completion do you use?

> make -nC needs to be written -n -C to make expansions work 

What do you mean by the *expansions*? I only see the tilde as something that can be expanded in your examples, but the tilde expansions do not seem to happen for both `make -n -C ~/bla/bla[TAB]` and `make -nC ~/bla/bla[TAB]` in the current master.

**Comment by scop** [comment]
When reporting issues, please fill in the information asked in the new issue report template, so we don't waste time roundtripping and asking the info separately. Filling the template is easier to do in a new report than to backfill in an existing one, so I'm closing this one -- please open a new one with the requested info filled if the issue you saw persists.

**Comment by jidanni** [comment]
Sorry, I meant only one of them could dig the targets out of the makefile. I'll check the versions when I get back on my desktop.
