### ISSUE TITLE
Long lag when completing the command argument of ssh

### ISSUE THREAD

**Issue by szsam** [scop/bash-completion#926]
## Describe the bug
There is a long lag (30 seconds) when completing the command argument of ssh.

## To reproduce

Type 'ssh user@host ', then hit tab. The shell will freeze for 30 seconds.

## Expected behavior

The completion should be fast. The 30-second lag is unacceptable.

## Versions (please complete the following information)

- [x] Operating system name/distribution and version: Ubuntu 20.04.5, WSL2
- [x] bash version, `echo "$BASH_VERSION"`: 5.0.17(1)-release
- [x] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: 2.10

## Additional context
It is the following line that takes 30 seconds, where `cur` is `""`. The output of the `compgen -c -- ''` command contains 10k+ lines on my system.
https://github.com/scop/bash-completion/blob/ac68847b33a1cd030ccbb1accaa5015ae4a9a797/completions/ssh#L356

## Debug trace
[bash_completion_log.txt](https://github.com/scop/bash-completion/files/11207775/bash_completion_log.txt)

**Comment by szsam** [comment]
I suggest that we do not try to complete when `cur` is an empty string.

**Comment by szsam** [comment]
I'm using Ubuntu on WSL (Windows Subsystem for Linux). That might be the reason why the `compgen` is so slow.

**Comment by akinomyoga** [comment]
Similar codes can be found in more completions within the codebase.

```bash
./completions/_svn:42:                COMPREPLY=($(compgen -c -- "$cur"))
./completions/cpio:27:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/dpkg:107:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/fio:78:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/fio:91:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/firefox:36:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/man:33:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/mr:57:                COMPREPLY=($(compgen -c -- "${cur}"))
./completions/mussh:42:            COMPREPLY+=($(compgen -c -- "$cur"))
./completions/mypy:28:            COMPREPLY=($(compgen -c -- "${cur:-py}"))
./completions/perlcritic:37:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/protoc:23:                COMPREPLY=($(compgen -c -- "$cur"))
./completions/querybts:22:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/reportbug:42:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/rpm:83:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/sqlite3:21:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/ssh:189:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/ssh:356:            COMPREPLY+=($(compgen -c -- "$cur"))
./completions/ssh:405:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/ssh:551:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/ssh-keygen:82:                        COMPREPLY=($(compgen -c -- "${cur#*=}"))
./completions/strace:93:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/tar:551:                COMPREPLY=($(compgen -c -- "$cur"))
./completions/tcpdump:31:            COMPREPLY=($(compgen -c -- "$cur"))
./completions/valgrind:86:                    COMPREPLY=($(compgen -c -- "$cur"))
./completions/vpnc:57:            COMPREPLY=($(compgen -c -- "$cur"))
```

I think it would be more consistent to switch the behavior referencing `shopt -q no_empty_cmd_completion`.

**Comment by scop** [comment]
> I think it would be more consistent to switch the behavior referencing `shopt -q no_empty_cmd_completion`.

SGTM. We may want to wrap that in a public utility function to make it harder to forget, easier to test, and make it possible for users to override (even if that's not something we'd generally recommend).
