### ISSUE TITLE
Decide and document quoting rule

### ISSUE THREAD

**Issue by akinomyoga** [scop/bash-completion#932]
> Hmm, I suppose this means we should be quoting all arguments containing variables to any commands or functions we invoke? This PR does not address them all throughout the codebase, but we can take care of them in followup PR's.
>
> I'm starting to feel that we should write up some rules about all this stuff in our docs somewhere, perhaps styleguide.md. And it would be great if there was some tooling that would help by flagging or fixing undesired uses. I wonder if shellcheck or shfmt would accept some of that stuff.
>
> _Originally posted by @scop in https://github.com/scop/bash-completion/pull/931#discussion_r1174403080_

**Comment by scop** [comment]
As we're going quite deep in our support for weird (considering interactive shell) `$IFS` already anyway, I suppose quoting these arguments containing variables fits in that theme. Likely needs to be done for other things as well, for example return values.

I'm not sure how to best write this up rather than to note that quoting needs to be done wherever word splitting can occur (making no assumptions about `$IFS`). Also not sure how long will it take until I start to actually remember to write things that way :stuck_out_tongue: 

(On the other hand, would be nice to remove unnecessary quoting where splitting does not occur, for example in assignments and within `[[ ]]`.)

**Comment by scop** [comment]
Re that unnecessary quoting, filed https://github.com/mvdan/sh/issues/996

**Comment by scop** [comment]
I guess I'd be fine with starting to quote all arguments, return values or the RHS of comparisons no matter if they contain variables or not. That'd make it easier to remember, and would colorize consistently in editors. What do you think?

**Comment by akinomyoga** [comment]
I agree with it. Actually, I personally prefer quoting them independently of IFS, noglob, etc. in the context. Context-independent constructs are easier to read because we do not need to check the contexts in reading.

**Comment by scop** [comment]
Cool. If you feel like it and can think of a good wording, feel free to take a look at filing a style guide PR. I'll get to it eventually myself, too, no pressure.

I think we should follow whatever our tooling (mostly shfmt I guess) does with regards to this, and only apply our "rules" on top of what it does, and not fight the tools.

**Comment by akinomyoga** [comment]
Thank you. I think I can try it, but I have questions.

- `$*` and `${arr[*]}` need to be quoted as `"$*"` and `"${arr[*]}"` even in the contexts where the quoting is usually unnecessary because unquoted `$*` and `${arr[*]}` is still affected by word splitting in bash <= 4.2:
  ```bash
  $ bash-4.2 -c 'a=(1 2 3);IFS=x;v=${a[*]};echo "[$v]"'
  [1 2 3]
  $ bash-4.3 -c 'a=(1 2 3);IFS=x;v=${a[*]};echo "[$v]"'
  [1x2x3]
  ```
  However, `shfmt` requires us to unquote it in a conditional command.
  ```diff
  shfmt
  -    [[ "$*" == abc ]]
  +    [[ $* == abc ]]
  ```
- Do we specify the detailed types of the quoting? Maybe we do not need to be so specific.
  - For example, when `$` or `` ` `` is not included in the string, do we use single quotes `'foo bar'`, double quotes `"foo bar"`, or even `foo\ bar`? By the way, we are using `var=""` in the codebase for the assignments of an empty string.
  - When control characters are included in the string (such as tabs and newlines), do we use `'...'` with raw control characters or `$'...'` with escape sequences such as `\t`?
  - How about when `'`, `"`, `$`, `\`, etc. are included in the string?
