### ISSUE TITLE
Use _comp_split and _comp_compgen in completions/*

### ISSUE THREAD

**Issue by scop** [scop/bash-completion#948]
> Now we have a utility function _comp_split to safely split strings (including the output of the compgen builtin and other commands) without being affected by pathname expansions, unexpected word splitting, etc. [...]
> The changes to completions/* are left for later PRs.

_Originally posted by @akinomyoga in https://github.com/scop/bash-completion/pull/919

**Comment by akinomyoga** [comment]
### Naming of functions that generate completions in COMPREPLY

I would like to discuss the naming of a particular class of functions (including `_filedir`, `_parse_help`, and `_parse_usage`).

For this rewriting, we will switch from `COMPREPLY=($(compgen ...))`, etc. to use `_comp_compgen ...`. One of the frequent cases among them is `COMPREPLY=($(compgen -W '$(_parse_help ...)' -- "$cur"))`. I would like to rewrite them to use new versions of `_parse_help` or `_parse_usage` that directly assign results to `COMPREPLY` (or a specified array).

Then there is a related discussion that I wanted to open. Currently, there are utility functions of the name `_<CATEGORY>` that generate and store completions of the category in `COMPREPLY`, such as `_filedir`, `_ip_addresses`, and `_pids`. The functions `_parse_help` and `_parse_usage` also behave in the same way after the suggested change to store results in arrays. If we just follow the new naming convention, the simple prefixing of `_comp` works for all of them (such as `_comp_filedir`).

- `_comp_filedir`, `_comp_ip_addresses`, `_comp_pids`, ...

But I think there is also a possibility to introduce a namespace or a naming rule for this class of functions, such as

- `_comp_generate_filedir`, `_comp_generate_ip_addresses`, `_comp_generate_pids`, ...
- `_comp_compgen_filedir`, `_comp_compgen_ip_addresses`, `_comp_compgen_pids`, ...
- `_comp_gen_filedir`, `_comp_gen_ip_addresses`, `_comp_gen_pids`, ...
- `_comp_yield_filedir`, `_comp_yield_ip_addresses`, `_comp_yield_pids`, ...
- `_comp_action_filedir`, `_comp_action_ip_addresses`, `_comp_action_pids`, ... (inspired by `compgen -A <action>`)
- or other ways

What do you think?

**Comment by akinomyoga** [comment]
Also, PR #560 by @algorythmic is related to the `_parse_help` change. I have rebased #560. Could you first check #560?

**Comment by akinomyoga** [comment]
I added another PR #950, which I'd like to address before `_parse_{help,usage}`.

----

I'd like to separate related PRs for easier review. There are some dependencies between the planned changes.

- (planned) _parse_help-3 ... non-trivial rewriting using the new function for `_parse_help` (v2)
  - (planned) _parse_help-2 ... non-trivial rewriting using the new function for `_parse_help` (v1)
    - (planned) _parse_help-1 ... new function for `_parse_help` and trivial rewriting
      - #560
      - #950
      - naming of functions that generate completions in `COMPREPLY` [#948 (comment)](#issuecomment-1529412590)
- (planned, WIP) _comp_split-1 ... trivial rewriting using `_comp_split` and `_comp_compgen`
  - (planned, WIP) compgen-W-cmdsub ... fix for `-W "$(...)"` -> `-W '$()'`
- (planned, WIP) _comp_split-* ... non-trivial rewriting using `_comp_split` and `_comp_compgen`

**Comment by scop** [comment]
@akinomyoga what are your thoughts on the status of this? For example a quick `git grep -F "COMPREPLY=("` reveals a few dozen hits I think we could look into before 2.12.

**Comment by akinomyoga** [comment]
As I have replied once in https://github.com/scop/bash-completion/discussions/530#discussioncomment-6642445, I wouldn't request it to be part of 2.12. However, if you like it, I'll try to look at it to see whether it is easy to apply. If it would cause again a bunch of discussions, we can probably postpone applying it not to delay the new release further.

**Comment by akinomyoga** [comment]
I have submitted PRs that replace unquoted array assignments.

- #1083 
- #1084 
  - #1085 
    - #1086 
    - #1087

**Comment by akinomyoga** [comment]
Thank you for reviewing all those issues!

I actually thought the PRs mentioned above were the last ones for replacing `arr=($word)` and `compgen` with `_comp_split` and `_comp_compgen`. The generators of the form `_comp_compgen NAME` were not initially intended for this issue because the generators were introduced in #952 after this issue was raised.  I feel we can now close this issue. But maybe the confirmation itself will take time, so we can remove this from the ToDo list anyway.

**Comment by scop** [comment]
Thanks for the feedback, I'll close this one now per that. I'd like to be able to reduce the number of open issues and PR's to ones for which there is clear intent to work on addressing something in the foreseeable future.
