### ISSUE TITLE
Bump Version

### ISSUE THREAD

**Issue by arcfi** [scop/bash-completion#96]
bash-completion-2.4 is included in several distros (SystemRescueCd, Fedora, etc.) and contains shameful bug for LVM-commands due to redundant whitespaces:
https://github.com/scop/bash-completion/commit/2ed36b808cee5416139a034477a223f4910b53d8#diff-b54ee1bd37f156b3f2d41450174ce540
https://bugzilla.redhat.com/show_bug.cgi?id=1404353
New release will force maintainers to resolve the issue. Thanks.

**Comment by scop** [comment]
2.5 released
