### ISSUE TITLE
Mark which version something was added in

### ISSUE THREAD

**Issue by scop** [scop/bash-completion#963]
## Describe the feature/solution

Similarly as #893 for deprecations, would be good to mark in which version a public API function/variable was added in.

I suppose this should be done for all things in the main `bash_completion` file, as well as any `_comp_xfunc_*` in `completions/*`.

**Comment by akinomyoga** [comment]
I agree with it. Doxygen/JavaDoc has `@since`, so maybe we can mark the version in the code document using it.

**Comment by scop** [comment]
I was just about to suggest the same :+1:

**Comment by scop** [comment]
#961 contains example usage.
