### ISSUE TITLE
long option support for tar broken with version 2.4

### ISSUE THREAD

**Issue by bitstreamout** [scop/bash-completion#98]
Try

`tar --create --file test.tar <TAB>`

does show only option but no files nor directories

`tar --create -f test.tar -<TAB>`
`-A  -c  -d  -r  -t  -u  -x`

 ...  the same for mixed options

`tar --create -f test.tar <TAB>`
`tar --create f test.tar <TAB>`

**Comment by bitstreamout** [comment]
A patch
[x.txt](https://github.com/scop/bash-completion/files/651734/x.txt)

**Comment by scop** [comment]
@bitstreamout Could you file a pull request along with test case demonstrating the failure and the fix for this?

@praiskup FYI

**Comment by akinomyoga** [comment]
The issue is still present. Even worse, when completing the word `./`, it seems to produce the option names as filenames.

```bash
$ tar --create --file a.tar.gz ./[TAB]
./A  ./c  ./d  ./r  ./t  ./u  ./x
```
